/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/course/{course_id}/belts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Belt Info
         * @description Returns descriptive info (headline + description) for each belt in a course.
         */
        get: operations["get_belt_info_course__course_id__belts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Info
         * @description Get current authenticated user info.
         */
        get: operations["get_current_user_info_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enroll User
         * @description Enroll user in a course with onboarding data.
         */
        post: operations["enroll_user_user_enroll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Status
         * @description Authoritative new-vs-returning check, read from the DB.
         *
         *     A returning user has an enrollment and/or learning state, regardless of
         *     what their Clerk `onboarded` metadata says. The frontend uses this to
         *     decide whether to run onboarding or send the user straight to the dashboard.
         */
        get: operations["get_user_status_user_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Progress
         * @description Get user's current progress (topic states and level info).
         */
        get: operations["get_user_progress_user_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push Subscribe
         * @description Store a browser PushSubscription for the current user.
         */
        post: operations["push_subscribe_push_subscribe_post"];
        /**
         * Push Unsubscribe
         * @description Remove a browser PushSubscription (called when the user unsubscribes).
         */
        delete: operations["push_unsubscribe_push_subscribe_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/notification-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Notification Settings */
        get: operations["get_notification_settings_user_notification_settings_get"];
        /** Put Notification Settings */
        put: operations["put_notification_settings_user_notification_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/notifications/due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Internal Due Notifications
         * @description Worker-facing: users to notify right now (claims them in-transaction).
         */
        get: operations["internal_due_notifications_internal_notifications_due_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/push/prune": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Internal Prune Push
         * @description Worker-facing: drop subscriptions that returned 404/410.
         */
        post: operations["internal_prune_push_internal_push_prune_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Leaderboard
         * @description Global leaderboard, ranked by total XP descending.
         */
        get: operations["get_leaderboard_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Session
         * @description Start a new session linked to authenticated user in database.
         */
        post: operations["start_session_session_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/start-zen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Zen Session
         * @description Start a Zen session: random exercises from selected belts, no SM-2 logic.
         */
        post: operations["start_zen_session_session_start_zen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Answer
         * @description Submit answer for exercise - validates ownership and saves to DB.
         */
        post: operations["submit_answer_session_answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/{session_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session Summary
         * @description Get session summary from database - validates ownership.
         */
        get: operations["session_summary_session__session_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerRequest */
        AnswerRequest: {
            /** Session Id */
            session_id: string;
            /** Exercise Id */
            exercise_id: string;
            /** Answer Index */
            answer_index: number;
            /** Attempts */
            attempts: number;
            /** Response Time S */
            response_time_s: number;
        };
        /** BeltEntry */
        BeltEntry: {
            /** Headline */
            headline: string;
            /** Description */
            description: string;
        };
        /** BeltProgressInfo */
        BeltProgressInfo: {
            /** Mastered */
            mastered: number;
            /** Total */
            total: number;
            /** Promoted */
            promoted: boolean;
        };
        /** DueNotification */
        DueNotification: {
            /** User Id */
            user_id: number;
            /** Pending Count */
            pending_count: number;
            /** Subscriptions */
            subscriptions: components["schemas"]["PushSubscriptionOut"][];
        };
        /** EnrollmentRequest */
        EnrollmentRequest: {
            /** University */
            university: string;
            /** Career */
            career: string;
            /** Name */
            name?: string | null;
        };
        /** EnrollmentResponse */
        EnrollmentResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** LeaderboardEntry */
        LeaderboardEntry: {
            /** Rank */
            rank: number;
            /** User Id */
            user_id: number;
            /** Name */
            name: string;
            /** Total Xp */
            total_xp: number;
            /** Is Current User */
            is_current_user: boolean;
        };
        /** LeaderboardResponse */
        LeaderboardResponse: {
            /** Entries */
            entries: components["schemas"]["LeaderboardEntry"][];
        };
        /** LevelInfo */
        LevelInfo: {
            /** Level */
            level: number;
            /** Xp In Level */
            xp_in_level: number;
            /** Xp Required */
            xp_required: number;
            /** Progress Pct */
            progress_pct: number;
        };
        /** LevelInfoWithMissing */
        LevelInfoWithMissing: {
            /** Level */
            level: number;
            /** Xp In Level */
            xp_in_level: number;
            /** Xp Required */
            xp_required: number;
            /** Xp Missing */
            xp_missing: number;
            /** Progress Pct */
            progress_pct: number;
        };
        /** NotificationSettings */
        NotificationSettings: {
            /** Enabled */
            enabled: boolean;
            /** Time */
            time?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** NotificationSettingsRequest */
        NotificationSettingsRequest: {
            /** Enabled */
            enabled: boolean;
            /** Time */
            time?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** PrunePushRequest */
        PrunePushRequest: {
            /** Subscription Ids */
            subscription_ids: number[];
        };
        /** PushKeys */
        PushKeys: {
            /** P256Dh */
            p256dh: string;
            /** Auth */
            auth: string;
        };
        /** PushSubscribeRequest */
        PushSubscribeRequest: {
            /** Endpoint */
            endpoint: string;
            keys: components["schemas"]["PushKeys"];
        };
        /** PushSubscriptionOut */
        PushSubscriptionOut: {
            /** Id */
            id: number;
            /** Endpoint */
            endpoint: string;
            /** P256Dh */
            p256dh: string;
            /** Auth */
            auth: string;
        };
        /** PushUnsubscribeRequest */
        PushUnsubscribeRequest: {
            /** Endpoint */
            endpoint: string;
        };
        /** SessionExercise */
        SessionExercise: {
            /** Id */
            id: string;
            /** Question */
            question: string;
            /** Options */
            options: string[];
            /** Correct Index */
            correct_index: number;
            /** Has Math */
            has_math: boolean;
            /** Topic */
            topic: string;
            /** Belt */
            belt: string;
            /** Graph Fn */
            graph_fn: string;
            /** Graph View */
            graph_view?: unknown[] | null;
            /** Feedback Correct */
            feedback_correct: string;
            /** Feedback Incorrect */
            feedback_incorrect: string;
            /** Explanation */
            explanation?: string | null;
        };
        /** SessionStartResponse */
        SessionStartResponse: {
            /** Session Id */
            session_id: string;
            /** User Name */
            user_name: string;
            /** Total */
            total: number;
            /** Exercises */
            exercises: components["schemas"]["SessionExercise"][];
        };
        /** SessionSummaryResponse */
        SessionSummaryResponse: {
            /** Session Id */
            session_id: string;
            /** User Name */
            user_name: string;
            /** Total */
            total: number;
            /** Correct */
            correct: number;
            /** Incorrect */
            incorrect: number;
            /** Items */
            items: components["schemas"]["SummaryItem"][];
            /** Topic States */
            topic_states: {
                [key: string]: components["schemas"]["TopicProgress"];
            };
            belt_progress: components["schemas"]["BeltProgressInfo"];
            /** Xp Earned */
            xp_earned: number;
            level_info: components["schemas"]["LevelInfoWithMissing"];
        };
        /** SimpleResponse */
        SimpleResponse: {
            /** Success */
            success: boolean;
        };
        /** StartSessionRequest */
        StartSessionRequest: {
            /** User Name */
            user_name: string;
        };
        /** StartZenSessionRequest */
        StartZenSessionRequest: {
            /** User Name */
            user_name: string;
            /** Belts */
            belts: string[];
            /** Count */
            count: number;
        };
        /** SummaryItem */
        SummaryItem: {
            /** Topic */
            topic: string;
            /** Belt */
            belt: string;
            /** Correct */
            correct: boolean;
        };
        /** TopicProgress */
        TopicProgress: {
            /** Phase */
            phase: string;
            /** Step Index */
            step_index: number;
            /** Status */
            status: string;
            /** Progress */
            progress: string;
            /** Is Pending */
            is_pending: boolean;
            /** Attempted */
            attempted: boolean;
            /** Next Review */
            next_review?: string | null;
            /** Failed */
            failed: boolean;
            /**
             * Units
             * @default []
             */
            units: components["schemas"]["UnitProgress"][];
        };
        /** UnitProgress */
        UnitProgress: {
            /** Exercise Type */
            exercise_type: string;
            /** State */
            state: string;
        };
        /** UserProgressResponse */
        UserProgressResponse: {
            /** Topic States */
            topic_states: {
                [key: string]: components["schemas"]["TopicProgress"];
            };
            level_info: components["schemas"]["LevelInfo"];
            /** Main Session Done Today */
            main_session_done_today: boolean;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Clerk User Id */
            clerk_user_id?: string | null;
        };
        /** UserStatusResponse */
        UserStatusResponse: {
            /** Enrolled */
            enrolled: boolean;
            /** Has Progress */
            has_progress: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_belt_info_course__course_id__belts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["BeltEntry"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_info_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enroll_user_user_enroll_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_status_user_status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_progress_user_progress_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProgressResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    push_subscribe_push_subscribe_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushSubscribeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    push_unsubscribe_push_subscribe_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushUnsubscribeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_notification_settings_user_notification_settings_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_notification_settings_user_notification_settings_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationSettingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    internal_due_notifications_internal_notifications_due_get: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: {
                "x-internal-secret"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DueNotification"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    internal_prune_push_internal_push_prune_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-secret"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrunePushRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leaderboard_leaderboard_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_session_session_start_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_zen_session_session_start_zen_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartZenSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_answer_session_answer_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_summary_session__session_id__summary_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
