/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/course/{course_id}/belts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Belt Info
         * @description Returns descriptive info (headline + description) for each belt in a course.
         *
         *     DEPRECATED: usar `GET /course/{course_id}/structure`, que devuelve la jerarquía
         *     completa (belts→units→topics→skills). Se mantiene por compatibilidad.
         */
        get: operations["get_belt_info_course__course_id__belts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/course/{course_id}/structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Course Structure
         * @description Estructura completa del curso desde course.json: la jerarquía
         *     curso → cinturón → unidades → temas → skills, más los exercise_types.
         *
         *     Fuente única de estructura (config-driven); el frontend genera su catálogo a
         *     partir de este mismo archivo.
         */
        get: operations["get_course_structure_course__course_id__structure_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Info
         * @description Get current authenticated user info.
         */
        get: operations["get_current_user_info_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Profile
         * @description Update the user's handle (username) and/or display name (apodo).
         */
        patch: operations["update_profile_user_profile_patch"];
        trace?: never;
    };
    "/user/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enroll User
         * @description Enroll user in a course with onboarding data.
         */
        post: operations["enroll_user_user_enroll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Status
         * @description Authoritative new-vs-returning check, read from the DB.
         *
         *     A returning user has an enrollment and/or learning state, regardless of
         *     what their Clerk `onboarded` metadata says. The frontend uses this to
         *     decide whether to run onboarding or send the user straight to the dashboard.
         */
        get: operations["get_user_status_user_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Progress
         * @description Get user's current progress (topic states and level info).
         *
         *     `tz` es la zona horaria IANA del navegador; si es válida, la persistimos en el
         *     usuario para que el "día" de la repetición espaciada use su zona, no la del
         *     servidor (UTC). El home llama a este endpoint en cada carga, así queda fresca.
         *
         *     `course` (opcional) es el slug del curso a filtrar. Si no viene, se usa el
         *     curso por defecto (id=1, "analisis").
         */
        get: operations["get_user_progress_user_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/practice-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Practice Stats
         * @description Stats del usuario para un curso en la iteración vigente, SOLO modo práctica
         *     (zen): sesiones de práctica completadas y ejercicios acertados en ellas.
         */
        get: operations["get_practice_stats_user_practice_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/course/{course}/topic/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Course Topic Advance
         * @description Adelantar un tema: lo desbloquea fuera de orden (o lo reactiva si estaba
         *     suspendido). Devuelve el progreso actualizado del curso.
         */
        post: operations["course_topic_advance_course__course__topic_advance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/course/{course}/topic/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Course Topic Suspend
         * @description Suspender un tema: lo oculta del home y cede su cupo a los temas siguientes.
         */
        post: operations["course_topic_suspend_course__course__topic_suspend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/course/{course}/topic/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Course Topic Reset
         * @description Reiniciar un tema: sus ítems vuelven a 'nuevo' y reingresan a repaso.
         */
        post: operations["course_topic_reset_course__course__topic_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/course/{course}/active-cap/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Course Active Cap Preview
         * @description Sin aplicar: qué temas se desbloquean/re-bloquean al fijar el cap en `value`.
         */
        get: operations["course_active_cap_preview_course__course__active_cap_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/course/{course}/active-cap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Course Set Active Cap
         * @description Fija cuántos ítems puede tener en aprendizaje a la vez (clamp 1..total).
         */
        put: operations["course_set_active_cap_course__course__active_cap_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/course/{course}/session-size": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Course Set Session Size
         * @description Fija el máximo de ejercicios por sesión de repaso (clamp 1..30).
         */
        put: operations["course_set_session_size_course__course__session_size_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/course/{course}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Course Reset
         * @description Reiniciar el curso: archiva el progreso vigente y arranca una iteración
         *     nueva (el cinturón refleja solo la iteración vigente).
         */
        post: operations["course_reset_course__course__reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push Subscribe
         * @description Store a browser PushSubscription for the current user.
         */
        post: operations["push_subscribe_push_subscribe_post"];
        /**
         * Push Unsubscribe
         * @description Remove a browser PushSubscription (called when the user unsubscribes).
         */
        delete: operations["push_unsubscribe_push_subscribe_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/notification-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Notification Settings */
        get: operations["get_notification_settings_user_notification_settings_get"];
        /** Put Notification Settings */
        put: operations["put_notification_settings_user_notification_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/notifications/due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Internal Due Notifications
         * @description Worker-facing: users to notify right now (claims them in-transaction).
         */
        get: operations["internal_due_notifications_internal_notifications_due_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/push/prune": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Internal Prune Push
         * @description Worker-facing: drop subscriptions that returned 404/410.
         */
        post: operations["internal_prune_push_internal_push_prune_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Leaderboard
         * @description Leaderboard ranked by total XP descending, paginado (offset/limit).
         *
         *     El ranking, los totales y los datos del usuario actual se calculan sobre el
         *     set completo del scope (global o filtrado por universidad); solo `entries`
         *     devuelve la página pedida para el scroll infinito.
         *
         *     Con `around_me=true` se ignoran `offset`/`limit` y se devuelve una ventana
         *     centrada en el usuario actual (`AROUND_WINDOW` filas a cada lado), para que
         *     el front cargue el ranking con el usuario en el medio y scrollee hacia ambos
         *     lados. Cada entry trae su `rank` absoluto, así el front conoce los bordes de
         *     la ventana y pide más arriba/abajo por offset.
         */
        get: operations["get_leaderboard_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard/universities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get University Leaderboard
         * @description Ranking de universidades: agrega estudiantes por universidad y carrera.
         *
         *     A diferencia del leaderboard individual (paginado, ventana alrededor del
         *     usuario), acá se recorre el set completo una vez y se agregan los totales
         *     por universidad, así el front puede comparar universidades entre sí.
         *
         *     `career` (bucket E/S/T/M/Otra): agrega contando solo estudiantes de esa
         *     carrera. `university`: limita a esa universidad (aislarla).
         */
        get: operations["get_university_leaderboard_leaderboard_universities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Leaderboard Summary
         * @description Números generales (globales) de la cabecera del leaderboard: estudiantes
         *     registrados, ejercicios acumulados y universidades presentes. No dependen de
         *     ningún filtro de carrera/universidad.
         */
        get: operations["get_leaderboard_summary_leaderboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/emoji-tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Emoji State
         * @description Estado del árbol de desbloqueo del usuario (bucket, XP, camino, vestido).
         */
        get: operations["get_emoji_state_user_emoji_tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/emoji/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unlock Emoji
         * @description Desbloquea el siguiente nodo del camino (irreversible, sin reset).
         */
        post: operations["unlock_emoji_user_emoji_unlock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/emoji/worn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Worn Emoji
         * @description Viste un emoji ya desbloqueado del camino. None = raíz del bucket (default).
         */
        put: operations["set_worn_emoji_user_emoji_worn_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Session
         * @description Start a new session linked to authenticated user in database.
         */
        post: operations["start_session_session_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/start-zen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Zen Session
         * @description Start a Zen session: random exercises from selected topics of one unit, no SM-2 logic.
         */
        post: operations["start_zen_session_session_start_zen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/start-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Test Session
         * @description Start a QA/test session: ALL exercises in each selected item, no SR logic.
         */
        post: operations["start_test_session_session_start_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Answer
         * @description Submit answer for exercise - validates ownership and saves to DB.
         */
        post: operations["submit_answer_session_answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/{session_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session Summary
         * @description Get session summary from database - validates ownership.
         */
        get: operations["session_summary_session__session_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Feedback
         * @description Save user feedback and notify via email. user_id comes from the token.
         *
         *     The email is best-effort — if Resend fails we still return success so the
         *     user isn't blocked by a provider outage.
         */
        post: operations["submit_feedback_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveCapRequest */
        ActiveCapRequest: {
            /** Value */
            value: number;
        };
        /** AnswerRequest */
        AnswerRequest: {
            /** Session Id */
            session_id: string;
            /** Exercise Id */
            exercise_id: string;
            /** Answer Index */
            answer_index: number;
            /** Attempts */
            attempts: number;
            /** Response Time S */
            response_time_s: number;
        };
        /** BeltEntry */
        BeltEntry: {
            /** Headline */
            headline: string;
            /** Description */
            description: string;
        };
        /** BeltProgressInfo */
        BeltProgressInfo: {
            /** Mastered */
            mastered: number;
            /** Total */
            total: number;
            /** Promoted */
            promoted: boolean;
        };
        /** CapPreviewResponse */
        CapPreviewResponse: {
            /** Value */
            value: number;
            /**
             * Unlock
             * @default []
             */
            unlock: string[];
            /**
             * Lock
             * @default []
             */
            lock: string[];
        };
        /** CourseResetResponse */
        CourseResetResponse: {
            /** Iteration */
            iteration: number;
        };
        /** DueNotification */
        DueNotification: {
            /** User Id */
            user_id: number;
            /** Pending Count */
            pending_count: number;
            /** Subscriptions */
            subscriptions: components["schemas"]["PushSubscriptionOut"][];
        };
        /** EmojiStateResponse */
        EmojiStateResponse: {
            /** Bucket */
            bucket?: string | null;
            /**
             * Total Xp
             * @default 0
             */
            total_xp: number;
            /**
             * Path
             * @default []
             */
            path: string[];
            /** Worn */
            worn?: string | null;
        };
        /** EmojiUnlockRequest */
        EmojiUnlockRequest: {
            /** Node Id */
            node_id: string;
        };
        /** EmojiWornRequest */
        EmojiWornRequest: {
            /** Node Id */
            node_id?: string | null;
        };
        /** EnrollmentRequest */
        EnrollmentRequest: {
            /** University */
            university: string;
            /** Career */
            career: string;
            /** Name */
            name?: string | null;
            /** Intro Item Correct */
            intro_item_correct?: boolean | null;
        };
        /** EnrollmentResponse */
        EnrollmentResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /**
             * Categoria
             * @enum {string}
             */
            categoria: "error" | "idea" | "comentario";
            /** Mensaje */
            mensaje: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** LeaderboardEntry */
        LeaderboardEntry: {
            /** Rank */
            rank: number;
            /** User Id */
            user_id: number;
            /** Name */
            name: string;
            /** Username */
            username?: string | null;
            /** Total Xp */
            total_xp: number;
            /** Exercises */
            exercises: number;
            /** Is Current User */
            is_current_user: boolean;
            /** Career */
            career?: string | null;
            /** University */
            university?: string | null;
            /** Emoji */
            emoji?: string | null;
            /**
             * Belt
             * @default white
             */
            belt: string;
        };
        /** LeaderboardMe */
        LeaderboardMe: {
            /** Rank */
            rank?: number | null;
            /** Xp To Next */
            xp_to_next?: number | null;
            /**
             * Total Xp
             * @default 0
             */
            total_xp: number;
        };
        /** LeaderboardResponse */
        LeaderboardResponse: {
            /** Entries */
            entries: components["schemas"]["LeaderboardEntry"][];
            /** Total Xp */
            total_xp: number;
            /** Total Exercises */
            total_exercises: number;
            /** Total Count */
            total_count: number;
            /** Has More */
            has_more: boolean;
            me: components["schemas"]["LeaderboardMe"];
            /** Universities */
            universities: string[];
        };
        /** LeaderboardSummaryResponse */
        LeaderboardSummaryResponse: {
            /** Total Students */
            total_students: number;
            /** Total Exercises */
            total_exercises: number;
            /** Universities */
            universities: string[];
        };
        /** LevelInfo */
        LevelInfo: {
            /** Level */
            level: number;
            /** Xp In Level */
            xp_in_level: number;
            /** Xp Required */
            xp_required: number;
            /** Progress Pct */
            progress_pct: number;
        };
        /** LevelInfoWithMissing */
        LevelInfoWithMissing: {
            /** Level */
            level: number;
            /** Xp In Level */
            xp_in_level: number;
            /** Xp Required */
            xp_required: number;
            /** Xp Missing */
            xp_missing: number;
            /** Progress Pct */
            progress_pct: number;
        };
        /** NotificationSettings */
        NotificationSettings: {
            /** Enabled */
            enabled: boolean;
            /** Time */
            time?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** NotificationSettingsRequest */
        NotificationSettingsRequest: {
            /** Enabled */
            enabled: boolean;
            /** Time */
            time?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** PracticeStatsResponse */
        PracticeStatsResponse: {
            /** Sessions Completed */
            sessions_completed: number;
            /** Exercises Answered */
            exercises_answered: number;
            /** Exercises Correct */
            exercises_correct: number;
        };
        /** PrunePushRequest */
        PrunePushRequest: {
            /** Subscription Ids */
            subscription_ids: number[];
        };
        /** PushKeys */
        PushKeys: {
            /** P256Dh */
            p256dh: string;
            /** Auth */
            auth: string;
        };
        /** PushSubscribeRequest */
        PushSubscribeRequest: {
            /** Endpoint */
            endpoint: string;
            keys: components["schemas"]["PushKeys"];
        };
        /** PushSubscriptionOut */
        PushSubscriptionOut: {
            /** Id */
            id: number;
            /** Endpoint */
            endpoint: string;
            /** P256Dh */
            p256dh: string;
            /** Auth */
            auth: string;
        };
        /** PushUnsubscribeRequest */
        PushUnsubscribeRequest: {
            /** Endpoint */
            endpoint: string;
        };
        /** SessionExercise */
        SessionExercise: {
            /** Id */
            id: string;
            /**
             * External Id
             * @default
             */
            external_id: string;
            /**
             * Exercise Type
             * @default
             */
            exercise_type: string;
            /** Question */
            question: string;
            /** Options */
            options: string[];
            /** Correct Index */
            correct_index: number;
            /** Has Math */
            has_math: boolean;
            /** Topic */
            topic: string;
            /** Belt */
            belt: string;
            /** Graph Fn */
            graph_fn: string;
            /** Graph View */
            graph_view?: unknown[] | null;
            /** Feedback Correct */
            feedback_correct: string;
            /** Feedback Incorrect */
            feedback_incorrect: string | (string | null)[];
            /** Explanation */
            explanation?: string | null;
        };
        /** SessionStartResponse */
        SessionStartResponse: {
            /** Session Id */
            session_id: string;
            /** User Name */
            user_name: string;
            /** Total */
            total: number;
            /**
             * Mode
             * @default main
             */
            mode: string;
            /** Exercises */
            exercises: components["schemas"]["SessionExercise"][];
        };
        /** SessionSummaryResponse */
        SessionSummaryResponse: {
            /** Session Id */
            session_id: string;
            /** User Name */
            user_name: string;
            /** Total */
            total: number;
            /** Correct */
            correct: number;
            /** First Try Correct */
            first_try_correct: number;
            /** Incorrect */
            incorrect: number;
            /** Items */
            items: components["schemas"]["SummaryItem"][];
            /** Topic States */
            topic_states: {
                [key: string]: components["schemas"]["TopicProgress"];
            };
            belt_progress: components["schemas"]["BeltProgressInfo"];
            /** Xp Earned */
            xp_earned: number;
            level_info: components["schemas"]["LevelInfoWithMissing"];
        };
        /** SimpleResponse */
        SimpleResponse: {
            /** Success */
            success: boolean;
        };
        /** SkillProgress */
        SkillProgress: {
            /** Exercise Type */
            exercise_type: string;
            /** State */
            state: string;
            /** Next Review */
            next_review?: string | null;
        };
        /** StartSessionRequest */
        StartSessionRequest: {
            /** User Name */
            user_name: string;
            /** Course */
            course?: string | null;
        };
        /** StartTestSessionRequest */
        StartTestSessionRequest: {
            /** Items */
            items: components["schemas"]["TestSessionItem"][];
            /** Course */
            course?: string | null;
            /**
             * Shuffle
             * @default true
             */
            shuffle: boolean;
            filters?: components["schemas"]["TestFilters"] | null;
        };
        /** StartZenSessionRequest */
        StartZenSessionRequest: {
            /** User Name */
            user_name: string;
            /** Belt */
            belt: string;
            /** Topics */
            topics: string[];
            /** Count */
            count: number;
            /** Course */
            course?: string | null;
        };
        /** SummaryItem */
        SummaryItem: {
            /** Topic */
            topic: string;
            /** Belt */
            belt: string;
            /** Correct */
            correct: boolean;
        };
        /** TestFilters */
        TestFilters: {
            /**
             * Has Math
             * @default false
             */
            has_math: boolean;
            /**
             * Has Graph
             * @default false
             */
            has_graph: boolean;
        };
        /** TestSessionItem */
        TestSessionItem: {
            /** Belt */
            belt: string;
            /** Topic */
            topic: string;
            /** Exercise Type */
            exercise_type: string;
        };
        /** TopicActionRequest */
        TopicActionRequest: {
            /** Belt */
            belt: string;
            /** Topic */
            topic: string;
        };
        /** TopicProgress */
        TopicProgress: {
            /** Phase */
            phase: string;
            /** Step Index */
            step_index: number;
            /** Status */
            status: string;
            /** Progress */
            progress: string;
            /** Is Pending */
            is_pending: boolean;
            /** Attempted */
            attempted: boolean;
            /** Next Review */
            next_review?: string | null;
            /** Failed */
            failed: boolean;
            /**
             * Suspended
             * @default false
             */
            suspended: boolean;
            /**
             * Skills
             * @default []
             */
            skills: components["schemas"]["SkillProgress"][];
        };
        /** UniversityLeaderboardResponse */
        UniversityLeaderboardResponse: {
            /** Rows */
            rows: components["schemas"]["UniversityRankRow"][];
            /** Total Students */
            total_students: number;
            /** Total Universities */
            total_universities: number;
            /** Career Totals */
            career_totals: {
                [key: string]: number;
            };
        };
        /** UniversityRankRow */
        UniversityRankRow: {
            /** University */
            university: string;
            /** Total Xp */
            total_xp: number;
            /** Students */
            students: number;
            /** Careers */
            careers: {
                [key: string]: number;
            };
        };
        /** UpdateProfileRequest */
        UpdateProfileRequest: {
            /** Username */
            username?: string | null;
            /** Display Name */
            display_name?: string | null;
        };
        /** UserProgressResponse */
        UserProgressResponse: {
            /** Topic States */
            topic_states: {
                [key: string]: components["schemas"]["TopicProgress"];
            };
            level_info: components["schemas"]["LevelInfo"];
            /** Main Session Done Today */
            main_session_done_today: boolean;
            /** Last Course */
            last_course?: string | null;
            /**
             * Active Cap
             * @default 18
             */
            active_cap: number;
            /**
             * Total Items
             * @default 0
             */
            total_items: number;
            /**
             * Iteration
             * @default 1
             */
            iteration: number;
            /**
             * Session Size
             * @default 8
             */
            session_size: number;
            /**
             * Session Size Max
             * @default 30
             */
            session_size_max: number;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Username */
            username?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Clerk User Id */
            clerk_user_id?: string | null;
        };
        /** UserStatusResponse */
        UserStatusResponse: {
            /** Enrolled */
            enrolled: boolean;
            /** Has Progress */
            has_progress: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_belt_info_course__course_id__belts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["BeltEntry"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_structure_course__course_id__structure_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_info_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_user_profile_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enroll_user_user_enroll_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_status_user_status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_progress_user_progress_get: {
        parameters: {
            query?: {
                tz?: string | null;
                course?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProgressResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_practice_stats_user_practice_stats_get: {
        parameters: {
            query?: {
                course?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    course_topic_advance_course__course__topic_advance_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                course: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProgressResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    course_topic_suspend_course__course__topic_suspend_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                course: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProgressResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    course_topic_reset_course__course__topic_reset_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                course: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProgressResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    course_active_cap_preview_course__course__active_cap_preview_get: {
        parameters: {
            query: {
                value: number;
            };
            header?: {
                authorization?: string;
            };
            path: {
                course: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    course_set_active_cap_course__course__active_cap_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                course: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActiveCapRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProgressResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    course_set_session_size_course__course__session_size_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                course: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActiveCapRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProgressResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    course_reset_course__course__reset_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                course: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseResetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    push_subscribe_push_subscribe_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushSubscribeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    push_unsubscribe_push_subscribe_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushUnsubscribeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_notification_settings_user_notification_settings_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_notification_settings_user_notification_settings_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationSettingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    internal_due_notifications_internal_notifications_due_get: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: {
                "x-internal-secret"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DueNotification"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    internal_prune_push_internal_push_prune_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-secret"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrunePushRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leaderboard_leaderboard_get: {
        parameters: {
            query?: {
                university?: string | null;
                career?: string | null;
                limit?: number;
                offset?: number;
                around_me?: boolean;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_university_leaderboard_leaderboard_universities_get: {
        parameters: {
            query?: {
                career?: string | null;
                university?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniversityLeaderboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leaderboard_summary_leaderboard_summary_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_emoji_state_user_emoji_tree_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmojiStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unlock_emoji_user_emoji_unlock_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmojiUnlockRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmojiStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_worn_emoji_user_emoji_worn_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmojiWornRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmojiStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_session_session_start_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_zen_session_session_start_zen_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartZenSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_test_session_session_start_test_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartTestSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_answer_session_answer_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_summary_session__session_id__summary_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_feedback_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
