/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/course/{course_id}/belts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Belt Info
         * @description Returns descriptive info (headline + description) for each belt in a course.
         */
        get: operations["get_belt_info_course__course_id__belts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Info
         * @description Get current authenticated user info.
         */
        get: operations["get_current_user_info_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enroll User
         * @description Enroll user in a course with onboarding data.
         */
        post: operations["enroll_user_user_enroll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Progress
         * @description Get user's current progress (skill states and level info).
         */
        get: operations["get_user_progress_user_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Session
         * @description Start a new session linked to authenticated user in database.
         */
        post: operations["start_session_session_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/start-zen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Zen Session
         * @description Start a Zen session: random exercises from selected belts, no SM-2 logic.
         */
        post: operations["start_zen_session_session_start_zen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Answer
         * @description Submit answer for exercise - validates ownership and saves to DB.
         */
        post: operations["submit_answer_session_answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/{session_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session Summary
         * @description Get session summary from database - validates ownership.
         */
        get: operations["session_summary_session__session_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerRequest */
        AnswerRequest: {
            /** Session Id */
            session_id: string;
            /** Exercise Id */
            exercise_id: string;
            /** Answer Index */
            answer_index: number;
            /** Response Time S */
            response_time_s: number;
        };
        /** BeltEntry */
        BeltEntry: {
            /** Headline */
            headline: string;
            /** Description */
            description: string;
        };
        /** BeltProgressInfo */
        BeltProgressInfo: {
            /** Graduated */
            graduated: number;
            /** Total */
            total: number;
            /** Stripes */
            stripes: number;
            /** Promoted */
            promoted: boolean;
        };
        /** EnrollmentRequest */
        EnrollmentRequest: {
            /** University */
            university: string;
            /** Career */
            career: string;
            /** Name */
            name?: string | null;
        };
        /** EnrollmentResponse */
        EnrollmentResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /**
         * LevelInfo
         * @description Level info as returned by /user/progress.
         */
        LevelInfo: {
            /** Level */
            level: number;
            /** Xp In Level */
            xp_in_level: number;
            /** Xp Required */
            xp_required: number;
            /** Progress Pct */
            progress_pct: number;
        };
        /**
         * LevelInfoWithMissing
         * @description Level info as returned by /session/{id}/summary (adds xp_missing).
         */
        LevelInfoWithMissing: {
            /** Level */
            level: number;
            /** Xp In Level */
            xp_in_level: number;
            /** Xp Required */
            xp_required: number;
            /** Xp Missing */
            xp_missing: number;
            /** Progress Pct */
            progress_pct: number;
        };
        /** SessionExercise */
        SessionExercise: {
            /** Id */
            id: string;
            /** Question */
            question: string;
            /** Options */
            options: string[];
            /** Correct Index */
            correct_index: number;
            /** Has Math */
            has_math: boolean;
            /** Skill */
            skill: string;
            /** Topic */
            topic: string;
            /** Graph Fn */
            graph_fn: string;
            /** Graph View */
            graph_view?: unknown[] | null;
            /** Feedback Correct */
            feedback_correct: string;
            /** Feedback Incorrect */
            feedback_incorrect: string;
            /** Explanation */
            explanation?: string | null;
        };
        /** SessionStartResponse */
        SessionStartResponse: {
            /** Session Id */
            session_id: string;
            /** User Name */
            user_name: string;
            /** Total */
            total: number;
            /** Exercises */
            exercises: components["schemas"]["SessionExercise"][];
        };
        /** SessionSummaryResponse */
        SessionSummaryResponse: {
            /** Session Id */
            session_id: string;
            /** User Name */
            user_name: string;
            /** Total */
            total: number;
            /** Correct */
            correct: number;
            /** Incorrect */
            incorrect: number;
            /** Items */
            items: components["schemas"]["SummaryItem"][];
            /** Skill States */
            skill_states: {
                [key: string]: components["schemas"]["SkillState"];
            };
            belt_progress: components["schemas"]["BeltProgressInfo"];
            /** Xp Earned */
            xp_earned: number;
            level_info: components["schemas"]["LevelInfoWithMissing"];
        };
        /** SkillState */
        SkillState: {
            /** Phase */
            phase: string;
            /** Step Index */
            step_index: number;
            /** Status */
            status: string;
            /** Progress */
            progress: string;
            /** Is Pending */
            is_pending: boolean;
            /** Attempted */
            attempted: boolean;
            /** Next Review */
            next_review?: string | null;
            /** Failed */
            failed: boolean;
        };
        /** StartSessionRequest */
        StartSessionRequest: {
            /** User Name */
            user_name: string;
        };
        /** StartZenSessionRequest */
        StartZenSessionRequest: {
            /** User Name */
            user_name: string;
            /** Belts */
            belts: string[];
            /** Count */
            count: number;
        };
        /** SummaryItem */
        SummaryItem: {
            /** Topic */
            topic: string;
            /** Skill */
            skill: string;
            /** Correct */
            correct: boolean;
            /** Phase */
            phase: string;
        };
        /** UserProgressResponse */
        UserProgressResponse: {
            /** Skill States */
            skill_states: {
                [key: string]: components["schemas"]["SkillState"];
            };
            level_info: components["schemas"]["LevelInfo"];
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Clerk User Id */
            clerk_user_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_belt_info_course__course_id__belts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["BeltEntry"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_info_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enroll_user_user_enroll_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_progress_user_progress_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProgressResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_session_session_start_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_zen_session_session_start_zen_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartZenSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_answer_session_answer_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_summary_session__session_id__summary_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
