"""
fix_exercises.py — Reemplaza todos los ejercicios en la BD con strings Unicode correctos.
Corrige el problema de \\u00bf etc. que quedaron como texto literal.
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))

from database import SessionLocal
from models import Exercise

EXERCISES_DATA = [
    # ── LINEAR / LEXI ────────────────────────────────────────────────
    {
        "course_id": 1, "belt": "white", "topic": "linear", "skill": "LEXI",
        "subtype": "text",
        "question": "¿Cuál de estas expresiones representa una función lineal?",
        "option_a": "$f(x) = 5x - 2$", "option_b": "$f(x) = x^2$",
        "option_c": "$f(x) = 3^x$", "option_d": "$f(x) = \\log(x)$",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! Una función lineal tiene la forma $f(x) = mx + b$, donde $m$ y $b$ son constantes.",
        "feedback_incorrect": "Una función lineal tiene la forma $f(x) = mx + b$. La opción correcta es $f(x) = 5x - 2$.",
        "graph_fn": None, "graph_view": None,
    },
    {
        "course_id": 1, "belt": "white", "topic": "linear", "skill": "LEXI",
        "subtype": "graph",
        "question": "¿Cómo se llama el punto donde la recta corta el eje Y?",
        "option_a": "Ordenada al origen", "option_b": "Pendiente",
        "option_c": "Raíz", "option_d": "Vértice",
        "correct_index": 0, "has_math": False,
        "feedback_correct": "¡Correcto! El valor de $f(0)$ se llama ordenada al origen (o intercepto en Y).",
        "feedback_incorrect": "El punto donde la recta corta el eje Y se llama ordenada al origen ($f(0) = b$ en $f(x) = mx + b$).",
        "graph_fn": "3*x + 2", "graph_view": "[-4, 4, -8, 10]",
    },
    # ── LINEAR / CLSF ────────────────────────────────────────────────
    {
        "course_id": 1, "belt": "white", "topic": "linear", "skill": "CLSF",
        "subtype": "graph",
        "question": "¿A qué familia de funciones pertenece esta gráfica?",
        "option_a": "Lineal", "option_b": "Cuadrática",
        "option_c": "Exponencial", "option_d": "Logarítmica",
        "correct_index": 0, "has_math": False,
        "feedback_correct": "¡Correcto! La gráfica es una línea recta: $f(x) = 2x - 5$, una función lineal.",
        "feedback_incorrect": "La gráfica es una línea recta ($f(x) = 2x - 5$), característica de una función lineal.",
        "graph_fn": "2*x - 5", "graph_view": "[-4, 6, -10, 10]",
    },
    {
        "course_id": 1, "belt": "white", "topic": "linear", "skill": "CLSF",
        "subtype": "text",
        "question": "¿A qué familia de funciones pertenece $f(x) = 2x - 5$?",
        "option_a": "Lineal", "option_b": "Cuadrática",
        "option_c": "Exponencial", "option_d": "Logarítmica",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! $f(x) = 2x - 5$ tiene la forma $f(x) = mx + b$: es una función lineal.",
        "feedback_incorrect": "$f(x) = 2x - 5$ tiene la forma $f(x) = mx + b$, que define una función lineal.",
        "graph_fn": None, "graph_view": None,
    },
    # ── LINEAR / FORM ────────────────────────────────────────────────
    {
        "course_id": 1, "belt": "white", "topic": "linear", "skill": "FORM",
        "subtype": "text",
        "question": "En $f(x) = -3x + 8$, ¿cuál es la ordenada al origen?",
        "option_a": "$8$", "option_b": "$-3$",
        "option_c": "$-3x$", "option_d": "$x$",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! En $f(x) = mx + b$, la ordenada al origen es $b = 8$.",
        "feedback_incorrect": "En $f(x) = mx + b$, $b$ es la ordenada al origen. Aquí $b = 8$.",
        "graph_fn": None, "graph_view": None,
    },
    {
        "course_id": 1, "belt": "white", "topic": "linear", "skill": "FORM",
        "subtype": "graph",
        "question": "¿Cuál de estas expresiones corresponde a la recta del gráfico?",
        "option_a": "$y = 2x - 3$", "option_b": "$y = -2x + 3$",
        "option_c": "$y = 3x - 2$", "option_d": "$y = 2x + 3$",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! La recta tiene pendiente 2 e intercepto −3: $y = 2x - 3$.",
        "feedback_incorrect": "La recta sube 2 unidades por cada unidad en x y corta el eje Y en −3: $y = 2x - 3$.",
        "graph_fn": "2*x - 3", "graph_view": "[-3, 5, -8, 8]",
    },
    # ── QUADRATIC / LEXI ─────────────────────────────────────────────
    {
        "course_id": 1, "belt": "white", "topic": "quadratic", "skill": "LEXI",
        "subtype": "text",
        "question": "¿Cuál de estas expresiones representa una función cuadrática?",
        "option_a": "$f(x) = 2x^2 - x + 1$", "option_b": "$f(x) = 4x - 7$",
        "option_c": "$f(x) = 2^x$", "option_d": "$f(x) = \\sqrt{x}$",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! Una función cuadrática tiene la forma $f(x) = ax^2 + bx + c$ con $a \\neq 0$.",
        "feedback_incorrect": "Una función cuadrática incluye un término de segundo grado ($x^2$). La correcta es $f(x) = 2x^2 - x + 1$.",
        "graph_fn": None, "graph_view": None,
    },
    {
        "course_id": 1, "belt": "white", "topic": "quadratic", "skill": "LEXI",
        "subtype": "graph",
        "question": "¿Cómo se llama el punto más bajo (o más alto) de esta parábola?",
        "option_a": "Vértice", "option_b": "Raíz",
        "option_c": "Ordenada al origen", "option_d": "Asíntota",
        "correct_index": 0, "has_math": False,
        "feedback_correct": "¡Correcto! El punto extremo de una parábola se llama vértice.",
        "feedback_incorrect": "El punto más bajo (mínimo) o más alto (máximo) de una parábola se llama vértice.",
        "graph_fn": "x*x - 4*x + 3", "graph_view": "[-1, 5, -2, 8]",
    },
    # ── QUADRATIC / CLSF ─────────────────────────────────────────────
    {
        "course_id": 1, "belt": "white", "topic": "quadratic", "skill": "CLSF",
        "subtype": "graph",
        "question": "¿A qué familia de funciones pertenece esta gráfica?",
        "option_a": "Cuadrática", "option_b": "Lineal",
        "option_c": "Exponencial", "option_d": "Racional",
        "correct_index": 0, "has_math": False,
        "feedback_correct": "¡Correcto! La gráfica es una parábola: $f(x) = x^2 - 4x + 3$, una función cuadrática.",
        "feedback_incorrect": "La gráfica es una parábola ($f(x) = x^2 - 4x + 3$), característica de una función cuadrática.",
        "graph_fn": "x*x - 4*x + 3", "graph_view": "[-1, 5, -2, 8]",
    },
    {
        "course_id": 1, "belt": "white", "topic": "quadratic", "skill": "CLSF",
        "subtype": "text",
        "question": "¿A qué familia de funciones pertenece $f(x) = x^2 - 4x + 3$?",
        "option_a": "Cuadrática", "option_b": "Lineal",
        "option_c": "Exponencial", "option_d": "Racional",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! $f(x) = x^2 - 4x + 3$ tiene la forma $ax^2 + bx + c$: es una función cuadrática.",
        "feedback_incorrect": "$f(x) = x^2 - 4x + 3$ tiene un término $x^2$ como mayor potencia: es una función cuadrática.",
        "graph_fn": None, "graph_view": None,
    },
    # ── QUADRATIC / FORM ─────────────────────────────────────────────
    {
        "course_id": 1, "belt": "white", "topic": "quadratic", "skill": "FORM",
        "subtype": "text",
        "question": "En $f(x) = 3x^2 - 6x + 2$, ¿cuál es el coeficiente del término cuadrático?",
        "option_a": "$3$", "option_b": "$-6$",
        "option_c": "$2$", "option_d": "$-3$",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! En $f(x) = ax^2 + bx + c$, el coeficiente cuadrático es $a = 3$.",
        "feedback_incorrect": "En $f(x) = ax^2 + bx + c$, $a$ es el coeficiente cuadrático. Aquí $a = 3$.",
        "graph_fn": None, "graph_view": None,
    },
    {
        "course_id": 1, "belt": "white", "topic": "quadratic", "skill": "FORM",
        "subtype": "graph",
        "question": "¿Cuál de estas expresiones corresponde a la parábola del gráfico?",
        "option_a": "$f(x) = (x-2)^2 - 1$", "option_b": "$f(x) = (x+2)^2 - 1$",
        "option_c": "$f(x) = -(x-2)^2 - 1$", "option_d": "$f(x) = (x-2)^2 + 1$",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! El vértice está en (2, −1) y la parábola se abre hacia arriba: $f(x) = (x-2)^2 - 1$.",
        "feedback_incorrect": "La parábola tiene vértice en (2, −1) y se abre hacia arriba: $f(x) = (x-2)^2 - 1$.",
        "graph_fn": "pow(x-2, 2) - 1", "graph_view": "[-1, 5, -2, 8]",
    },
    # ── POLYNOMIAL / LEXI ────────────────────────────────────────────
    {
        "course_id": 1, "belt": "white", "topic": "polynomial", "skill": "LEXI",
        "subtype": "text",
        "question": "¿Cuál de estas funciones es un polinomio de grado 3?",
        "option_a": "$f(x) = x^3 - 2x + 5$", "option_b": "$f(x) = x^2 + 1$",
        "option_c": "$f(x) = 4x - 1$", "option_d": "$f(x) = x^4$",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! Un polinomio de grado 3 tiene como término de mayor grado $x^3$.",
        "feedback_incorrect": "Un polinomio de grado 3 tiene $x^3$ como potencia máxima. La correcta es $f(x) = x^3 - 2x + 5$.",
        "graph_fn": None, "graph_view": None,
    },
    {
        "course_id": 1, "belt": "white", "topic": "polynomial", "skill": "LEXI",
        "subtype": "graph",
        "question": "¿Cuántas raíces reales puede tener como máximo esta función polinómica?",
        "option_a": "3", "option_b": "2",
        "option_c": "1", "option_d": "Infinitas",
        "correct_index": 0, "has_math": False,
        "feedback_correct": "¡Correcto! Un polinomio de grado 3 puede tener hasta 3 raíces reales.",
        "feedback_incorrect": "El número máximo de raíces reales de un polinomio es igual a su grado. Aquí el grado es 3.",
        "graph_fn": "pow(x, 3) - 3*x", "graph_view": "[-3, 3, -5, 5]",
    },
    # ── POLYNOMIAL / CLSF ────────────────────────────────────────────
    {
        "course_id": 1, "belt": "white", "topic": "polynomial", "skill": "CLSF",
        "subtype": "graph",
        "question": "¿A qué familia de funciones pertenece esta gráfica?",
        "option_a": "Polinómica", "option_b": "Cuadrática",
        "option_c": "Lineal", "option_d": "Exponencial",
        "correct_index": 0, "has_math": False,
        "feedback_correct": "¡Correcto! La curva es un polinomio de grado 3: $f(x) = x^3 - 2x^2 + x - 1$.",
        "feedback_incorrect": "La curva con dos cambios de dirección es $f(x) = x^3 - 2x^2 + x - 1$, un polinomio de grado 3.",
        "graph_fn": "pow(x, 3) - 2*pow(x, 2) + x - 1", "graph_view": "[-2, 3, -5, 4]",
    },
    {
        "course_id": 1, "belt": "white", "topic": "polynomial", "skill": "CLSF",
        "subtype": "text",
        "question": "¿A qué familia de funciones pertenece $f(x) = x^3 - 2x^2 + x - 1$?",
        "option_a": "Polinómica", "option_b": "Cuadrática",
        "option_c": "Lineal", "option_d": "Exponencial",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! $f(x) = x^3 - 2x^2 + x - 1$ es un polinomio de grado 3.",
        "feedback_incorrect": "$f(x) = x^3 - 2x^2 + x - 1$ tiene $x^3$ como término de mayor grado: es un polinomio de grado 3.",
        "graph_fn": None, "graph_view": None,
    },
    # ── POLYNOMIAL / FORM ────────────────────────────────────────────
    {
        "course_id": 1, "belt": "white", "topic": "polynomial", "skill": "FORM",
        "subtype": "text",
        "question": "¿Cuál es el grado de $p(x) = 4x^5 - 3x^3 + x - 7$?",
        "option_a": "$5$", "option_b": "$3$",
        "option_c": "$1$", "option_d": "$4$",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! El grado es la potencia más alta. En $4x^5 - 3x^3 + x - 7$, el grado es $5$.",
        "feedback_incorrect": "El grado es la potencia más alta de $x$. En $4x^5 - 3x^3 + x - 7$, el grado es $5$.",
        "graph_fn": None, "graph_view": None,
    },
    {
        "course_id": 1, "belt": "white", "topic": "polynomial", "skill": "FORM",
        "subtype": "graph",
        "question": "¿Cuál de estas expresiones corresponde a la curva del gráfico?",
        "option_a": "$f(x) = x^3 - 3x$", "option_b": "$f(x) = x^3 + 3x$",
        "option_c": "$f(x) = -x^3 + 3x$", "option_d": "$f(x) = x^2 - 3$",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! La curva tiene raíces en $-\\sqrt{3}$, $0$ y $\\sqrt{3}$, consistente con $f(x) = x^3 - 3x$.",
        "feedback_incorrect": "La curva cruza el eje X en $-\\sqrt{3}$, $0$ y $\\sqrt{3}$ con pendiente positiva en el origen: $f(x) = x^3 - 3x$.",
        "graph_fn": "pow(x, 3) - 3*x", "graph_view": "[-3, 3, -5, 5]",
    },
    # ── EXPONENTIAL / LEXI ───────────────────────────────────────────
    {
        "course_id": 1, "belt": "white", "topic": "exponential", "skill": "LEXI",
        "subtype": "text",
        "question": "¿Cuál de estas expresiones representa una función exponencial?",
        "option_a": "$f(x) = 5 \\cdot 2^x$", "option_b": "$f(x) = x^5$",
        "option_c": "$f(x) = 3x + 1$", "option_d": "$f(x) = \\ln(x)$",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! En una función exponencial, la variable $x$ aparece en el exponente: $f(x) = a \\cdot b^x$.",
        "feedback_incorrect": "En una función exponencial la variable está en el exponente. La correcta es $f(x) = 5 \\cdot 2^x$.",
        "graph_fn": None, "graph_view": None,
    },
    {
        "course_id": 1, "belt": "white", "topic": "exponential", "skill": "LEXI",
        "subtype": "graph",
        "question": "¿Cómo se llama la línea horizontal que esta curva se aproxima pero nunca alcanza?",
        "option_a": "Asíntota horizontal", "option_b": "Asíntota vertical",
        "option_c": "Eje de simetría", "option_d": "Tangente",
        "correct_index": 0, "has_math": False,
        "feedback_correct": "¡Correcto! Las funciones exponenciales tienen una asíntota horizontal ($y = 0$ en su forma básica).",
        "feedback_incorrect": "La línea horizontal que una curva se aproxima infinitamente sin tocarla se llama asíntota horizontal.",
        "graph_fn": "pow(2, x)", "graph_view": "[-4, 4, -1, 10]",
    },
    # ── EXPONENTIAL / CLSF ───────────────────────────────────────────
    {
        "course_id": 1, "belt": "white", "topic": "exponential", "skill": "CLSF",
        "subtype": "graph",
        "question": "¿A qué familia de funciones pertenece esta gráfica?",
        "option_a": "Exponencial", "option_b": "Polinómica",
        "option_c": "Logarítmica", "option_d": "Lineal",
        "correct_index": 0, "has_math": False,
        "feedback_correct": "¡Correcto! La curva crece aceleradamente: $f(x) = 3 \\cdot 2^x$, una función exponencial.",
        "feedback_incorrect": "El crecimiento acelerado con asíntota en $y = 0$ es propio de una exponencial: $f(x) = 3 \\cdot 2^x$.",
        "graph_fn": "3 * pow(2, x)", "graph_view": "[-3, 3, -1, 12]",
    },
    {
        "course_id": 1, "belt": "white", "topic": "exponential", "skill": "CLSF",
        "subtype": "text",
        "question": "¿A qué familia de funciones pertenece $f(x) = 3 \\cdot 2^x$?",
        "option_a": "Exponencial", "option_b": "Polinómica",
        "option_c": "Logarítmica", "option_d": "Lineal",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! En $f(x) = 3 \\cdot 2^x$, la variable $x$ está en el exponente: es una función exponencial.",
        "feedback_incorrect": "En $f(x) = 3 \\cdot 2^x$, la variable aparece en el exponente. Eso define una función exponencial.",
        "graph_fn": None, "graph_view": None,
    },
    # ── EXPONENTIAL / FORM ───────────────────────────────────────────
    {
        "course_id": 1, "belt": "white", "topic": "exponential", "skill": "FORM",
        "subtype": "text",
        "question": "En $f(x) = 3 \\cdot (0{,}5)^x$, ¿cuál es la base de la exponencial?",
        "option_a": "$0{,}5$", "option_b": "$3$",
        "option_c": "$x$", "option_d": "$1{,}5$",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! En $f(x) = a \\cdot b^x$, la base es $b = 0{,}5$. Como $0 < b < 1$, la función es decreciente.",
        "feedback_incorrect": "En $f(x) = a \\cdot b^x$, $b$ es la base. Aquí $b = 0{,}5$.",
        "graph_fn": None, "graph_view": None,
    },
    {
        "course_id": 1, "belt": "white", "topic": "exponential", "skill": "FORM",
        "subtype": "graph",
        "question": "¿Cuál de estas expresiones corresponde a la curva del gráfico?",
        "option_a": "$f(x) = (0{,}5)^x$", "option_b": "$f(x) = 2^x$",
        "option_c": "$f(x) = -2^x$", "option_d": "$f(x) = 2 \\cdot x$",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! La curva decrece hacia 0: base menor que 1, $f(x) = (0{,}5)^x$.",
        "feedback_incorrect": "La curva decrece (base $b < 1$) con asíntota en $y = 0$: corresponde a $f(x) = (0{,}5)^x$.",
        "graph_fn": "pow(0.5, x)", "graph_view": "[-3, 4, -0.5, 6]",
    },
    # ── LOGARITHMIC / LEXI ───────────────────────────────────────────
    {
        "course_id": 1, "belt": "white", "topic": "logarithmic", "skill": "LEXI",
        "subtype": "text",
        "question": "¿Cuál de estas expresiones es una función logarítmica?",
        "option_a": "$f(x) = \\log_2(x)$", "option_b": "$f(x) = 2^x$",
        "option_c": "$f(x) = x^2$", "option_d": "$f(x) = 1/x$",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! Una función logarítmica tiene la forma $f(x) = \\log_a(x)$.",
        "feedback_incorrect": "Una función logarítmica usa el logaritmo de la variable. La correcta es $f(x) = \\log_2(x)$.",
        "graph_fn": None, "graph_view": None,
    },
    {
        "course_id": 1, "belt": "white", "topic": "logarithmic", "skill": "LEXI",
        "subtype": "graph",
        "question": "¿Cómo se llama la línea vertical que actúa como frontera para esta función?",
        "option_a": "Asíntota vertical", "option_b": "Asíntota horizontal",
        "option_c": "Eje de simetría", "option_d": "Tangente",
        "correct_index": 0, "has_math": False,
        "feedback_correct": "¡Correcto! Las funciones logarítmicas tienen una asíntota vertical ($x = 0$ en su forma básica).",
        "feedback_incorrect": "La línea vertical que la función no puede cruzar se llama asíntota vertical. Aquí está en $x = 0$.",
        "graph_fn": "log2(x)", "graph_view": "[-0.5, 6, -4, 5]",
    },
    # ── LOGARITHMIC / CLSF ───────────────────────────────────────────
    {
        "course_id": 1, "belt": "white", "topic": "logarithmic", "skill": "CLSF",
        "subtype": "graph",
        "question": "¿A qué familia de funciones pertenece esta gráfica?",
        "option_a": "Logarítmica", "option_b": "Exponencial",
        "option_c": "Racional", "option_d": "Lineal",
        "correct_index": 0, "has_math": False,
        "feedback_correct": "¡Correcto! La curva crece lentamente para $x > 0$: $f(x) = \\log_2(x) + 1$, una función logarítmica.",
        "feedback_incorrect": "La asíntota vertical en $x = 0$ y el crecimiento lento son propios de una logarítmica: $f(x) = \\log_2(x) + 1$.",
        "graph_fn": "log2(x) + 1", "graph_view": "[-0.5, 6, -4, 5]",
    },
    {
        "course_id": 1, "belt": "white", "topic": "logarithmic", "skill": "CLSF",
        "subtype": "text",
        "question": "¿A qué familia de funciones pertenece $f(x) = \\log_2(x) + 1$?",
        "option_a": "Logarítmica", "option_b": "Exponencial",
        "option_c": "Racional", "option_d": "Lineal",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! $f(x) = \\log_2(x) + 1$ aplica un logaritmo a $x$: es una función logarítmica.",
        "feedback_incorrect": "$f(x) = \\log_2(x) + 1$ usa el logaritmo de la variable: pertenece a la familia logarítmica.",
        "graph_fn": None, "graph_view": None,
    },
    # ── LOGARITHMIC / FORM ───────────────────────────────────────────
    {
        "course_id": 1, "belt": "white", "topic": "logarithmic", "skill": "FORM",
        "subtype": "text",
        "question": "En $f(x) = \\log_5(x)$, ¿cuál es la base del logaritmo?",
        "option_a": "$5$", "option_b": "$x$",
        "option_c": "$1$", "option_d": "$0$",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! En $\\log_5(x)$, el subíndice $5$ es la base.",
        "feedback_incorrect": "En $\\log_a(x)$, $a$ es la base. En $\\log_5(x)$, la base es $5$.",
        "graph_fn": None, "graph_view": None,
    },
    {
        "course_id": 1, "belt": "white", "topic": "logarithmic", "skill": "FORM",
        "subtype": "graph",
        "question": "¿Cuál de estas expresiones corresponde a la curva del gráfico?",
        "option_a": "$f(x) = \\log_2(x+1)$", "option_b": "$f(x) = \\log_2(x)$",
        "option_c": "$f(x) = \\log_2(x-1)$", "option_d": "$f(x) = -\\log_2(x+1)$",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! La curva pasa por (0, 0) y tiene asíntota en $x = -1$: $f(x) = \\log_2(x+1)$.",
        "feedback_incorrect": "La asíntota vertical en $x = -1$ y el cruce por el origen indican $f(x) = \\log_2(x+1)$.",
        "graph_fn": "log2(x + 1)", "graph_view": "[-1, 6, -3, 4]",
    },
    # ── TRIGONOMETRIC / LEXI ─────────────────────────────────────────
    {
        "course_id": 1, "belt": "white", "topic": "trigonometric", "skill": "LEXI",
        "subtype": "text",
        "question": "¿Cuál de estas es una función trigonométrica?",
        "option_a": "$f(x) = \\operatorname{sen}(x)$", "option_b": "$f(x) = e^x$",
        "option_c": "$f(x) = x^3$", "option_d": "$f(x) = \\ln(x)$",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! El seno, coseno y tangente son las funciones trigonométricas básicas.",
        "feedback_incorrect": "Las funciones trigonométricas son seno, coseno y tangente. La correcta es $f(x) = \\operatorname{sen}(x)$.",
        "graph_fn": None, "graph_view": None,
    },
    {
        "course_id": 1, "belt": "white", "topic": "trigonometric", "skill": "LEXI",
        "subtype": "graph",
        "question": "¿Cómo se llama la distancia entre el valor máximo de la curva y su eje de simetría horizontal?",
        "option_a": "Amplitud", "option_b": "Período",
        "option_c": "Frecuencia", "option_d": "Fase",
        "correct_index": 0, "has_math": False,
        "feedback_correct": "¡Correcto! La amplitud es la distancia del máximo (o mínimo) al eje central. Aquí vale 2.",
        "feedback_incorrect": "Esa distancia se llama amplitud. En $f(x) = 2 \\cdot \\operatorname{sen}(x)$, la amplitud es 2.",
        "graph_fn": "2 * sin(x)", "graph_view": "[-7, 7, -3, 3]",
    },
    # ── TRIGONOMETRIC / CLSF ─────────────────────────────────────────
    {
        "course_id": 1, "belt": "white", "topic": "trigonometric", "skill": "CLSF",
        "subtype": "graph",
        "question": "¿A qué familia de funciones pertenece esta gráfica?",
        "option_a": "Trigonométrica", "option_b": "Exponencial",
        "option_c": "Polinómica", "option_d": "Racional",
        "correct_index": 0, "has_math": False,
        "feedback_correct": "¡Correcto! La oscilación periódica corresponde a $f(x) = 2 \\cdot \\operatorname{sen}(x)$, una función trigonométrica.",
        "feedback_incorrect": "La forma de onda periódica entre −2 y 2 es propia de una trigonométrica: $f(x) = 2 \\cdot \\operatorname{sen}(x)$.",
        "graph_fn": "2 * sin(x)", "graph_view": "[-7, 7, -3, 3]",
    },
    {
        "course_id": 1, "belt": "white", "topic": "trigonometric", "skill": "CLSF",
        "subtype": "text",
        "question": "¿A qué familia de funciones pertenece $f(x) = 2\\operatorname{sen}(x)$?",
        "option_a": "Trigonométrica", "option_b": "Exponencial",
        "option_c": "Polinómica", "option_d": "Racional",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! $f(x) = 2\\operatorname{sen}(x)$ usa la función seno: es trigonométrica.",
        "feedback_incorrect": "La función seno pertenece a la familia trigonométrica. $f(x) = 2\\operatorname{sen}(x)$ es trigonométrica.",
        "graph_fn": None, "graph_view": None,
    },
    # ── TRIGONOMETRIC / FORM ─────────────────────────────────────────
    {
        "course_id": 1, "belt": "white", "topic": "trigonometric", "skill": "FORM",
        "subtype": "text",
        "question": "En $f(x) = 3\\operatorname{sen}(2x + \\pi/4)$, ¿cuál es la amplitud?",
        "option_a": "$3$", "option_b": "$2$",
        "option_c": "$\\pi/4$", "option_d": "$1$",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! En $A \\cdot \\operatorname{sen}(Bx + C)$, la amplitud es $A = 3$.",
        "feedback_incorrect": "En $A \\cdot \\operatorname{sen}(Bx + C)$, $A$ es la amplitud. Aquí $A = 3$.",
        "graph_fn": None, "graph_view": None,
    },
    {
        "course_id": 1, "belt": "white", "topic": "trigonometric", "skill": "FORM",
        "subtype": "graph",
        "question": "¿Cuál de estas expresiones corresponde a la curva del gráfico?",
        "option_a": "$f(x) = \\cos(x)$", "option_b": "$f(x) = \\operatorname{sen}(x)$",
        "option_c": "$f(x) = 2\\cos(x)$", "option_d": "$f(x) = \\cos(2x)$",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! La curva parte de su máximo en $x = 0$ con amplitud 1: $f(x) = \\cos(x)$.",
        "feedback_incorrect": "La curva comienza en su valor máximo (1) cuando $x = 0$: eso es $f(x) = \\cos(x)$, no el seno.",
        "graph_fn": "cos(x)", "graph_view": "[-7, 7, -3, 3]",
    },
    # ── RATIONAL / LEXI ──────────────────────────────────────────────
    {
        "course_id": 1, "belt": "white", "topic": "rational", "skill": "LEXI",
        "subtype": "text",
        "question": "¿Cuál de estas es una función racional?",
        "option_a": "$f(x) = \\dfrac{x+1}{x-2}$", "option_b": "$f(x) = x^2 - 1$",
        "option_c": "$f(x) = 3^x$", "option_d": "$f(x) = \\sqrt{x}$",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! Una función racional es el cociente de dos polinomios.",
        "feedback_incorrect": "Una función racional es un cociente de polinomios. La correcta es $f(x) = \\dfrac{x+1}{x-2}$.",
        "graph_fn": None, "graph_view": None,
    },
    {
        "course_id": 1, "belt": "white", "topic": "rational", "skill": "LEXI",
        "subtype": "graph",
        "question": "¿Cómo se llaman las líneas que esta curva se aproxima pero nunca llega a tocar?",
        "option_a": "Asíntotas", "option_b": "Tangentes",
        "option_c": "Ejes de simetría", "option_d": "Rectas directrices",
        "correct_index": 0, "has_math": False,
        "feedback_correct": "¡Correcto! Las líneas que una curva se acerca indefinidamente sin tocar se llaman asíntotas.",
        "feedback_incorrect": "Esas líneas se llaman asíntotas. Esta función racional tiene una vertical ($x = 2$) y una horizontal ($y = 1$).",
        "graph_fn": "(x + 1) / (x - 2)", "graph_view": "[-5, 7, -8, 8]",
    },
    # ── RATIONAL / CLSF ──────────────────────────────────────────────
    {
        "course_id": 1, "belt": "white", "topic": "rational", "skill": "CLSF",
        "subtype": "graph",
        "question": "¿A qué familia de funciones pertenece esta gráfica?",
        "option_a": "Racional", "option_b": "Polinómica",
        "option_c": "Lineal", "option_d": "Logarítmica",
        "correct_index": 0, "has_math": False,
        "feedback_correct": "¡Correcto! Las dos ramas con asíntotas corresponden a $f(x) = \\dfrac{x+1}{x-2}$, una función racional.",
        "feedback_incorrect": "Las asíntotas vertical y horizontal con dos ramas separadas son propias de una racional: $f(x) = \\dfrac{x+1}{x-2}$.",
        "graph_fn": "(x + 1) / (x - 2)", "graph_view": "[-5, 7, -8, 8]",
    },
    {
        "course_id": 1, "belt": "white", "topic": "rational", "skill": "CLSF",
        "subtype": "text",
        "question": "¿A qué familia de funciones pertenece $f(x) = \\dfrac{x+1}{x-2}$?",
        "option_a": "Racional", "option_b": "Polinómica",
        "option_c": "Lineal", "option_d": "Logarítmica",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! $\\dfrac{x+1}{x-2}$ es el cociente de dos polinomios: es una función racional.",
        "feedback_incorrect": "$f(x) = \\dfrac{x+1}{x-2}$ es un cociente de polinomios: pertenece a la familia racional.",
        "graph_fn": None, "graph_view": None,
    },
    # ── RATIONAL / FORM ──────────────────────────────────────────────
    {
        "course_id": 1, "belt": "white", "topic": "rational", "skill": "FORM",
        "subtype": "text",
        "question": "¿Para qué valor de $x$ no está definida $f(x) = \\dfrac{2x + 3}{x - 5}$?",
        "option_a": "$x = 5$", "option_b": "$x = 3$",
        "option_c": "$x = -3$", "option_d": "$x = 2$",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! La función no está definida cuando el denominador se anula: $x - 5 = 0 \\Rightarrow x = 5$.",
        "feedback_incorrect": "La función no está definida donde el denominador es cero: $x - 5 = 0 \\Rightarrow x = 5$.",
        "graph_fn": None, "graph_view": None,
    },
    {
        "course_id": 1, "belt": "white", "topic": "rational", "skill": "FORM",
        "subtype": "graph",
        "question": "¿Cuál de estas expresiones corresponde a la curva del gráfico?",
        "option_a": "$f(x) = \\dfrac{1}{x-1}$", "option_b": "$f(x) = \\dfrac{1}{x+1}$",
        "option_c": "$f(x) = \\dfrac{x}{x-1}$", "option_d": "$f(x) = \\dfrac{1}{x^2-1}$",
        "correct_index": 0, "has_math": True,
        "feedback_correct": "¡Correcto! La asíntota vertical en $x = 1$ y la horizontal en $y = 0$ corresponden a $f(x) = \\dfrac{1}{x-1}$.",
        "feedback_incorrect": "La asíntota vertical está en $x = 1$ (denominador = 0) y la horizontal en $y = 0$: $f(x) = \\dfrac{1}{x-1}$.",
        "graph_fn": "1 / (x - 1)", "graph_view": "[-4, 6, -6, 6]",
    },
]


def fix():
    db = SessionLocal()
    try:
        deleted = db.query(Exercise).delete()
        print(f"Eliminados {deleted} ejercicios con encoding roto.")

        for data in EXERCISES_DATA:
            ex = Exercise(**data)
            db.add(ex)

        db.commit()
        count = db.query(Exercise).count()
        print(f"Insertados {count} ejercicios con Unicode correcto.")

        # Verificar una muestra
        sample = db.query(Exercise).filter(Exercise.topic == "linear", Exercise.skill == "LEXI").first()
        print(f"\nMuestra: {sample.question}")
        print(f"Opción A: {sample.option_a}")
    finally:
        db.close()


if __name__ == "__main__":
    fix()
