// AUTO-GENERATED by scripts/sync-emoji-tree.ts.
// Source: backend/content/emoji-tree.json
// Do not edit by hand; rerun `bun run scripts/sync-emoji-tree.ts`.

export type EmojiBucket = "E" | "S" | "T" | "M" | "Otra"

export interface EmojiNode {
  id: string
  emoji: string
  label: string
  unis?: string[]
  children?: EmojiNode[]
}

// Umbral de XP por profundidad del nodo (0 = raíz de bucket, gratis).
export const DEPTH_XP: Record<number, number> = {"1":64,"2":256,"3":1024,"4":4096,"5":8192}

export const EMOJI_TREE: Record<EmojiBucket, EmojiNode> = {
  "E": {
    "id": "E",
    "emoji": "⚙️",
    "label": "Ingeniería",
    "children": [
      {
        "id": "e-construccion",
        "emoji": "🏗️",
        "label": "Construcción",
        "children": [
          {
            "id": "e-infraestructura",
            "emoji": "🌉",
            "label": "Infraestructura",
            "children": [
              {
                "id": "e-estructuras",
                "emoji": "🧱",
                "label": "Estructuras",
                "children": [
                  {
                    "id": "e-hormigon",
                    "emoji": "🏢",
                    "label": "Hormigón",
                    "children": [
                      {
                        "id": "e-civil",
                        "emoji": "👷",
                        "label": "Civil",
                        "unis": [
                          "UBA",
                          "UTN"
                        ]
                      }
                    ]
                  }
                ]
              },
              {
                "id": "e-nautica",
                "emoji": "⚓",
                "label": "Náutica",
                "children": [
                  {
                    "id": "e-cascos",
                    "emoji": "🛳️",
                    "label": "Cascos",
                    "children": [
                      {
                        "id": "e-naval",
                        "emoji": "🚢",
                        "label": "Naval",
                        "unis": [
                          "UBA",
                          "UTN"
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            "id": "e-territorio",
            "emoji": "🧭",
            "label": "Territorio",
            "children": [
              {
                "id": "e-geomatica",
                "emoji": "📐",
                "label": "Geomática",
                "children": [
                  {
                    "id": "e-mensura",
                    "emoji": "🛰️",
                    "label": "Mensura",
                    "children": [
                      {
                        "id": "e-agrimensura",
                        "emoji": "📍",
                        "label": "Agrimensura",
                        "unis": [
                          "UBA"
                        ]
                      }
                    ]
                  }
                ]
              },
              {
                "id": "e-movilidad",
                "emoji": "🚦",
                "label": "Movilidad",
                "children": [
                  {
                    "id": "e-logistica",
                    "emoji": "🚉",
                    "label": "Logística",
                    "children": [
                      {
                        "id": "e-transporte",
                        "emoji": "🚆",
                        "label": "Transporte",
                        "unis": [
                          "UNSAM"
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "e-energia",
        "emoji": "⚡",
        "label": "Energía",
        "children": [
          {
            "id": "e-electricidad",
            "emoji": "🔌",
            "label": "Electricidad",
            "children": [
              {
                "id": "e-potencia",
                "emoji": "🏭",
                "label": "Potencia",
                "children": [
                  {
                    "id": "e-redes",
                    "emoji": "🔌",
                    "label": "Redes",
                    "children": [
                      {
                        "id": "e-electrica",
                        "emoji": "⚡",
                        "label": "Eléctrica",
                        "unis": [
                          "UBA",
                          "UTN"
                        ]
                      }
                    ]
                  }
                ]
              },
              {
                "id": "e-renovables",
                "emoji": "🔋",
                "label": "Renovables",
                "children": [
                  {
                    "id": "e-limpia",
                    "emoji": "☀️",
                    "label": "Limpia",
                    "children": [
                      {
                        "id": "e-energia-carrera",
                        "emoji": "🌬️",
                        "label": "Energía",
                        "unis": [
                          "UNSAM"
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            "id": "e-dispositivos",
            "emoji": "📡",
            "label": "Dispositivos",
            "children": [
              {
                "id": "e-circuitos",
                "emoji": "💾",
                "label": "Circuitos",
                "children": [
                  {
                    "id": "e-embebidos",
                    "emoji": "🔧",
                    "label": "Embebidos",
                    "children": [
                      {
                        "id": "e-electronica",
                        "emoji": "🔌",
                        "label": "Electrónica",
                        "unis": [
                          "UBA",
                          "UTN",
                          "UNSAM"
                        ]
                      }
                    ]
                  }
                ]
              },
              {
                "id": "e-senales",
                "emoji": "📶",
                "label": "Señales",
                "children": [
                  {
                    "id": "e-antenas",
                    "emoji": "🗼",
                    "label": "Antenas",
                    "children": [
                      {
                        "id": "e-telecomunicaciones",
                        "emoji": "📡",
                        "label": "Telecomunicaciones",
                        "unis": [
                          "UNSAM"
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "e-maquinas",
        "emoji": "🔧",
        "label": "Máquinas",
        "children": [
          {
            "id": "e-motriz",
            "emoji": "⚙️",
            "label": "Motriz",
            "children": [
              {
                "id": "e-diseno",
                "emoji": "🛠️",
                "label": "Diseño",
                "children": [
                  {
                    "id": "e-motores",
                    "emoji": "🏎️",
                    "label": "Motores",
                    "children": [
                      {
                        "id": "e-mecanica",
                        "emoji": "⚙️",
                        "label": "Mecánica",
                        "unis": [
                          "UBA",
                          "UTN"
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            "id": "e-produccion",
            "emoji": "🏭",
            "label": "Producción",
            "children": [
              {
                "id": "e-gestion-prod",
                "emoji": "📊",
                "label": "Gestión",
                "children": [
                  {
                    "id": "e-calidad",
                    "emoji": "📈",
                    "label": "Calidad",
                    "children": [
                      {
                        "id": "e-industrial",
                        "emoji": "🏭",
                        "label": "Industrial",
                        "unis": [
                          "UBA",
                          "UTN",
                          "UNSAM"
                        ]
                      }
                    ]
                  }
                ]
              },
              {
                "id": "e-manufactura",
                "emoji": "🧵",
                "label": "Manufactura",
                "children": [
                  {
                    "id": "e-hilados",
                    "emoji": "🪡",
                    "label": "Hilados",
                    "children": [
                      {
                        "id": "e-textil",
                        "emoji": "🧶",
                        "label": "Textil",
                        "unis": [
                          "UTN"
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "e-materia",
        "emoji": "⚗️",
        "label": "Materia",
        "children": [
          {
            "id": "e-reacciones",
            "emoji": "🧪",
            "label": "Reacciones",
            "children": [
              {
                "id": "e-sintesis",
                "emoji": "⚗️",
                "label": "Síntesis",
                "children": [
                  {
                    "id": "e-catalisis",
                    "emoji": "🧫",
                    "label": "Catálisis",
                    "children": [
                      {
                        "id": "e-quimica",
                        "emoji": "🥽",
                        "label": "Química",
                        "unis": [
                          "UBA",
                          "UTN"
                        ]
                      }
                    ]
                  }
                ]
              },
              {
                "id": "e-hidrocarburos",
                "emoji": "🛢️",
                "label": "Hidrocarburos",
                "children": [
                  {
                    "id": "e-yacimientos",
                    "emoji": "⛽",
                    "label": "Yacimientos",
                    "children": [
                      {
                        "id": "e-petroleo",
                        "emoji": "🛢️",
                        "label": "Petróleo",
                        "unis": [
                          "UBA"
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            "id": "e-solidos",
            "emoji": "💎",
            "label": "Sólidos",
            "children": [
              {
                "id": "e-metalurgia",
                "emoji": "🔩",
                "label": "Metalurgia",
                "children": [
                  {
                    "id": "e-aleaciones",
                    "emoji": "🧱",
                    "label": "Aleaciones",
                    "children": [
                      {
                        "id": "e-materiales",
                        "emoji": "💠",
                        "label": "Materiales",
                        "unis": [
                          "UNSAM-Sabato"
                        ]
                      }
                    ]
                  }
                ]
              },
              {
                "id": "e-procesado",
                "emoji": "🍞",
                "label": "Procesado",
                "children": [
                  {
                    "id": "e-conservacion",
                    "emoji": "🥫",
                    "label": "Conservación",
                    "children": [
                      {
                        "id": "e-alimentos",
                        "emoji": "🍎",
                        "label": "Alimentos",
                        "unis": [
                          "UBA"
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            "id": "e-vida",
            "emoji": "🌱",
            "label": "Vida",
            "children": [
              {
                "id": "e-ambiente",
                "emoji": "♻️",
                "label": "Ambiente",
                "children": [
                  {
                    "id": "e-sostenibilidad",
                    "emoji": "🌍",
                    "label": "Sostenibilidad",
                    "children": [
                      {
                        "id": "e-ambiental",
                        "emoji": "🌿",
                        "label": "Ambiental",
                        "unis": [
                          "UNSAM"
                        ]
                      }
                    ]
                  }
                ]
              },
              {
                "id": "e-bioingenieria",
                "emoji": "🧬",
                "label": "Bioingeniería",
                "children": [
                  {
                    "id": "e-equipos",
                    "emoji": "❤️",
                    "label": "Equipos",
                    "children": [
                      {
                        "id": "e-biomedica",
                        "emoji": "🩺",
                        "label": "Biomédica",
                        "unis": [
                          "UNSAM"
                        ]
                      }
                    ]
                  }
                ]
              },
              {
                "id": "e-agro",
                "emoji": "🌾",
                "label": "Agro",
                "children": [
                  {
                    "id": "e-cultivos",
                    "emoji": "🚜",
                    "label": "Cultivos",
                    "children": [
                      {
                        "id": "e-agronomia",
                        "emoji": "🌾",
                        "label": "Agronomía",
                        "unis": [
                          "UBA-FAUBA"
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  },
  "S": {
    "id": "S",
    "emoji": "🔬",
    "label": "Ciencias",
    "children": [
      {
        "id": "s-materia",
        "emoji": "🌐",
        "label": "Materia",
        "children": [
          {
            "id": "s-fisicoquimica",
            "emoji": "⚛️",
            "label": "Físico-química",
            "children": [
              {
                "id": "s-fisica",
                "emoji": "🔭",
                "label": "Física",
                "unis": [
                  "UBA"
                ],
                "children": [
                  {
                    "id": "s-cosmologia",
                    "emoji": "🌌",
                    "label": "Cosmología"
                  },
                  {
                    "id": "s-cuantica",
                    "emoji": "⚛️",
                    "label": "Cuántica"
                  },
                  {
                    "id": "s-particulas",
                    "emoji": "🎛️",
                    "label": "Partículas"
                  },
                  {
                    "id": "s-condensada",
                    "emoji": "🧲",
                    "label": "Condensada"
                  }
                ]
              },
              {
                "id": "s-quimica",
                "emoji": "🥽",
                "label": "Química",
                "unis": [
                  "UBA"
                ],
                "children": [
                  {
                    "id": "s-organica",
                    "emoji": "🧪",
                    "label": "Orgánica"
                  },
                  {
                    "id": "s-materiales-quim",
                    "emoji": "💎",
                    "label": "Materiales"
                  },
                  {
                    "id": "s-fisicoquimica-pasion",
                    "emoji": "⚡",
                    "label": "Físicoquímica"
                  },
                  {
                    "id": "s-verde",
                    "emoji": "🌿",
                    "label": "Verde"
                  }
                ]
              }
            ]
          },
          {
            "id": "s-tierra",
            "emoji": "🪐",
            "label": "Tierra",
            "children": [
              {
                "id": "s-geologia",
                "emoji": "⛏️",
                "label": "Geología",
                "unis": [
                  "UBA"
                ],
                "children": [
                  {
                    "id": "s-volcanes",
                    "emoji": "🌋",
                    "label": "Volcanes"
                  },
                  {
                    "id": "s-minerales",
                    "emoji": "💎",
                    "label": "Minerales"
                  },
                  {
                    "id": "s-tectonica",
                    "emoji": "🪨",
                    "label": "Tectónica"
                  }
                ]
              },
              {
                "id": "s-oceanografia",
                "emoji": "🌊",
                "label": "Oceanografía",
                "unis": [
                  "UBA"
                ],
                "children": [
                  {
                    "id": "s-marina",
                    "emoji": "🐋",
                    "label": "Marina"
                  },
                  {
                    "id": "s-corrientes",
                    "emoji": "🌀",
                    "label": "Corrientes"
                  },
                  {
                    "id": "s-quimica-marina",
                    "emoji": "🧪",
                    "label": "Química"
                  }
                ]
              },
              {
                "id": "s-atmosfera",
                "emoji": "🛰️",
                "label": "Atmósfera",
                "unis": [
                  "UBA"
                ],
                "children": [
                  {
                    "id": "s-clima",
                    "emoji": "🌪️",
                    "label": "Clima"
                  },
                  {
                    "id": "s-tormentas",
                    "emoji": "⛈️",
                    "label": "Tormentas"
                  },
                  {
                    "id": "s-calentamiento",
                    "emoji": "🌍",
                    "label": "Calentamiento"
                  }
                ]
              },
              {
                "id": "s-paleontologia",
                "emoji": "🦴",
                "label": "Paleontología",
                "unis": [
                  "UBA"
                ],
                "children": [
                  {
                    "id": "s-dinos",
                    "emoji": "🦕",
                    "label": "Dinos"
                  },
                  {
                    "id": "s-paleobotanica",
                    "emoji": "🌿",
                    "label": "Paleobotánica"
                  },
                  {
                    "id": "s-fosiles",
                    "emoji": "🐚",
                    "label": "Fósiles"
                  }
                ]
              }
            ]
          },
          {
            "id": "s-ambiente",
            "emoji": "🌱",
            "label": "Ambiente",
            "children": [
              {
                "id": "s-ambientales",
                "emoji": "🌿",
                "label": "Ambientales",
                "unis": [
                  "UBA"
                ],
                "children": [
                  {
                    "id": "s-conservacion",
                    "emoji": "♻️",
                    "label": "Conservación"
                  },
                  {
                    "id": "s-aguas",
                    "emoji": "💧",
                    "label": "Aguas"
                  },
                  {
                    "id": "s-ecologia-amb",
                    "emoji": "🌳",
                    "label": "Ecología"
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "s-vida",
        "emoji": "🧬",
        "label": "Vida",
        "children": [
          {
            "id": "s-organismos",
            "emoji": "🔬",
            "label": "Organismos",
            "children": [
              {
                "id": "s-biologia",
                "emoji": "🦠",
                "label": "Biología",
                "unis": [
                  "UBA"
                ],
                "children": [
                  {
                    "id": "s-genetica",
                    "emoji": "🧬",
                    "label": "Genética"
                  },
                  {
                    "id": "s-ecologia-bio",
                    "emoji": "🌳",
                    "label": "Ecología"
                  },
                  {
                    "id": "s-neuro",
                    "emoji": "🧠",
                    "label": "Neuro"
                  },
                  {
                    "id": "s-evolucion",
                    "emoji": "🦋",
                    "label": "Evolución"
                  }
                ]
              },
              {
                "id": "s-biotecnologia",
                "emoji": "🧬",
                "label": "Biotecnología",
                "unis": [
                  "UNSAM"
                ],
                "children": [
                  {
                    "id": "s-farma-biotec",
                    "emoji": "💊",
                    "label": "Farma"
                  },
                  {
                    "id": "s-agro-biotec",
                    "emoji": "🌾",
                    "label": "Agro"
                  },
                  {
                    "id": "s-industrial-biotec",
                    "emoji": "🏭",
                    "label": "Industrial"
                  },
                  {
                    "id": "s-medica-biotec",
                    "emoji": "🧫",
                    "label": "Médica"
                  }
                ]
              }
            ]
          },
          {
            "id": "s-salud",
            "emoji": "💊",
            "label": "Salud",
            "children": [
              {
                "id": "s-farmacia",
                "emoji": "💉",
                "label": "Farmacia",
                "unis": [
                  "UBA"
                ],
                "children": [
                  {
                    "id": "s-farmacos",
                    "emoji": "💊",
                    "label": "Fármacos"
                  },
                  {
                    "id": "s-industria-farm",
                    "emoji": "🏭",
                    "label": "Industria"
                  },
                  {
                    "id": "s-cosmetica",
                    "emoji": "🧴",
                    "label": "Cosmética"
                  }
                ]
              },
              {
                "id": "s-bioquimica",
                "emoji": "🩸",
                "label": "Bioquímica",
                "unis": [
                  "UBA"
                ],
                "children": [
                  {
                    "id": "s-molecular",
                    "emoji": "🧬",
                    "label": "Molecular"
                  },
                  {
                    "id": "s-clinica",
                    "emoji": "🔬",
                    "label": "Clínica"
                  },
                  {
                    "id": "s-alimentos-bioq",
                    "emoji": "🍔",
                    "label": "Alimentos"
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  },
  "T": {
    "id": "T",
    "emoji": "🤖",
    "label": "Tecnología",
    "children": [
      {
        "id": "t-computo",
        "emoji": "⚙️",
        "label": "Cómputo",
        "children": [
          {
            "id": "t-teoria",
            "emoji": "🧠",
            "label": "Teoría",
            "children": [
              {
                "id": "t-computacion",
                "emoji": "💻",
                "label": "Computación",
                "unis": [
                  "UBA"
                ],
                "children": [
                  {
                    "id": "t-ia-comp",
                    "emoji": "🤖",
                    "label": "IA"
                  },
                  {
                    "id": "t-algoritmos",
                    "emoji": "🧮",
                    "label": "Algoritmos"
                  },
                  {
                    "id": "t-graficos",
                    "emoji": "🎮",
                    "label": "Gráficos"
                  },
                  {
                    "id": "t-seguridad",
                    "emoji": "🔐",
                    "label": "Seguridad"
                  }
                ]
              }
            ]
          },
          {
            "id": "t-desarrollo",
            "emoji": "🏗️",
            "label": "Desarrollo",
            "children": [
              {
                "id": "t-informatica",
                "emoji": "🖥️",
                "label": "Informática",
                "unis": [
                  "UBA"
                ],
                "children": [
                  {
                    "id": "t-redes",
                    "emoji": "🌐",
                    "label": "Redes"
                  },
                  {
                    "id": "t-bases",
                    "emoji": "🗄️",
                    "label": "Bases"
                  },
                  {
                    "id": "t-cloud",
                    "emoji": "☁️",
                    "label": "Cloud"
                  },
                  {
                    "id": "t-ciberseguridad",
                    "emoji": "🔐",
                    "label": "Ciberseguridad"
                  }
                ]
              },
              {
                "id": "t-software",
                "emoji": "🧩",
                "label": "Software",
                "unis": [
                  "UNSAM"
                ],
                "children": [
                  {
                    "id": "t-apps",
                    "emoji": "📱",
                    "label": "Apps"
                  },
                  {
                    "id": "t-web",
                    "emoji": "🌐",
                    "label": "Web"
                  },
                  {
                    "id": "t-juegos",
                    "emoji": "🎮",
                    "label": "Juegos"
                  },
                  {
                    "id": "t-backend",
                    "emoji": "⚙️",
                    "label": "Backend"
                  }
                ]
              }
            ]
          },
          {
            "id": "t-gestion",
            "emoji": "🗂️",
            "label": "Gestión",
            "children": [
              {
                "id": "t-sistemas",
                "emoji": "🔩",
                "label": "Sistemas",
                "unis": [
                  "UTN"
                ],
                "children": [
                  {
                    "id": "t-empresarial",
                    "emoji": "🏢",
                    "label": "Empresarial"
                  },
                  {
                    "id": "t-integracion",
                    "emoji": "🔗",
                    "label": "Integración"
                  },
                  {
                    "id": "t-bi",
                    "emoji": "📊",
                    "label": "BI"
                  }
                ]
              },
              {
                "id": "t-analisis",
                "emoji": "🗃️",
                "label": "Análisis",
                "unis": [
                  "UBA"
                ],
                "children": [
                  {
                    "id": "t-requerimientos",
                    "emoji": "📋",
                    "label": "Requerimientos"
                  },
                  {
                    "id": "t-procesos-anal",
                    "emoji": "🔄",
                    "label": "Procesos"
                  },
                  {
                    "id": "t-testing",
                    "emoji": "🧪",
                    "label": "Testing"
                  }
                ]
              },
              {
                "id": "t-organizaciones",
                "emoji": "🏢",
                "label": "Organizaciones",
                "unis": [
                  "UBA-FCE"
                ],
                "children": [
                  {
                    "id": "t-gestion-org",
                    "emoji": "📊",
                    "label": "Gestión"
                  },
                  {
                    "id": "t-procesos-org",
                    "emoji": "🔄",
                    "label": "Procesos"
                  },
                  {
                    "id": "t-negocio-org",
                    "emoji": "💼",
                    "label": "Negocio"
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "t-informacion",
        "emoji": "📡",
        "label": "Información",
        "children": [
          {
            "id": "t-ciencia",
            "emoji": "🔬",
            "label": "Ciencia",
            "children": [
              {
                "id": "t-datos",
                "emoji": "📊",
                "label": "Datos",
                "unis": [
                  "UNSAM",
                  "UBA"
                ],
                "children": [
                  {
                    "id": "t-ml",
                    "emoji": "🤖",
                    "label": "ML"
                  },
                  {
                    "id": "t-estadistica",
                    "emoji": "📈",
                    "label": "Estadística"
                  },
                  {
                    "id": "t-nlp",
                    "emoji": "🗣️",
                    "label": "NLP"
                  },
                  {
                    "id": "t-vision",
                    "emoji": "👁️",
                    "label": "Visión"
                  }
                ]
              }
            ]
          },
          {
            "id": "t-negocio",
            "emoji": "📉",
            "label": "Negocio",
            "children": [
              {
                "id": "t-analitica",
                "emoji": "📈",
                "label": "Analítica",
                "unis": [
                  "UBA-FCE"
                ],
                "children": [
                  {
                    "id": "t-visualizacion",
                    "emoji": "📊",
                    "label": "Visualización"
                  },
                  {
                    "id": "t-marketing-anal",
                    "emoji": "🎯",
                    "label": "Marketing"
                  },
                  {
                    "id": "t-negocio-anal",
                    "emoji": "💼",
                    "label": "Negocio"
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  },
  "M": {
    "id": "M",
    "emoji": "π",
    "label": "Matemática",
    "children": [
      {
        "id": "m-pura",
        "emoji": "∫",
        "label": "Pura",
        "children": [
          {
            "id": "m-fundamentos",
            "emoji": "🧮",
            "label": "Fundamentos",
            "children": [
              {
                "id": "m-matematica",
                "emoji": "📐",
                "label": "Matemática",
                "unis": [
                  "UBA"
                ],
                "children": [
                  {
                    "id": "m-analisis",
                    "emoji": "∑",
                    "label": "Análisis"
                  },
                  {
                    "id": "m-algebra",
                    "emoji": "⬡",
                    "label": "Álgebra"
                  },
                  {
                    "id": "m-geometria",
                    "emoji": "🔺",
                    "label": "Geometría"
                  },
                  {
                    "id": "m-topologia",
                    "emoji": "🌀",
                    "label": "Topología"
                  },
                  {
                    "id": "m-logica",
                    "emoji": "🔢",
                    "label": "Lógica"
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "m-aplicada",
        "emoji": "📊",
        "label": "Aplicada",
        "children": [
          {
            "id": "m-probabilidad",
            "emoji": "🎲",
            "label": "Probabilidad",
            "children": [
              {
                "id": "m-actuario",
                "emoji": "💼",
                "label": "Actuario",
                "unis": [
                  "UBA-FCE"
                ],
                "children": [
                  {
                    "id": "m-seguros",
                    "emoji": "🛡️",
                    "label": "Seguros"
                  },
                  {
                    "id": "m-finanzas-act",
                    "emoji": "💰",
                    "label": "Finanzas"
                  },
                  {
                    "id": "m-pensiones",
                    "emoji": "👴",
                    "label": "Pensiones"
                  },
                  {
                    "id": "m-riesgo-act",
                    "emoji": "📉",
                    "label": "Riesgo"
                  }
                ]
              }
            ]
          },
          {
            "id": "m-modelos",
            "emoji": "🤖",
            "label": "Modelos",
            "children": [
              {
                "id": "m-datos",
                "emoji": "📈",
                "label": "Datos",
                "unis": [
                  "UBA",
                  "UNSAM"
                ],
                "children": [
                  {
                    "id": "m-ml",
                    "emoji": "🤖",
                    "label": "ML"
                  },
                  {
                    "id": "m-estadistica",
                    "emoji": "📊",
                    "label": "Estadística"
                  },
                  {
                    "id": "m-ia",
                    "emoji": "🧠",
                    "label": "IA"
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  },
  "Otra": {
    "id": "Otra",
    "emoji": "✦",
    "label": "Otra",
    "children": [
      {
        "id": "o-economia",
        "emoji": "💰",
        "label": "Economía",
        "children": [
          {
            "id": "o-mercados",
            "emoji": "📈",
            "label": "Mercados",
            "children": [
              {
                "id": "o-economia-carrera",
                "emoji": "💹",
                "label": "Economía",
                "unis": [
                  "UBA",
                  "UNSAM"
                ],
                "children": [
                  {
                    "id": "o-macro",
                    "emoji": "📊",
                    "label": "Macro"
                  },
                  {
                    "id": "o-micro",
                    "emoji": "🔬",
                    "label": "Micro"
                  },
                  {
                    "id": "o-comportamiento",
                    "emoji": "🧠",
                    "label": "Comportamiento"
                  },
                  {
                    "id": "o-internacional",
                    "emoji": "🌍",
                    "label": "Internacional"
                  }
                ]
              },
              {
                "id": "o-conocimiento",
                "emoji": "🧠",
                "label": "Conocimiento",
                "unis": [
                  "UNSAM"
                ],
                "children": [
                  {
                    "id": "o-ia",
                    "emoji": "🤖",
                    "label": "IA"
                  },
                  {
                    "id": "o-industria40",
                    "emoji": "🏭",
                    "label": "Industria 4.0"
                  },
                  {
                    "id": "o-datos",
                    "emoji": "📊",
                    "label": "Datos"
                  }
                ]
              }
            ]
          },
          {
            "id": "o-riesgo",
            "emoji": "🎲",
            "label": "Riesgo",
            "children": [
              {
                "id": "o-actuario",
                "emoji": "💼",
                "label": "Actuario",
                "unis": [
                  "UBA-FCE"
                ],
                "children": [
                  {
                    "id": "o-seguros",
                    "emoji": "🛡️",
                    "label": "Seguros"
                  },
                  {
                    "id": "o-finanzas-act",
                    "emoji": "💰",
                    "label": "Finanzas"
                  },
                  {
                    "id": "o-riesgo-pasion",
                    "emoji": "📉",
                    "label": "Riesgo"
                  }
                ]
              }
            ]
          },
          {
            "id": "o-agro",
            "emoji": "🌾",
            "label": "Agro",
            "children": [
              {
                "id": "o-agraria",
                "emoji": "💵",
                "label": "Agraria",
                "unis": [
                  "UBA-FAUBA"
                ],
                "children": [
                  {
                    "id": "o-produccion-agr",
                    "emoji": "🌾",
                    "label": "Producción"
                  },
                  {
                    "id": "o-mercados-agr",
                    "emoji": "📊",
                    "label": "Mercados"
                  },
                  {
                    "id": "o-tierras",
                    "emoji": "🏞️",
                    "label": "Tierras"
                  }
                ]
              },
              {
                "id": "o-agroalimentos",
                "emoji": "🥖",
                "label": "Agroalimentos",
                "unis": [
                  "UBA-FAUBA"
                ],
                "children": [
                  {
                    "id": "o-industria-agr",
                    "emoji": "🏭",
                    "label": "Industria"
                  },
                  {
                    "id": "o-calidad-agr",
                    "emoji": "🔬",
                    "label": "Calidad"
                  },
                  {
                    "id": "o-exportacion",
                    "emoji": "🌍",
                    "label": "Exportación"
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "o-gestion",
        "emoji": "🏢",
        "label": "Gestión",
        "children": [
          {
            "id": "o-empresas",
            "emoji": "📊",
            "label": "Empresas",
            "children": [
              {
                "id": "o-administracion",
                "emoji": "🗃️",
                "label": "Administración",
                "unis": [
                  "UBA",
                  "UNSAM"
                ],
                "children": [
                  {
                    "id": "o-marketing",
                    "emoji": "📣",
                    "label": "Marketing"
                  },
                  {
                    "id": "o-finanzas-adm",
                    "emoji": "💰",
                    "label": "Finanzas"
                  },
                  {
                    "id": "o-rrhh",
                    "emoji": "👥",
                    "label": "RRHH"
                  },
                  {
                    "id": "o-estrategia",
                    "emoji": "🎯",
                    "label": "Estrategia"
                  }
                ]
              }
            ]
          },
          {
            "id": "o-cuentas",
            "emoji": "🧾",
            "label": "Cuentas",
            "children": [
              {
                "id": "o-contador",
                "emoji": "🧮",
                "label": "Contador",
                "unis": [
                  "UBA",
                  "UNSAM"
                ],
                "children": [
                  {
                    "id": "o-auditoria",
                    "emoji": "🔍",
                    "label": "Auditoría"
                  },
                  {
                    "id": "o-impuestos",
                    "emoji": "🧾",
                    "label": "Impuestos"
                  },
                  {
                    "id": "o-costos",
                    "emoji": "📊",
                    "label": "Costos"
                  },
                  {
                    "id": "o-gestion-cont",
                    "emoji": "💼",
                    "label": "Gestión"
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  }
}
