// AUTO-GENERATED by scripts/sync-catalog.ts.
// Source: backend/content/algebra/course.json
// Do not edit by hand; rerun `bun run scripts/sync-catalog.ts`.

export type BeltKey = "white" | "blue" | "violet" | "brown"

export interface Topic {
  key: string
  name: string
  tooltip: string
  short_description?: string
  skills: string[]
}

export interface Unit {
  key: string
  name: string
  description?: string
  topics: Topic[]
}

export interface Belt {
  key: BeltKey
  headline: string
  description: string
  units: Unit[]
}

export interface ExerciseType {
  id: string
  label: string
  description: string
}

export interface Catalog {
  slug: string
  name: string
  description: string
  belts: Belt[]
  exercise_types: ExerciseType[]
}

export const catalog: Catalog = {
  "slug": "algebra",
  "name": "Álgebra Lineal",
  "description": "Sistema de repaso adaptativo para Álgebra Lineal I",
  "exercise_types": [
    {
      "id": "LEXI",
      "label": "Léxico",
      "description": "Definiciones, vocabulario y notación del tema."
    },
    {
      "id": "CLSF",
      "label": "Clasificación",
      "description": "Reconocer y clasificar objetos, vectores, matrices o transformaciones."
    },
    {
      "id": "FORM",
      "label": "Formulación",
      "description": "Identificar y aplicar los componentes de una fórmula o ecuación."
    },
    {
      "id": "GRAF",
      "label": "Gráficos",
      "description": "Leer e interpretar información geométrica y representaciones en el plano y el espacio."
    },
    {
      "id": "ESTR",
      "label": "Planteo",
      "description": "Elegir el método o las condiciones para resolver."
    },
    {
      "id": "RESL",
      "label": "Resolución",
      "description": "Calcular el resultado paso a paso."
    }
  ],
  "belts": [
    {
      "key": "white",
      "headline": "Aritmética",
      "description": "Las **operaciones aritméticas** fundamentales (fracciones, potencias, raíces, logaritmos, signos) son la base operativa sobre la que se apoya el resto del álgebra.",
      "units": [
        {
          "key": "aritmetica",
          "name": "Aritmética",
          "description": "Las **operaciones aritméticas fundamentales** (fracciones, potencias, radicales, logaritmos, notación, valor absoluto y propiedades algebraicas básicas) son la base operativa sobre la que se apoya el resto del álgebra.\n$$\\frac{a}{b}, \\quad a^n, \\quad \\sqrt[n]{a}$$\nDominarlas evita que un error de cálculo bloquee el razonamiento en temas más avanzados.",
          "topics": [
            {
              "key": "fracciones",
              "name": "Fracciones",
              "tooltip": "Una **fracción** $\\frac{a}{b}$ representa una parte de un todo o una razón entre dos cantidades.\n$$\\frac{a}{b} \\cdot \\frac{c}{d} = \\frac{a \\cdot c}{b \\cdot d}$$\nMás allá de la mecánica de sumar y multiplicar, dominar fracciones compuestas, el signo y la comparación sin pasar a decimales evita errores que se arrastran a matrices y sistemas.",
              "short_description": "Las **fracciones** representan una parte de un todo o una razón entre cantidades.\n$$\\frac{a}{b} \\cdot \\frac{c}{d} = \\frac{a \\cdot c}{b \\cdot d}$$",
              "skills": [
                "LEXI",
                "ESTR",
                "RESL"
              ]
            },
            {
              "key": "powers",
              "name": "Potenciación",
              "tooltip": "La **potenciación** $a^n$ representa la multiplicación repetida de una base $a$ por sí misma $n$ veces.\n$$a^m \\cdot a^n = a^{m+n}, \\quad a^{-n} = \\frac{1}{a^n}$$\nSus propiedades (producto y cociente de potencias de igual base, potencia de potencia, exponente negativo y fraccionario) son la herramienta operativa detrás de toda la notación algebraica posterior.",
              "short_description": "Las **propiedades de la potenciación** permiten operar exponentes sin desarrollar la multiplicación completa.\n$$a^m \\cdot a^n = a^{m+n}$$",
              "skills": [
                "LEXI",
                "RESL",
                "FORM"
              ]
            },
            {
              "key": "radicals",
              "name": "Radicales",
              "tooltip": "La **raíz enésima** $\\sqrt[n]{a}$ es la operación inversa de elevar a la potencia $n$.\n$$\\sqrt[n]{a} = a^{1/n}$$\nSimplificar radicales y racionalizar denominadores, eliminar raíces del denominador multiplicando por un factor adecuado, evita arrastrar expresiones irracionales innecesarias en los cálculos.",
              "short_description": "La **raíz enésima** es la operación inversa de la potenciación.\n$$\\sqrt[n]{a} = a^{1/n}$$",
              "skills": [
                "LEXI",
                "RESL",
                "FORM"
              ]
            },
            {
              "key": "logarithms",
              "name": "Logaritmos",
              "tooltip": "El **logaritmo** en base $b$ de un número $x$ es el exponente al que hay que elevar $b$ para obtener $x$.\n$$\\log_b(x) = y \\iff b^y = x$$\nSus propiedades operativas (logaritmo de un producto, un cociente y una potencia) permiten simplificar cálculos antes de que aparezca la función logarítmica como objeto en sí.",
              "short_description": "El **logaritmo** en base $b$ de $x$ es el exponente al que se eleva $b$ para obtener $x$.\n$$\\log_b(x) = y \\iff b^y = x$$",
              "skills": [
                "LEXI",
                "RESL",
                "FORM"
              ]
            },
            {
              "key": "scientific_notation",
              "name": "Notación",
              "tooltip": "La **notación científica** expresa cualquier número como el producto de un valor entre $1$ y $10$ por una potencia de $10$.\n$$a \\times 10^n, \\quad 1 \\leq |a| < 10$$\nFacilita operar con cantidades extremadamente grandes o pequeñas sin escribir todos los ceros, y es el formato estándar en ciencias e ingeniería.",
              "short_description": "La **notación científica** expresa un número como $a \\times 10^n$ con $1 \\leq |a| < 10$.\n$$a \\times 10^n$$",
              "skills": [
                "RESL",
                "FORM"
              ]
            },
            {
              "key": "absolute_value",
              "name": "Absoluto",
              "tooltip": "El **valor absoluto** $|a|$ de un número mide su distancia al cero en la recta numérica, sin importar el signo.\n$$|a| = \\begin{cases} a & \\text{si } a \\geq 0 \\\\ -a & \\text{si } a < 0 \\end{cases}$$\nAparece constantemente al resolver ecuaciones e inecuaciones, y su propiedad clave es que siempre devuelve un resultado no negativo.",
              "short_description": "El **valor absoluto** mide la distancia de un número al cero, siempre con resultado no negativo.\n$$|{-5}| = 5$$",
              "skills": [
                "RESL",
                "FORM"
              ]
            },
            {
              "key": "algebraic_properties",
              "name": "Propiedades",
              "tooltip": "La **propiedad distributiva** y la extracción de **factor común** permiten transformar una expresión con paréntesis en una suma de términos, y viceversa.\n$$a(b + c) = ab + ac$$\nDominar el manejo de signos al abrir o cerrar paréntesis, sobre todo cuando el signo exterior es negativo, es el paso operativo que conecta la aritmética numérica con el álgebra simbólica de las unidades siguientes.",
              "short_description": "La **distributiva** transforma una expresión entre paréntesis en una suma de términos.\n$$a(b+c) = ab + ac$$",
              "skills": [
                "LEXI",
                "RESL",
                "FORM"
              ]
            }
          ]
        }
      ]
    },
    {
      "key": "blue",
      "headline": "Vectores",
      "description": "Un **vector** en el plano o el espacio es una magnitud con dirección y sentido, representable como un segmento orientado o como una lista de componentes.\n$$\u000bec{v} = (v_1, v_2, v_3)$$\nSus operaciones y propiedades son la base de las matrices y las transformaciones lineales.",
      "units": [
        {
          "key": "vectors",
          "name": "Vectores",
          "description": "Un **vector** es un ente matemático que pertenece a un espacio $\\mathbb{R}^n$, definido por una tupla ordenada de componentes.\n$$\\vec{v} = (v_1, v_2, \\dots, v_n)$$\nEsta unidad introduce los conceptos fundamentales de geometría vectorial, operaciones, métricas y geometría analítica en el plano y el espacio.",
          "topics": [
            {
              "key": "definition",
              "name": "Definición",
              "tooltip": "Un **vector** es un ente matemático que pertenece a un espacio $\\mathbb{R}^n$, definido por una tupla ordenada de componentes.\n$$\\vec{v} = (v_1, v_2, \\dots, v_n)$$\nGeométricamente, en $\\mathbb{R}^2$ y $\\mathbb{R}^3$, modela magnitudes que poseen dirección y sentido, como desplazamientos o fuerzas. Constituye el objeto de estudio fundamental sobre el cual se construyen los espacios vectoriales.",
              "short_description": "Un **vector** es un ente matemático que pertenece a un espacio $\\mathbb{R}^n$, definido por una tupla ordenada de componentes.\n$$\\vec{v} = (v_1, v_2, \\dots, v_n)$$",
              "skills": [
                "LEXI",
                "CLSF"
              ]
            },
            {
              "key": "operations",
              "name": "Operaciones",
              "tooltip": "Las operaciones básicas entre vectores son la **suma** componente a componente y el **producto por un escalar**.\n$$\\alpha\\vec{v} = (\\alpha v_1, \\alpha v_2, \\dots, \\alpha v_n)$$\nEstas operaciones permiten escalar, invertir o combinar vectores geométricamente. Son las dos operaciones que estructuran axiomáticamente a cualquier espacio vectorial.",
              "short_description": "Las operaciones básicas entre vectores son la **suma** componente a componente y el **producto por un escalar**.\n$$\\alpha\\vec{v} = (\\alpha v_1, \\alpha v_2, \\dots, \\alpha v_n)$$",
              "skills": [
                "LEXI",
                "RESL"
              ]
            },
            {
              "key": "norm",
              "name": "Norma",
              "tooltip": "La **norma** o módulo de un vector cuantifica su longitud o magnitud en el espacio, calculada a partir de sus componentes.\n$$\\| \\vec{v} \\| = \\sqrt{v_1^2 + v_2^2 + \\dots + v_n^2}$$\nPermite definir conceptos métricos como la distancia entre dos puntos y la normalización de vectores, llevándolos a longitud unitaria sin alterar su dirección.",
              "short_description": "La **norma** o módulo de un vector cuantifica su longitud o magnitud en el espacio, calculada a partir de sus componentes.\n$$\\| \\vec{v} \\| = \\sqrt{v_1^2 + v_2^2 + \\dots + v_n^2}$$",
              "skills": [
                "LEXI",
                "RESL"
              ]
            },
            {
              "key": "scalar",
              "name": "Escalar",
              "tooltip": "La operación **escalar** (producto interno) toma dos vectores y devuelve un número real, vinculando sus magnitudes con el ángulo que forman.\n$$\\vec{u} \\cdot \\vec{v} = \\| \\vec{u} \\| \\| \\vec{v} \\| \\cos(\\theta)$$\nAlgebraicamente, se calcula sumando el producto de sus componentes homólogas. Es la herramienta principal para proyectar un vector sobre otro y analizar la relación angular.",
              "short_description": "La operación **escalar** (producto interno) toma dos vectores y devuelve un número real, vinculando sus magnitudes con el ángulo que forman.\n$$\\vec{u} \\cdot \\vec{v} = \\| \\vec{u} \\| \\| \\vec{v} \\| \\cos(\\theta)$$",
              "skills": [
                "LEXI",
                "RESL"
              ]
            },
            {
              "key": "orthogonality",
              "name": "Ortogonalidad",
              "tooltip": "Dos vectores son **ortogonales** si el ángulo entre ellos es recto, lo cual se verifica analíticamente cuando su producto escalar es nulo.\n$$\\vec{u} \\cdot \\vec{v} = 0$$\nEsta condición de perpendicularidad simplifica cálculos de proyecciones y es la base para construir sistemas de coordenadas independientes, donde el movimiento en una dirección no afecta a la otra.",
              "short_description": "Dos vectores son **ortogonales** si el ángulo entre ellos es recto, lo cual se verifica analíticamente cuando su producto escalar es nulo.\n$$\\vec{u} \\cdot \\vec{v} = 0$$",
              "skills": [
                "LEXI",
                "CLSF",
                "RESL"
              ]
            },
            {
              "key": "product",
              "name": "Producto",
              "tooltip": "El **producto** vectorial es una operación exclusiva de $\\mathbb{R}^3$ que toma dos vectores y devuelve un tercer vector, perpendicular a ambos.\n$$\\vec{w} = \\vec{u} \\times \\vec{v}$$\nLa norma de este nuevo vector equivale al área del paralelogramo que forman los vectores originales. Se utiliza habitualmente para hallar vectores normales a planos.",
              "short_description": "El **producto** vectorial es una operación exclusiva de $\\mathbb{R}^3$ que toma dos vectores y devuelve un tercer vector, perpendicular a ambos.\n$$\\vec{w} = \\vec{u} \\times \\vec{v}$$",
              "skills": [
                "LEXI",
                "RESL"
              ]
            }
          ]
        }
      ]
    },
    {
      "key": "violet",
      "headline": "Matrices",
      "description": "Una **matriz** organiza números en filas y columnas para representar sistemas de ecuaciones y transformaciones lineales de forma compacta.\n$$A \\in \\mathbb{R}^{m \times n}$$\nSus operaciones, determinante e inversa permiten resolver sistemas y estudiar la estructura del espacio que la matriz transforma.",
      "units": [
        {
          "key": "matrices",
          "name": "Matrices",
          "description": "Una **matriz** es un arreglo rectangular de escalares dispuestos en filas y columnas.\n$$A \\in \\mathbb{R}^{m \\times n}$$\nEsta unidad abarca el álgebra matricial, los determinantes, la inversión de matrices y los métodos para resolver sistemas lineales.",
          "topics": [
            {
              "key": "definition",
              "name": "Definición",
              "tooltip": "Una **matriz** es un arreglo rectangular de escalares dispuestos en filas y columnas.\n$$A \\in \\mathbb{R}^{m \\times n}$$\nFunciona como una estructura de datos para organizar coeficientes de sistemas de ecuaciones y como el operador matemático que aplica transformaciones lineales sobre vectores.",
              "short_description": "Una **matriz** es un arreglo rectangular de escalares dispuestos en filas y columnas.\n$$A \\in \\mathbb{R}^{m \\times n}$$",
              "skills": [
                "LEXI",
                "CLSF"
              ]
            },
            {
              "key": "operations",
              "name": "Operaciones",
              "tooltip": "La suma de matrices se realiza elemento a elemento, mientras que el **producto matricial** combina las filas de la primera con las columnas de la segunda.\n$$C_{ij} = \\sum_{k=1}^n A_{ik}B_{kj}$$\nA diferencia del producto de números reales, la multiplicación de matrices no es conmutativa. El orden de los factores altera el resultado, reflejando transformaciones secuenciales.",
              "short_description": "La suma de matrices se realiza elemento a elemento, mientras que el **producto matricial** combina las filas de la primera con las columnas de la segunda.\n$$C_{ij} = \\sum_{k=1}^n A_{ik}B_{kj}$$",
              "skills": [
                "LEXI",
                "RESL"
              ]
            },
            {
              "key": "transpose",
              "name": "Transpuesta",
              "tooltip": "La **matriz transpuesta** se obtiene intercambiando las filas por las columnas de la matriz original.\n$$(A^T)_{ij} = A_{ji}$$\nSi una matriz es igual a su transpuesta, se clasifica como simétrica. Esta operación conserva la diagonal principal inalterada e invierte el orden en el caso del producto matricial.",
              "short_description": "La **matriz transpuesta** se obtiene intercambiando las filas por las columnas de la matriz original.\n$$(A^T)_{ij} = A_{ji}$$",
              "skills": [
                "LEXI",
                "RESL"
              ]
            },
            {
              "key": "determinants",
              "name": "Determinantes",
              "tooltip": "El **determinante** es un escalar asociado a una matriz cuadrada que indica, entre otras propiedades, si el sistema tiene solución única.\n$$\\det(A) \\neq 0 \\iff \\text{Inversible}$$\nGeométricamente, representa el factor por el cual la matriz expande o contrae el volumen en el espacio. Si el determinante es cero, la transformación colapsa el espacio.",
              "short_description": "El **determinante** es un escalar asociado a una matriz cuadrada que indica si la matriz es inversible.\n$$\\det(A) \\neq 0 \\iff \\text{Inversible}$$",
              "skills": [
                "LEXI",
                "RESL"
              ]
            },
            {
              "key": "inverse",
              "name": "Inversa",
              "tooltip": "La **matriz inversa** es aquella que, al multiplicarse por la matriz original, da como resultado la matriz identidad.\n$$A A^{-1} = A^{-1} A = I$$\nFunciona como la operación de división en el álgebra matricial, deshaciendo la transformación aplicada por la matriz original. Solo existe para matrices cuadradas de determinante no nulo.",
              "short_description": "La **matriz inversa** es aquella que, al multiplicarse por la matriz original, da como resultado la matriz identidad.\n$$A A^{-1} = A^{-1} A = I$$",
              "skills": [
                "LEXI",
                "RESL"
              ]
            }
          ]
        }
      ]
    },
    {
      "key": "brown",
      "headline": "Espacios",
      "description": "Un **espacio vectorial** es un conjunto de elementos sobre un cuerpo que cumple los axiomas de clausura y linealidad.\n$$\\alpha\\vec{u} + \\vec{v} \\in S$$\nEsta unidad introduce los conceptos fundamentales de subespacios, combinaciones lineales, independencia, generadores, bases y dimensión.",
      "units": [
        {
          "key": "spaces",
          "name": "Espacios",
          "description": "Un espacio vectorial es un conjunto de elementos sobre un cuerpo que cumple los axiomas de clausura y linealidad.\n$$\\alpha\\vec{u} + \\vec{v} \\in S$$\nEsta unidad introduce los conceptos fundamentales de subespacios, combinaciones, bases y dimensión.",
          "topics": [
            {
              "key": "definition",
              "name": "Definición",
              "tooltip": "Un **espacio vectorial** es un conjunto $V$ con dos operaciones, suma y producto por escalar, que satisfacen un conjunto de axiomas: clausura, asociatividad, existencia de neutro y opuesto, y distributividad.\n$$\\vec{u}+\\vec{v} \\in V, \\quad \\alpha\\vec{v} \\in V$$\n$\\mathbb{R}^n$ es el ejemplo prototípico, pero la definición abstracta permite trabajar con otros conjuntos, como polinomios o matrices, bajo la misma estructura.",
              "short_description": "Un **espacio vectorial** es un conjunto $V$ con operaciones de suma y producto por escalar que satisface un conjunto de axiomas de clausura y linealidad.\n$$\\vec{u}+\\vec{v} \\in V, \\quad \\alpha\\vec{v} \\in V$$",
              "skills": [
                "LEXI",
                "CLSF"
              ]
            },
            {
              "key": "subspaces",
              "name": "Subespacios",
              "tooltip": "Un **subespacio vectorial** es un subconjunto de un espacio mayor que se comporta como un espacio vectorial por sí mismo.\n$$\\alpha\\vec{u} + \\vec{v} \\in S$$\nPara calificar como tal, debe ser cerrado bajo la suma y el producto por escalar, lo que exige geométricamente que incluya al vector nulo. Rectas y planos por el origen son ejemplos clásicos.",
              "short_description": "Un **subespacio vectorial** es un subconjunto de un espacio mayor cerrado bajo sumas y productos escalares.\n$$\\alpha\\vec{u} + \\vec{v} \\in S$$",
              "skills": [
                "LEXI",
                "CLSF",
                "RESL"
              ]
            },
            {
              "key": "combinations",
              "name": "Combinaciones",
              "tooltip": "Una **combinación lineal** es el vector resultante de sumar un conjunto de vectores previamente multiplicados por escalares.\n$$\\vec{v} = c_1\\vec{v}_1 + c_2\\vec{v}_2 + \\dots + c_k\\vec{v}_k$$\nEs la forma fundamental de moverse dentro de un espacio vectorial: cada escalar dicta la intensidad del desplazamiento en la dirección de su vector correspondiente.",
              "short_description": "Una **combinación lineal** es la suma de vectores previamente multiplicados por coeficientes escalares.\n$$\\vec{v} = c_1\\vec{v}_1 + c_2\\vec{v}_2 + \\dots + c_k\\vec{v}_k$$",
              "skills": [
                "LEXI",
                "RESL"
              ]
            },
            {
              "key": "independence",
              "name": "Independencia",
              "tooltip": "Un conjunto de vectores es **linealmente independiente** si ninguno de ellos puede expresarse como combinación lineal del resto.\n$$c_1\\vec{v}_1 + \\dots + c_k\\vec{v}_k = \\vec{0} \\implies c_i = 0$$\nLa única forma de obtener el vector nulo es con coeficientes nulos. Asegura que cada vector aporta una nueva dimensión útil.",
              "short_description": "Un conjunto es **linealmente independiente** si ningún vector puede expresarse en función de los otros.\n$$c_1\\vec{v}_1 + \\dots + c_k\\vec{v}_k = \\vec{0} \\implies c_i = 0$$",
              "skills": [
                "LEXI",
                "CLSF",
                "RESL"
              ]
            },
            {
              "key": "generators",
              "name": "Generadores",
              "tooltip": "Un conjunto de **generadores** es un grupo de vectores cuyas combinaciones lineales permiten construir cualquier vector de un espacio dado.\n$$\\text{gen}(\\{\\vec{v}_1, \\dots, \\vec{v}_k\\}) = V$$\nAbarcan todo el subespacio, pero no necesariamente con eficiencia: pueden existir elementos redundantes que no comprometan el espacio cubierto.",
              "short_description": "Un conjunto de **generadores** es un grupo de vectores cuyas combinaciones generan todo un espacio.\n$$\\text{gen}(\\{\\vec{v}_1, \\dots, \\vec{v}_k\\}) = V$$",
              "skills": [
                "LEXI",
                "CLSF",
                "RESL"
              ]
            },
            {
              "key": "bases",
              "name": "Bases",
              "tooltip": "Una **base** es un conjunto de vectores que actúa como sistema de referencia óptimo: genera todo el espacio y es linealmente independiente.\n$$V = \\text{gen}(B) \\quad \\text{y} \\quad B \\text{ es L.I.}$$\nGarantiza que cualquier vector del espacio se escriba de forma única como combinación lineal de los vectores de la base.",
              "short_description": "Una **base** es un conjunto linealmente independiente que genera la totalidad de un espacio.\n$$V = \\text{gen}(B) \\quad \\text{y} \\quad B \\text{ es L.I.}$$",
              "skills": [
                "LEXI",
                "ESTR",
                "RESL"
              ]
            },
            {
              "key": "dimension",
              "name": "Dimensión",
              "tooltip": "La **dimensión** de un espacio vectorial es la cantidad exacta de vectores que contiene cualquiera de sus bases.\n$$\\dim(V) = n$$\nEs una propiedad intrínseca del espacio que representa sus grados de libertad. Aunque existan infinitas bases, todas poseen la misma cantidad de elementos.",
              "short_description": "La **dimensión** de un espacio vectorial es la cantidad de elementos que posee cualquiera de sus bases.\n$$\\dim(V) = n$$",
              "skills": [
                "LEXI",
                "CLSF",
                "RESL"
              ]
            }
          ]
        }
      ]
    }
  ]
}
