// AUTO-GENERATED by scripts/sync-catalog.ts.
// Source: backend/content/algebra/course.json
// Do not edit by hand; rerun `bun run scripts/sync-catalog.ts`.

export type BeltKey = "white" | "blue"

export interface Topic {
  key: string
  name: string
  tooltip: string
  short_description?: string
  skills: string[]
}

export interface Unit {
  key: string
  name: string
  description?: string
  topics: Topic[]
}

export interface Belt {
  key: BeltKey
  headline: string
  description: string
  units: Unit[]
}

export interface ExerciseType {
  id: string
  label: string
  description: string
}

export interface Catalog {
  slug: string
  name: string
  description: string
  belts: Belt[]
  exercise_types: ExerciseType[]
}

export const catalog: Catalog = {
  "slug": "algebra",
  "name": "Álgebra Lineal",
  "description": "Sistema de repaso adaptativo para Álgebra Lineal I",
  "exercise_types": [
    {
      "id": "LEXI",
      "label": "Léxico",
      "description": "Definiciones, vocabulario y notación del tema."
    },
    {
      "id": "CLSF",
      "label": "Clasificación",
      "description": "Reconocer y clasificar objetos, vectores, matrices o transformaciones."
    },
    {
      "id": "FORM",
      "label": "Formulación",
      "description": "Identificar y aplicar los componentes de una fórmula o ecuación."
    },
    {
      "id": "GRAF",
      "label": "Gráficos",
      "description": "Leer e interpretar información geométrica y representaciones en el plano y el espacio."
    },
    {
      "id": "ESTR",
      "label": "Estrategia",
      "description": "Elegir el método o las condiciones para resolver."
    },
    {
      "id": "RESL",
      "label": "Resolución",
      "description": "Calcular el resultado paso a paso."
    }
  ],
  "belts": [
    {
      "key": "white",
      "headline": "Vectores",
      "description": "Un **vector** es una herramienta matemática que modela magnitudes físicas con dirección y sentido. Su estudio en $\\mathbb{R}^n$ sienta las bases para comprender la geometría del espacio, la ortogonalidad y la construcción de sistemas de coordenadas independientes.\n$$\\vec{v} = (v_1, v_2, \\dots, v_n)$$\nEsta unidad recorre la definición de vectores, sus operaciones métricas y la representación de rectas y planos.",
      "units": [
        {
          "key": "vectors",
          "name": "Vectores",
          "description": "Un **vector** es un ente matemático que pertenece a un espacio $\\mathbb{R}^n$, definido por una tupla ordenada de componentes.\n$$\\vec{v} = (v_1, v_2, \\dots, v_n)$$\nEsta unidad introduce los conceptos fundamentales de geometría vectorial, operaciones, métricas y geometría analítica en el plano y el espacio.",
          "topics": [
            {
              "key": "definition",
              "name": "Definición",
              "tooltip": "Un **vector** es un ente matemático que pertenece a un espacio $\\mathbb{R}^n$, definido por una tupla ordenada de componentes.\n$$\\vec{v} = (v_1, v_2, \\dots, v_n)$$\nGeométricamente, en $\\mathbb{R}^2$ y $\\mathbb{R}^3$, modela magnitudes que poseen dirección y sentido, como desplazamientos o fuerzas. Constituye el objeto de estudio fundamental sobre el cual se construyen los espacios vectoriales.",
              "short_description": "Un **vector** es un ente matemático que pertenece a un espacio $\\mathbb{R}^n$, definido por una tupla ordenada de componentes.\n$$\\vec{v} = (v_1, v_2, \\dots, v_n)$$",
              "skills": [
                "LEXI",
                "CLSF"
              ]
            },
            {
              "key": "operations",
              "name": "Operaciones",
              "tooltip": "Las operaciones básicas entre vectores son la **suma** componente a componente y el **producto por un escalar**.\n$$\\alpha\\vec{v} = (\\alpha v_1, \\alpha v_2, \\dots, \\alpha v_n)$$\nEstas operaciones permiten escalar, invertir o combinar vectores geométricamente. Son las dos operaciones que estructuran axiomáticamente a cualquier espacio vectorial.",
              "short_description": "Las operaciones básicas entre vectores son la **suma** componente a componente y el **producto por un escalar**.\n$$\\alpha\\vec{v} = (\\alpha v_1, \\alpha v_2, \\dots, \\alpha v_n)$$",
              "skills": [
                "LEXI",
                "RESL"
              ]
            },
            {
              "key": "norm",
              "name": "Norma",
              "tooltip": "La **norma** o módulo de un vector cuantifica su longitud o magnitud en el espacio, calculada a partir de sus componentes.\n$$\\| \\vec{v} \\| = \\sqrt{v_1^2 + v_2^2 + \\dots + v_n^2}$$\nPermite definir conceptos métricos como la distancia entre dos puntos y la normalización de vectores, llevándolos a longitud unitaria sin alterar su dirección.",
              "short_description": "La **norma** o módulo de un vector cuantifica su longitud o magnitud en el espacio, calculada a partir de sus componentes.\n$$\\| \\vec{v} \\| = \\sqrt{v_1^2 + v_2^2 + \\dots + v_n^2}$$",
              "skills": [
                "LEXI",
                "RESL"
              ]
            },
            {
              "key": "scalar",
              "name": "Escalar",
              "tooltip": "La operación **escalar** (producto interno) toma dos vectores y devuelve un número real, vinculando sus magnitudes con el ángulo que forman.\n$$\\vec{u} \\cdot \\vec{v} = \\| \\vec{u} \\| \\| \\vec{v} \\| \\cos(\\theta)$$\nAlgebraicamente, se calcula sumando el producto de sus componentes homólogas. Es la herramienta principal para proyectar un vector sobre otro y analizar la relación angular.",
              "short_description": "La operación **escalar** (producto interno) toma dos vectores y devuelve un número real, vinculando sus magnitudes con el ángulo que forman.\n$$\\vec{u} \\cdot \\vec{v} = \\| \\vec{u} \\| \\| \\vec{v} \\| \\cos(\\theta)$$",
              "skills": [
                "LEXI",
                "RESL"
              ]
            },
            {
              "key": "orthogonality",
              "name": "Ortogonalidad",
              "tooltip": "Dos vectores son **ortogonales** si el ángulo entre ellos es recto, lo cual se verifica analíticamente cuando su producto escalar es nulo.\n$$\\vec{u} \\cdot \\vec{v} = 0$$\nEsta condición de perpendicularidad simplifica cálculos de proyecciones y es la base para construir sistemas de coordenadas independientes, donde el movimiento en una dirección no afecta a la otra.",
              "short_description": "Dos vectores son **ortogonales** si el ángulo entre ellos es recto, lo cual se verifica analíticamente cuando su producto escalar es nulo.\n$$\\vec{u} \\cdot \\vec{v} = 0$$",
              "skills": [
                "LEXI",
                "CLSF",
                "RESL"
              ]
            },
            {
              "key": "product",
              "name": "Producto",
              "tooltip": "El **producto** vectorial es una operación exclusiva de $\\mathbb{R}^3$ que toma dos vectores y devuelve un tercer vector, perpendicular a ambos.\n$$\\vec{w} = \\vec{u} \\times \\vec{v}$$\nLa norma de este nuevo vector equivale al área del paralelogramo que forman los vectores originales. Se utiliza habitualmente para hallar vectores normales a planos.",
              "short_description": "El **producto** vectorial es una operación exclusiva de $\\mathbb{R}^3$ que toma dos vectores y devuelve un tercer vector, perpendicular a ambos.\n$$\\vec{w} = \\vec{u} \\times \\vec{v}$$",
              "skills": [
                "LEXI",
                "RESL"
              ]
            },
            {
              "key": "lines",
              "name": "Rectas",
              "tooltip": "Una **recta** en el espacio queda determinada unívocamente por un punto de paso y un vector director que marca su orientación.\n$$L: \\vec{x} = \\vec{p} + t\\vec{d}$$\nAl variar el parámetro escalar $t$, se recorren todos los puntos que pertenecen a la recta, generando un subespacio unidimensional desplazado desde el origen.",
              "short_description": "Una **recta** en el espacio queda determinada unívocamente por un punto de paso y un vector director que marca su orientación.\n$$L: \\vec{x} = \\vec{p} + t\\vec{d}$$",
              "skills": [
                "LEXI",
                "FORM",
                "GRAF",
                "RESL"
              ]
            },
            {
              "key": "planes",
              "name": "Planos",
              "tooltip": "Un **plano** en el espacio requiere un punto de paso y un vector normal que define su inclinación respecto a los ejes.\n$$\\pi: \\vec{n} \\cdot (\\vec{x} - \\vec{p}) = 0$$\nLa ecuación refleja que cualquier vector contenido dentro del plano es ortogonal al vector normal. Las intersecciones entre planos modelan geométricamente los sistemas de ecuaciones.",
              "short_description": "Un **plano** en el espacio requiere un punto de paso y un vector normal que define su inclinación respecto a los ejes.\n$$\\pi: \\vec{n} \\cdot (\\vec{x} - \\vec{p}) = 0$$",
              "skills": [
                "LEXI",
                "FORM",
                "RESL"
              ]
            }
          ]
        }
      ]
    },
    {
      "key": "blue",
      "headline": "Matrices",
      "description": "Una **matriz** organiza coeficientes y variables en estructuras rectangulares, funcionando como el núcleo de los sistemas de ecuaciones lineales y como operadores que transforman el espacio a través de rotaciones, proyecciones e inversiones.\n$$A \\in \\mathbb{R}^{m \\times n}$$\nEsta unidad introduce la definición, operaciones, determinantes, matrices inversas y sistemas de ecuaciones lineales.",
      "units": [
        {
          "key": "matrices",
          "name": "Matrices",
          "description": "Una **matriz** es un arreglo rectangular de escalares dispuestos en filas y columnas.\n$$A \\in \\mathbb{R}^{m \\times n}$$\nEsta unidad abarca el álgebra matricial, los determinantes, la inversión de matrices y los métodos para resolver sistemas lineales.",
          "topics": [
            {
              "key": "definition",
              "name": "Definición",
              "tooltip": "Una **matriz** es un arreglo rectangular de escalares dispuestos en filas y columnas.\n$$A \\in \\mathbb{R}^{m \\times n}$$\nFunciona como una estructura de datos para organizar coeficientes de sistemas de ecuaciones y como el operador matemático que aplica transformaciones lineales sobre vectores.",
              "short_description": "Una **matriz** es un arreglo rectangular de escalares dispuestos en filas y columnas.\n$$A \\in \\mathbb{R}^{m \\times n}$$",
              "skills": [
                "LEXI",
                "CLSF"
              ]
            },
            {
              "key": "operations",
              "name": "Operaciones",
              "tooltip": "La suma de matrices se realiza elemento a elemento, mientras que el **producto matricial** combina las filas de la primera con las columnas de la segunda.\n$$C_{ij} = \\sum_{k=1}^n A_{ik}B_{kj}$$\nA diferencia del producto de números reales, la multiplicación de matrices no es conmutativa. El orden de los factores altera el resultado, reflejando transformaciones secuenciales.",
              "short_description": "La suma de matrices se realiza elemento a elemento, mientras que el **producto matricial** combina las filas de la primera con las columnas de la segunda.\n$$C_{ij} = \\sum_{k=1}^n A_{ik}B_{kj}$$",
              "skills": [
                "LEXI",
                "RESL"
              ]
            },
            {
              "key": "transpose",
              "name": "Transpuesta",
              "tooltip": "La **matriz transpuesta** se obtiene intercambiando las filas por las columnas de la matriz original.\n$$(A^T)_{ij} = A_{ji}$$\nSi una matriz es igual a su transpuesta, se clasifica como simétrica. Esta operación conserva la diagonal principal inalterada e invierte el orden en el caso del producto matricial.",
              "short_description": "La **matriz transpuesta** se obtiene intercambiando las filas por las columnas de la matriz original.\n$$(A^T)_{ij} = A_{ji}$$",
              "skills": [
                "LEXI",
                "RESL"
              ]
            },
            {
              "key": "determinants",
              "name": "Determinantes",
              "tooltip": "El **determinante** es un escalar asociado a una matriz cuadrada que indica, entre otras propiedades, si el sistema tiene solución única.\n$$\\det(A) \\neq 0 \\iff \\text{Inversible}$$\nGeométricamente, representa el factor por el cual la matriz expande o contrae el volumen en el espacio. Si el determinante es cero, la transformación colapsa el espacio.",
              "short_description": "El **determinante** es un escalar asociado a una matriz cuadrada que indica si la matriz es inversible.\n$$\\det(A) \\neq 0 \\iff \\text{Inversible}$$",
              "skills": [
                "LEXI",
                "RESL"
              ]
            },
            {
              "key": "inverse",
              "name": "Inversa",
              "tooltip": "La **matriz inversa** es aquella que, al multiplicarse por la matriz original, da como resultado la matriz identidad.\n$$A A^{-1} = A^{-1} A = I$$\nFunciona como la operación de división en el álgebra matricial, deshaciendo la transformación aplicada por la matriz original. Solo existe para matrices cuadradas de determinante no nulo.",
              "short_description": "La **matriz inversa** es aquella que, al multiplicarse por la matriz original, da como resultado la matriz identidad.\n$$A A^{-1} = A^{-1} A = I$$",
              "skills": [
                "LEXI",
                "RESL"
              ]
            },
            {
              "key": "systems",
              "name": "Sistemas",
              "tooltip": "Un **sistema de ecuaciones lineales** puede expresarse de forma compacta mediante una ecuación matricial.\n$$A\\vec{x} = \\vec{b}$$\nAquí, la matriz concentra los coeficientes, el vector agrupa las incógnitas y el segundo vector representa los términos independientes. Permite abordar sistemas lineales de forma global.",
              "short_description": "Un **sistema de ecuaciones lineales** puede expresarse de forma compacta mediante una ecuación matricial.\n$$A\\vec{x} = \\vec{b}$$",
              "skills": [
                "LEXI",
                "CLSF",
                "FORM",
                "RESL"
              ]
            },
            {
              "key": "elimination",
              "name": "Eliminación",
              "tooltip": "La **eliminación de Gauss** es un algoritmo sistemático que transforma la matriz de un sistema en una forma escalonada mediante operaciones por fila.\n$$\\begin{pmatrix} A | \\vec{b} \\end{pmatrix} \\to \\begin{pmatrix} U | \\vec{c} \\end{pmatrix}$$\nEl proceso preserva el conjunto de soluciones del sistema original mientras despeja progresivamente las variables, facilitando su resolución mediante sustitución inversa.",
              "short_description": "La **eliminación de Gauss** es un algoritmo que transforma la matriz en una forma escalonada mediante operaciones por fila.\n$$\\begin{pmatrix} A | \\vec{b} \\end{pmatrix} \\to \\begin{pmatrix} U | \\vec{c} \\end{pmatrix}$$",
              "skills": [
                "LEXI",
                "ESTR",
                "RESL"
              ]
            }
          ]
        }
      ]
    }
  ]
}
