// AUTO-GENERATED by scripts/sync-catalog.ts.
// Source: backend/content/algebra/course.json
// Do not edit by hand; rerun `bun run scripts/sync-catalog.ts`.

export type BeltKey = "white" | "blue" | "violet" | "brown"

export interface Topic {
  key: string
  name: string
  tooltip: string
  short_description?: string
  skills: string[]
}

export interface Unit {
  key: string
  name: string
  description?: string
  topics: Topic[]
}

export interface Belt {
  key: BeltKey
  headline: string
  description: string
  units: Unit[]
}

export interface ExerciseType {
  id: string
  label: string
  description: string
}

export interface Catalog {
  slug: string
  name: string
  description: string
  belts: Belt[]
  exercise_types: ExerciseType[]
}

export const catalog: Catalog = {
  "slug": "algebra",
  "name": "Álgebra Lineal",
  "description": "Sistema de repaso adaptativo para Álgebra Lineal I",
  "exercise_types": [
    {
      "id": "LEXI",
      "label": "Léxico",
      "description": "Definiciones, vocabulario y notación del tema."
    },
    {
      "id": "CLSF",
      "label": "Clasificación",
      "description": "Reconocer y clasificar objetos, vectores, matrices o transformaciones."
    },
    {
      "id": "FORM",
      "label": "Formulación",
      "description": "Identificar y aplicar los componentes de una fórmula o ecuación."
    },
    {
      "id": "GRAF",
      "label": "Gráficos",
      "description": "Leer e interpretar información geométrica y representaciones en el plano y el espacio."
    },
    {
      "id": "ESTR",
      "label": "Planteo",
      "description": "Elegir el método o las condiciones para resolver."
    },
    {
      "id": "RESL",
      "label": "Resolución",
      "description": "Calcular el resultado paso a paso."
    }
  ],
  "belts": [
    {
      "key": "white",
      "headline": "Aritmética",
      "description": "Las **operaciones aritméticas** fundamentales (fracciones, potencias, raíces, logaritmos, signos) son la base operativa sobre la que se apoya el resto del álgebra.",
      "units": [
        {
          "key": "aritmetica",
          "name": "Aritmética",
          "description": "Las **operaciones aritméticas fundamentales** (fracciones, potencias, radicales, logaritmos, notación, valor absoluto y propiedades algebraicas básicas) son la base operativa sobre la que se apoya el resto del álgebra.\n$$\\frac{a}{b}, \\quad a^n, \\quad \\sqrt[n]{a}$$\nDominarlas evita que un error de cálculo bloquee el razonamiento en temas más avanzados.",
          "topics": [
            {
              "key": "fracciones",
              "name": "Fracciones",
              "tooltip": "Una **fracción** $\\frac{a}{b}$ representa una parte de un todo o una razón entre dos cantidades.\n$$\\frac{a}{b} \\cdot \\frac{c}{d} = \\frac{a \\cdot c}{b \\cdot d}$$\nMás allá de la mecánica de sumar y multiplicar, dominar fracciones compuestas, el signo y la comparación sin pasar a decimales evita errores que se arrastran a matrices y sistemas.",
              "short_description": "Las **fracciones** representan una parte de un todo o una razón entre cantidades.\n$$\\frac{a}{b} \\cdot \\frac{c}{d} = \\frac{a \\cdot c}{b \\cdot d}$$",
              "skills": [
                "LEXI",
                "ESTR",
                "RESL"
              ]
            },
            {
              "key": "powers",
              "name": "Potenciación",
              "tooltip": "La **potenciación** $a^n$ representa la multiplicación repetida de una base $a$ por sí misma $n$ veces.\n$$a^m \\cdot a^n = a^{m+n}, \\quad a^{-n} = \\frac{1}{a^n}$$\nSus propiedades (producto y cociente de potencias de igual base, potencia de potencia, exponente negativo y fraccionario) son la herramienta operativa detrás de toda la notación algebraica posterior.",
              "short_description": "Las **propiedades de la potenciación** permiten operar exponentes sin desarrollar la multiplicación completa.\n$$a^m \\cdot a^n = a^{m+n}$$",
              "skills": [
                "LEXI",
                "RESL",
                "FORM"
              ]
            },
            {
              "key": "radicals",
              "name": "Radicales",
              "tooltip": "La **raíz enésima** $\\sqrt[n]{a}$ es la operación inversa de elevar a la potencia $n$.\n$$\\sqrt[n]{a} = a^{1/n}$$\nSimplificar radicales y racionalizar denominadores, eliminar raíces del denominador multiplicando por un factor adecuado, evita arrastrar expresiones irracionales innecesarias en los cálculos.",
              "short_description": "La **raíz enésima** es la operación inversa de la potenciación.\n$$\\sqrt[n]{a} = a^{1/n}$$",
              "skills": [
                "LEXI",
                "RESL",
                "FORM"
              ]
            },
            {
              "key": "logarithms",
              "name": "Logaritmos",
              "tooltip": "El **logaritmo** en base $b$ de un número $x$ es el exponente al que hay que elevar $b$ para obtener $x$.\n$$\\log_b(x) = y \\iff b^y = x$$\nSus propiedades operativas (logaritmo de un producto, un cociente y una potencia) permiten simplificar cálculos antes de que aparezca la función logarítmica como objeto en sí.",
              "short_description": "El **logaritmo** en base $b$ de $x$ es el exponente al que se eleva $b$ para obtener $x$.\n$$\\log_b(x) = y \\iff b^y = x$$",
              "skills": [
                "LEXI",
                "RESL",
                "FORM"
              ]
            },
            {
              "key": "scientific_notation",
              "name": "Notación",
              "tooltip": "La **notación científica** expresa cualquier número como el producto de un valor entre $1$ y $10$ por una potencia de $10$.\n$$a \\times 10^n, \\quad 1 \\leq |a| < 10$$\nFacilita operar con cantidades extremadamente grandes o pequeñas sin escribir todos los ceros, y es el formato estándar en ciencias e ingeniería.",
              "short_description": "La **notación científica** expresa un número como $a \\times 10^n$ con $1 \\leq |a| < 10$.\n$$a \\times 10^n$$",
              "skills": [
                "RESL",
                "FORM"
              ]
            },
            {
              "key": "absolute_value",
              "name": "Absoluto",
              "tooltip": "El **valor absoluto** $|a|$ de un número mide su distancia al cero en la recta numérica, sin importar el signo.\n$$|a| = \\begin{cases} a & \\text{si } a \\geq 0 \\\\ -a & \\text{si } a < 0 \\end{cases}$$\nAparece constantemente al resolver ecuaciones e inecuaciones, y su propiedad clave es que siempre devuelve un resultado no negativo.",
              "short_description": "El **valor absoluto** mide la distancia de un número al cero, siempre con resultado no negativo.\n$$|{-5}| = 5$$",
              "skills": [
                "RESL",
                "FORM"
              ]
            }
          ]
        }
      ]
    },
    {
      "key": "blue",
      "headline": "Vectores",
      "description": "Un **vector** en el plano o el espacio es una magnitud con dirección y sentido, representable como un segmento orientado o como una lista de componentes.\n$$\\vec{v} = (v_1, v_2, v_3)$$\nSus operaciones y propiedades son la base de las matrices y las transformaciones lineales.",
      "units": [
        {
          "key": "vectors",
          "name": "Vectores",
          "description": "Un **vector** es un ente matemático que pertenece a un espacio $\\mathbb{R}^n$, definido por una tupla ordenada de componentes.\n$$\\vec{v} = (v_1, v_2, \\dots, v_n)$$\nEsta unidad introduce los conceptos fundamentales de geometría vectorial, operaciones, métricas y geometría analítica en el plano y el espacio.",
          "topics": [
            {
              "key": "definition",
              "name": "Definición",
              "tooltip": "Un **vector** es un ente matemático que pertenece a un espacio $\\mathbb{R}^n$, definido por una tupla ordenada de componentes.\n$$\\vec{v} = (v_1, v_2, \\dots, v_n)$$\nGeométricamente, en $\\mathbb{R}^2$ y $\\mathbb{R}^3$, modela magnitudes que poseen dirección y sentido, como desplazamientos o fuerzas. Constituye el objeto de estudio fundamental sobre el cual se construyen los espacios vectoriales.",
              "short_description": "Un **vector** es un ente matemático que pertenece a un espacio $\\mathbb{R}^n$, definido por una tupla ordenada de componentes.\n$$\\vec{v} = (v_1, v_2, \\dots, v_n)$$",
              "skills": [
                "LEXI",
                "FORM"
              ]
            },
            {
              "key": "operations",
              "name": "Operaciones",
              "tooltip": "Las operaciones básicas entre vectores son la **suma** componente a componente y el **producto por un escalar**.\n$$\\alpha\\vec{v} = (\\alpha v_1, \\alpha v_2, \\dots, \\alpha v_n)$$\nEstas operaciones permiten escalar, invertir o combinar vectores geométricamente. Son las dos operaciones que estructuran axiomáticamente a cualquier espacio vectorial.",
              "short_description": "Las operaciones básicas entre vectores son la **suma** componente a componente y el **producto por un escalar**.\n$$\\alpha\\vec{v} = (\\alpha v_1, \\alpha v_2, \\dots, \\alpha v_n)$$",
              "skills": [
                "FORM",
                "RESL"
              ]
            },
            {
              "key": "norm",
              "name": "Norma",
              "tooltip": "La **norma** o módulo de un vector cuantifica su longitud o magnitud en el espacio, calculada a partir de sus componentes.\n$$\\| \\vec{v} \\| = \\sqrt{v_1^2 + v_2^2 + \\dots + v_n^2}$$\nPermite definir conceptos métricos como la distancia entre dos puntos y la normalización de vectores, llevándolos a longitud unitaria sin alterar su dirección.",
              "short_description": "La **norma** o módulo de un vector cuantifica su longitud o magnitud en el espacio, calculada a partir de sus componentes.\n$$\\| \\vec{v} \\| = \\sqrt{v_1^2 + v_2^2 + \\dots + v_n^2}$$",
              "skills": [
                "LEXI",
                "RESL"
              ]
            },
            {
              "key": "scalar",
              "name": "Escalar",
              "tooltip": "La operación **escalar** (producto interno) toma dos vectores y devuelve un número real, vinculando sus magnitudes con el ángulo que forman.\n$$\\vec{u} \\cdot \\vec{v} = \\| \\vec{u} \\| \\| \\vec{v} \\| \\cos(\\theta)$$\nAlgebraicamente, se calcula sumando el producto de sus componentes homólogas. Es la herramienta principal para proyectar un vector sobre otro y analizar la relación angular.",
              "short_description": "La operación **escalar** (producto interno) toma dos vectores y devuelve un número real, vinculando sus magnitudes con el ángulo que forman.\n$$\\vec{u} \\cdot \\vec{v} = \\| \\vec{u} \\| \\| \\vec{v} \\| \\cos(\\theta)$$",
              "skills": [
                "LEXI",
                "CLSF",
                "RESL"
              ]
            },
            {
              "key": "orthogonality",
              "name": "Ortogonalidad",
              "tooltip": "Dos vectores son **ortogonales** si el ángulo entre ellos es recto, lo cual se verifica analíticamente cuando su producto escalar es nulo.\n$$\\vec{u} \\cdot \\vec{v} = 0$$\nEsta condición de perpendicularidad simplifica cálculos de proyecciones y es la base para construir sistemas de coordenadas independientes, donde el movimiento en una dirección no afecta a la otra.",
              "short_description": "Dos vectores son **ortogonales** si el ángulo entre ellos es recto, lo cual se verifica analíticamente cuando su producto escalar es nulo.\n$$\\vec{u} \\cdot \\vec{v} = 0$$",
              "skills": [
                "LEXI",
                "CLSF",
                "RESL"
              ]
            },
            {
              "key": "product",
              "name": "Producto",
              "tooltip": "El **producto** vectorial es una operación exclusiva de $\\mathbb{R}^3$ que toma dos vectores y devuelve un tercer vector, perpendicular a ambos.\n$$\\vec{w} = \\vec{u} \\times \\vec{v}$$\nLa norma de este nuevo vector equivale al área del paralelogramo que forman los vectores originales. Se utiliza habitualmente para hallar vectores normales a planos.",
              "short_description": "El **producto** vectorial es una operación exclusiva de $\\mathbb{R}^3$ que toma dos vectores y devuelve un tercer vector, perpendicular a ambos.\n$$\\vec{w} = \\vec{u} \\times \\vec{v}$$",
              "skills": [
                "LEXI",
                "CLSF"
              ]
            }
          ]
        }
      ]
    },
    {
      "key": "violet",
      "headline": "Matrices",
      "description": "Una **matriz** organiza números en filas y columnas para representar sistemas de ecuaciones y transformaciones lineales de forma compacta.\n$$A \\in \\mathbb{R}^{m \\times n}$$\nSus operaciones, determinante e inversa permiten resolver sistemas y estudiar la estructura del espacio que la matriz transforma.",
      "units": [
        {
          "key": "matrices",
          "name": "Matrices",
          "description": "Una **matriz** es un arreglo rectangular de escalares dispuestos en filas y columnas.\n$$A \\in \\mathbb{R}^{m \\times n}$$\nEsta unidad abarca el álgebra matricial, los determinantes, la inversión de matrices y los métodos para resolver sistemas lineales.",
          "topics": [
            {
              "key": "definition",
              "name": "Definición",
              "tooltip": "Una **matriz** es un arreglo rectangular de escalares dispuestos en filas y columnas.\n$$A \\in \\mathbb{R}^{m \\times n}$$\nOrganiza datos en forma de tabla, pero sobre todo describe una transformación: cada columna registra en qué se convierte una de las direcciones básicas del espacio.",
              "short_description": "Una **matriz** es un arreglo rectangular de escalares dispuestos en filas y columnas.\n$$A \\in \\mathbb{R}^{m \\times n}$$",
              "skills": [
                "LEXI",
                "CLSF",
                "FORM"
              ]
            },
            {
              "key": "operations",
              "name": "Operaciones",
              "tooltip": "La **suma de matrices** y el **producto por un escalar** se calculan entrada a entrada, y solo tienen sentido entre matrices del mismo orden.\n$$(A+B)_{ij} = A_{ij} + B_{ij}$$\nHeredan de los números reales la conmutatividad y la asociatividad, porque cada posición se opera por separado y sin interferir con las demás.",
              "short_description": "La **suma de matrices** y el **producto por un escalar** se calculan entrada a entrada.\n$$(A+B)_{ij} = A_{ij} + B_{ij}$$",
              "skills": [
                "LEXI",
                "RESL",
                "FORM"
              ]
            },
            {
              "key": "product",
              "name": "Producto",
              "tooltip": "El **producto matricial** combina cada fila de la primera matriz con cada columna de la segunda, y solo está definido si las dimensiones encajan.\n$$C_{ij} = \\sum_{k=1}^n A_{ik}B_{kj}$$\nA diferencia del producto de números, el orden de los factores altera el resultado: multiplicar matrices es encadenar transformaciones, y encadenarlas al revés lleva a otro lado.",
              "short_description": "El **producto matricial** combina cada fila de la primera matriz con cada columna de la segunda.\n$$C_{ij} = \\sum_{k=1}^n A_{ik}B_{kj}$$",
              "skills": [
                "LEXI",
                "CLSF",
                "RESL"
              ]
            },
            {
              "key": "determinants",
              "name": "Determinantes",
              "tooltip": "El **determinante** es un número asociado a una matriz cuadrada que mide cuánto agranda o achica las áreas que transforma.\n$$\\det\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix} = ad - bc$$\nUn signo negativo indica que la orientación se invirtió, y un determinante nulo indica que la transformación aplasta el espacio contra una recta.",
              "short_description": "El **determinante** mide cuánto agranda o achica las áreas la transformación de una matriz cuadrada.\n$$\\det\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix} = ad - bc$$",
              "skills": [
                "LEXI",
                "CLSF",
                "RESL"
              ]
            },
            {
              "key": "inverse",
              "name": "Inversa",
              "tooltip": "La **matriz inversa** es la que deshace exactamente lo que hizo la original, devolviendo la matriz identidad.\n$$A A^{-1} = A^{-1} A = I$$\nCumple el papel que la división cumple entre números, pero solo existe cuando el determinante no es nulo: una transformación que aplastó el espacio ya no se puede revertir.",
              "short_description": "La **matriz inversa** es la que deshace la transformación original y devuelve la identidad.\n$$A A^{-1} = A^{-1} A = I$$",
              "skills": [
                "LEXI",
                "CLSF",
                "RESL"
              ]
            },
            {
              "key": "systems",
              "name": "Sistemas",
              "tooltip": "Un **sistema de ecuaciones lineales** se escribe de forma compacta como una matriz de coeficientes multiplicada por el vector de incógnitas.\n$$AX = B$$\nEscalonar la matriz ampliada permite clasificar el sistema en compatible determinado, compatible indeterminado o incompatible, sin despejar cada incógnita por separado.",
              "short_description": "Un **sistema de ecuaciones lineales** se escribe de forma compacta como una ecuación matricial.\n$$AX = B$$",
              "skills": [
                "FORM",
                "CLSF",
                "RESL"
              ]
            }
          ]
        }
      ]
    },
    {
      "key": "brown",
      "headline": "Espacios",
      "description": "Un **espacio vectorial** es un conjunto donde sumar dos elementos o multiplicar uno por un número nunca saca del conjunto.\n$$\\alpha\\vec{u} + \\vec{v} \\in V$$\nEsta unidad formaliza los subespacios, el conjunto generado, la independencia lineal, las bases y la dimensión.",
      "units": [
        {
          "key": "spaces",
          "name": "Espacios",
          "description": "Un espacio vectorial es un conjunto donde sumar dos elementos o multiplicar uno por un número nunca saca del conjunto.\n$$\\alpha\\vec{u} + \\vec{v} \\in V$$\nEsta unidad formaliza los subespacios, el conjunto generado, la independencia, las bases y la dimensión.",
          "topics": [
            {
              "key": "definition",
              "name": "Definición",
              "tooltip": "Un **espacio vectorial** es un conjunto donde sumar dos elementos o multiplicar uno por un número nunca saca del conjunto.\n$$\\vec{u}+\\vec{v} \\in V, \\quad \\alpha\\vec{v} \\in V$$\n$\\mathbb{R}^2$ y $\\mathbb{R}^3$ son los ejemplos conocidos, pero los polinomios y las matrices cumplen las mismas reglas, y por eso todo lo que valga para uno vale para los otros.",
              "short_description": "Un **espacio vectorial** es un conjunto donde sumar dos elementos o multiplicar uno por un número nunca saca del conjunto.\n$$\\vec{u}+\\vec{v} \\in V, \\quad \\alpha\\vec{v} \\in V$$",
              "skills": [
                "LEXI",
                "CLSF",
                "RESL"
              ]
            },
            {
              "key": "subspaces",
              "name": "Subespacios",
              "tooltip": "Un **subespacio** es un subconjunto que se comporta como un espacio vectorial por sí solo.\n$$\\alpha\\vec{u} + \\vec{v} \\in S$$\nTiene que ser cerrado bajo la suma y el producto por escalar, y eso obliga a que contenga al vector nulo. Las rectas y los planos que pasan por el origen son el caso típico.",
              "short_description": "Un **subespacio** es un subconjunto cerrado bajo la suma y el producto por escalar.\n$$\\alpha\\vec{u} + \\vec{v} \\in S$$",
              "skills": [
                "LEXI",
                "CLSF",
                "RESL"
              ]
            },
            {
              "key": "generators",
              "name": "Generadores",
              "tooltip": "El **conjunto generado** por unos vectores reúne todas sus combinaciones lineales, y describe hasta dónde se puede llegar con ellos.\n$$\\text{gen}\\{\\vec{v}_1, \\dots, \\vec{v}_k\\} = V$$\nUn conjunto generador cubre todo el espacio, pero no necesariamente sin desperdicio: puede tener vectores de más que no agregan ningún alcance nuevo.",
              "short_description": "Un **conjunto generador** es un grupo de vectores cuyas combinaciones lineales cubren todo el espacio.\n$$\\text{gen}\\{\\vec{v}_1, \\dots, \\vec{v}_k\\} = V$$",
              "skills": [
                "LEXI",
                "CLSF",
                "RESL"
              ]
            },
            {
              "key": "independence",
              "name": "Independencia",
              "tooltip": "Un conjunto es **linealmente independiente** cuando ninguno de sus vectores se puede armar combinando los otros, o sea cuando ninguno sobra.\n$$\\alpha_1\\vec{v}_1 + \\dots + \\alpha_k\\vec{v}_k = \\vec{0} \\implies \\alpha_i = 0$$\nEsa igualdad es la versión que se calcula: la única manera de llegar al vector nulo es con todos los coeficientes en cero.",
              "short_description": "Un conjunto es **linealmente independiente** cuando ninguno de sus vectores se puede armar combinando los otros.\n$$\\alpha_1\\vec{v}_1 + \\dots + \\alpha_k\\vec{v}_k = \\vec{0} \\implies \\alpha_i = 0$$",
              "skills": [
                "LEXI",
                "CLSF",
                "RESL"
              ]
            },
            {
              "key": "bases",
              "name": "Bases",
              "tooltip": "Una **base** es un conjunto que genera todo el espacio y además es linealmente independiente: no falta ninguno y no sobra ninguno.\n$$B = \\{\\vec{v}_1, \\dots, \\vec{v}_n\\}$$\nEsa doble condición es la que hace que cada vector del espacio se escriba de una única manera, y por eso una base funciona como sistema de referencia.",
              "short_description": "Una **base** es un conjunto linealmente independiente que además genera todo el espacio.\n$$B = \\{\\vec{v}_1, \\dots, \\vec{v}_n\\}$$",
              "skills": [
                "LEXI",
                "ESTR",
                "RESL"
              ]
            },
            {
              "key": "dimension",
              "name": "Dimensión",
              "tooltip": "La **dimensión** de un espacio es la cantidad de vectores que tiene cualquiera de sus bases.\n$$\\dim(V) = n$$\nQue ese número no dependa de la base elegida es lo que lo vuelve una propiedad del espacio. Por eso los polinomios de grado hasta dos, que tienen dimensión tres, se comportan igual que $\\mathbb{R}^3$.",
              "short_description": "La **dimensión** de un espacio es la cantidad de vectores que tiene cualquiera de sus bases.\n$$\\dim(V) = n$$",
              "skills": [
                "LEXI",
                "CLSF",
                "RESL"
              ]
            }
          ]
        }
      ]
    }
  ]
}
