// AUTO-GENERATED by scripts/sync-catalog.ts.
// Source: backend/content/analisis/course.json
// Do not edit by hand; rerun `bun run scripts/sync-catalog.ts`.

export type BeltKey = "white" | "blue" | "violet" | "brown"

export interface Topic {
  key: string
  name: string
  tooltip: string
  short_description?: string
  skills: string[]
}

export interface Unit {
  key: string
  name: string
  topics: Topic[]
}

export interface Belt {
  key: BeltKey
  headline: string
  description: string
  units: Unit[]
}

export interface ExerciseType {
  id: string
  label: string
  description: string
}

export interface Catalog {
  slug: string
  name: string
  description: string
  belts: Belt[]
  exercise_types: ExerciseType[]
}

export const catalog: Catalog = {
  "slug": "analisis",
  "name": "Análisis",
  "description": "Sistema de repaso adaptativo para Análisis Matemático I",
  "exercise_types": [
    {
      "id": "LEXI",
      "label": "Léxico",
      "description": "Definiciones, vocabulario y notación del tema."
    },
    {
      "id": "CLSF",
      "label": "Clasificación",
      "description": "Reconocer y clasificar funciones, puntos o casos."
    },
    {
      "id": "FORM",
      "label": "Formulación",
      "description": "Identificar y aplicar los componentes de una fórmula."
    },
    {
      "id": "GRAF",
      "label": "Gráficos",
      "description": "Leer e interpretar información en gráficos."
    },
    {
      "id": "ESTR",
      "label": "Estrategia",
      "description": "Elegir el método o las condiciones para resolver."
    },
    {
      "id": "RESL",
      "label": "Resolución",
      "description": "Calcular el resultado paso a paso."
    }
  ],
  "belts": [
    {
      "key": "white",
      "headline": "Funciones",
      "description": "Una función es una relación que asigna a cada elemento de un conjunto de partida o **dominio**, un único elemento de un conjunto de llegada o **codominio**.\n$$f : X \\to Y, \\quad y = f(x)$$\nEsta relación permite modelar la **dependencia** entre variables y hace posible el **análisis** de su comportamiento a través de límites, derivadas e integrales.",
      "units": [
        {
          "key": "functions",
          "name": "Funciones",
          "topics": [
            {
              "key": "definition",
              "name": "Definición",
              "tooltip": "Una **función** es una relación que asigna a cada elemento de un conjunto de partida o **dominio**, un único elemento de un conjunto de llegada o **codominio**.\n$$f : X \\to Y, \\quad y = f(x)$$\nLa condición necesaria para esta relación es la **unicidad**, cada valor de entrada se transforma en una y solo una salida.",
              "short_description": "Una **función** es una relación que asigna a cada elemento de un conjunto de partida o **dominio**, un único elemento de un conjunto de llegada o **codominio**.\n$$f : X \\to Y, \\quad y = f(x)$$",
              "skills": [
                "LEXI",
                "CLSF"
              ]
            },
            {
              "key": "linear",
              "name": "Funciones lineales",
              "tooltip": "Una **función lineal** es aquella que puede expresarse como un polinomio de primer grado.\n$$f(x) = mx + b$$\nLa representación gráfica de esta relación en el plano cartesiano es siempre una línea recta, lo que refleja una tasa de cambio constante entre sus variables.",
              "short_description": "Una **función lineal** es aquella que puede expresarse como un polinomio de primer grado.\n$$f(x) = mx + b$$",
              "skills": [
                "LEXI",
                "CLSF",
                "FORM",
                "GRAF"
              ]
            },
            {
              "key": "quadratic",
              "name": "Funciones cuadráticas",
              "tooltip": "Una **función cuadrática** es aquella que puede expresarse como un polinomio de segundo grado.\n$$f(x) = ax^2 + bx + c$$\nLa representación gráfica de esta relación en el plano cartesiano es una curva simétrica conocida como **parábola**.",
              "short_description": "Una **función cuadrática** es aquella que puede expresarse como un polinomio de segundo grado.\n$$f(x) = ax^2 + bx + c$$",
              "skills": [
                "LEXI",
                "CLSF",
                "FORM",
                "GRAF"
              ]
            },
            {
              "key": "polynomial",
              "name": "Funciones polinómicas",
              "tooltip": "Una **función polinómica** es aquella que puede expresarse como un polinomio de grado $n$, generalización que incluye a las funciones lineales y cuadráticas.\n$$f(x) = a_nx^n + a_{n-1}x^{n-1} + \\cdots + a_1x + a_0$$\nLa representación gráfica de esta relación en el plano cartesiano es siempre una curva suave y continua.",
              "short_description": "Una **función polinómica** es aquella que puede expresarse como un polinomio de grado $n$, generalización que incluye a las funciones lineales y cuadráticas.\n$$f(x) = a_nx^n + a_{n-1}x^{n-1} + \\cdots + a_1x + a_0$$",
              "skills": [
                "LEXI",
                "CLSF",
                "FORM",
                "GRAF"
              ]
            },
            {
              "key": "exponential",
              "name": "Funciones exponenciales",
              "tooltip": "Una **función exponencial** es aquella en la que la variable independiente aparece como exponente de una base constante.\n$$f(x) = a^x$$\nLa representación gráfica de esta relación en el plano cartesiano es una curva continua que refleja un ritmo de crecimiento o decaimiento sumamente rápido.",
              "short_description": "Una **función exponencial** es aquella en la que la variable independiente aparece como exponente de una base constante.\n$$f(x) = a^x$$",
              "skills": [
                "LEXI",
                "CLSF",
                "FORM",
                "GRAF"
              ]
            },
            {
              "key": "logarithmic",
              "name": "Funciones logarítmicas",
              "tooltip": "Una **función logarítmica** es aquella en la que la variable independiente aparece como el argumento de un logaritmo de base constante.\n$$f(x) = \\log_a(x)$$\nLa representación gráfica de esta relación en el plano cartesiano es una curva continua que refleja un ritmo de crecimiento o decaimiento sumamente gradual.",
              "short_description": "Una **función logarítmica** es aquella en la que la variable independiente aparece como el argumento de un logaritmo de base constante.\n$$f(x) = \\log_a(x)$$",
              "skills": [
                "LEXI",
                "CLSF",
                "FORM",
                "GRAF"
              ]
            },
            {
              "key": "rational",
              "name": "Funciones racionales",
              "tooltip": "Una **función racional** es aquella que puede expresarse como el cociente o división entre dos polinomios.\n$$f(x) = \\frac{P(x)}{Q(x)}$$\nLa representación gráfica de esta relación en el plano cartesiano es habitualmente una curva dividida en múltiples ramas, caracterizada por acercarse infinitamente a líneas de límite conocidas como **asíntotas**.",
              "short_description": "Una **función racional** es aquella que puede expresarse como el cociente o división entre dos polinomios.\n$$f(x) = \\frac{P(x)}{Q(x)}$$",
              "skills": [
                "LEXI",
                "CLSF",
                "FORM",
                "GRAF"
              ]
            },
            {
              "key": "modulo",
              "name": "Función módulo",
              "tooltip": "Una **función módulo** (o **valor absoluto**) es aquella que devuelve la distancia de un número al cero, resultando siempre en un valor no negativo.\n$$f(x) = |x|$$\nLa representación gráfica de esta relación en el plano cartesiano tiene forma de **V** con vértice en el origen, y presenta un punto no derivable donde la función cambia de rama.",
              "short_description": "Una **función módulo** (o **valor absoluto**) es aquella que devuelve la distancia de un número al cero, resultando siempre en un valor no negativo.\n$$f(x) = |x|$$",
              "skills": []
            },
            {
              "key": "trigonometric",
              "name": "Funciones trigonométricas",
              "tooltip": "Una **función trigonométrica** es aquella que vincula la medida de un ángulo con las proporciones métricas de un espacio geométrico, destacándose como principales el **seno**, el **coseno** y la **tangente**.\n$$\\begin{aligned} f(x) &= \\sin(x) \\\\ f(x) &= \\cos(x) \\\\ f(x) &= \\tan(x) \\end{aligned}$$\nLa representación gráfica de esta relación en el plano cartesiano se caracteriza por ser una curva que oscila y repite su forma a intervalos regulares, lo que refleja un comportamiento cíclico o periódico.",
              "short_description": "Una **función trigonométrica** es aquella que vincula la medida de un ángulo con las proporciones métricas de un espacio geométrico, destacándose como principales el **seno**, el **coseno** y la **tangente**.\n$$\\begin{aligned} f(x) &= \\sin(x) \\\\ f(x) &= \\cos(x) \\\\ f(x) &= \\tan(x) \\end{aligned}$$",
              "skills": [
                "LEXI",
                "CLSF",
                "FORM",
                "GRAF"
              ]
            }
          ]
        }
      ]
    },
    {
      "key": "blue",
      "headline": "Límites",
      "description": "Un **límite** describe el valor al que se aproxima una función a medida que su variable independiente se acerca a un punto determinado o al infinito.\n$$\\lim_{x \\to a} f(x) = L$$\nEs el concepto que permite definir con rigor la **continuidad**, la **derivada** y la **integral**, y hace posible el estudio del comportamiento local de una función incluso allí donde no está definida.",
      "units": [
        {
          "key": "limits",
          "name": "Límites",
          "topics": [
            {
              "key": "definition",
              "name": "Definición",
              "tooltip": "El **límite** de una función formaliza la idea de **tendencia**. Describe a qué valor se acerca cuando su variable tiende a un valor $a$, sin importar si está definida exactamente allí.\n$$\\lim_{x \\to a} f(x) = L$$\nMientras que evaluar una función exige un valor fijo, el límite opera desde la **aproximación**. Permite comprender su comportamiento hacia un valor determinado a partir del análisis de su entorno.",
              "short_description": "El **límite** de una función formaliza la idea de **tendencia**. Describe a qué valor se acerca cuando su variable tiende a un valor $a$, sin importar si está definida exactamente allí.\n$$\\lim_{x \\to a} f(x) = L$$",
              "skills": [
                "LEXI",
                "RESL"
              ]
            },
            {
              "key": "lateral_limits",
              "name": "Laterales",
              "tooltip": "Los **límites laterales** desglosan el análisis de una tendencia al restringir la aproximación a una única dirección, acercándose a un valor exclusivamente por su izquierda o por su derecha.\n$$\\lim_{x \\to a^-} f(x), \\quad \\lim_{x \\to a^+} f(x)$$\nSu evaluación es indispensable en funciones que presentan **saltos** o **puntos de quiebre**. El **límite bilateral** existe si y solo si ambos caminos laterales convergen de forma simultánea hacia el mismo destino.",
              "short_description": "Los **límites laterales** desglosan el análisis de una tendencia al restringir la aproximación a una única dirección, acercándose a un valor exclusivamente por su izquierda o por su derecha.\n$$\\lim_{x \\to a^-} f(x), \\quad \\lim_{x \\to a^+} f(x)$$",
              "skills": [
                "LEXI",
                "GRAF",
                "RESL"
              ]
            },
            {
              "key": "infinite_limits",
              "name": "Infinito",
              "tooltip": "Los **límites al infinito** y los **límites infinitos** extienden el concepto de tendencia a escenarios donde la variable o la función crecen sin cota.\n$$\\lim_{x \\to \\pm\\infty} f(x) = L, \\quad \\lim_{x \\to a} f(x) = \\pm\\infty$$\nSu cálculo permite identificar las **asíntotas** de la gráfica, lo que hace posible distinguir entre una relación que se estabiliza a largo plazo y una que diverge en un punto específico de su dominio.",
              "short_description": "Los **límites al infinito** y los **límites infinitos** extienden el concepto de tendencia a escenarios donde la variable o la función crecen sin cota.\n$$\\lim_{x \\to \\pm\\infty} f(x) = L, \\quad \\lim_{x \\to a} f(x) = \\pm\\infty$$",
              "skills": [
                "LEXI",
                "GRAF",
                "RESL"
              ]
            },
            {
              "key": "continuity",
              "name": "Continuidad",
              "tooltip": "Una función es **continua** en un punto o un intervalo cuando la tendencia en un entorno coincide exactamente con su evaluación en el punto.\n$$\\lim_{x \\to a} f(x) = f(a)$$\nEl incumplimiento de esta igualdad genera una **discontinuidad**. Clasificar su gravedad, ya sea removible, de salto o esencial, depende puramente del comportamiento de los límites laterales.",
              "short_description": "Una función es **continua** en un punto o un intervalo cuando la tendencia en un entorno coincide exactamente con su evaluación en el punto.\n$$\\lim_{x \\to a} f(x) = f(a)$$",
              "skills": [
                "CLSF",
                "GRAF",
                "RESL"
              ]
            },
            {
              "key": "factorization",
              "name": "Factorización",
              "tooltip": "La **factorización** es un método algebraico para resolver límites donde la sustitución directa produce una **indeterminación**.\n\nPermite reescribir expresiones polinómicas como el producto de factores más simples.\n$$\\lim_{x \\to a} \\frac{f(x)(x-a)}{g(x)(x-a)}$$\nAl aislar este factor en el numerador y el denominador, hace posible su cancelación, lo que elimina la indeterminación y habilita la evaluación directa de la tendencia de la función.",
              "short_description": "La **factorización** es un método algebraico para resolver límites donde la sustitución directa produce una **indeterminación**.\n\nPermite reescribir expresiones polinómicas como el producto de factores más simples.\n$$\\lim_{x \\to a} \\frac{f(x)(x-a)}{g(x)(x-a)}$$",
              "skills": [
                "LEXI",
                "RESL"
              ]
            },
            {
              "key": "rationalization",
              "name": "Racionalización",
              "tooltip": "La **racionalización** es un método algebraico para resolver límites donde la sustitución directa produce una **indeterminación** y la expresión contiene raíces cuadradas.\n\nPermite transformar la expresión multiplicando por una fracción unitaria.\n$$\\lim_{x \\to a} \\frac{f(x)}{g(x)} \\cdot \\frac{\\sqrt{u}+c}{\\sqrt{u}+c}$$\nAl forzar una diferencia de cuadrados, aísla el factor en el numerador y el denominador, lo que hace posible su cancelación y habilita la evaluación directa de la tendencia de la función.",
              "short_description": "La **racionalización** es un método algebraico para resolver límites donde la sustitución directa produce una **indeterminación** y la expresión contiene raíces cuadradas.\n\nPermite transformar la expresión multiplicando por una fracción unitaria.\n$$\\lim_{x \\to a} \\frac{f(x)}{g(x)} \\cdot \\frac{\\sqrt{u}+c}{\\sqrt{u}+c}$$",
              "skills": [
                "LEXI",
                "RESL"
              ]
            }
          ]
        }
      ]
    },
    {
      "key": "violet",
      "headline": "Derivadas",
      "description": "Una **derivada** mide la tasa de cambio instantánea de una función respecto de su variable independiente.\n$$f'(a) = \\lim_{h \\to 0} \\frac{f(a+h) - f(a)}{h}$$\nGeométricamente representa la **pendiente** de la **recta tangente** a la curva en un punto, y es la herramienta principal para analizar el crecimiento, la curvatura y el comportamiento local de una función.",
      "units": [
        {
          "key": "derivatives",
          "name": "Derivadas",
          "topics": [
            {
              "key": "limit_definition",
              "name": "Definición de derivada",
              "tooltip": "La **derivada** mide la **tasa de cambio instantánea** de una función. Describe a qué velocidad exacta está variando una magnitud en un momento o punto específico.\n$$f'(a) = \\lim_{h \\to 0} \\frac{f(a+h) - f(a)}{h}$$\nAl aplicar el concepto de límite sobre una variación infinitamente pequeña, revela la **intensidad con la que crece o decrece la función** en un punto. Constituye la operación fundamental que, junto con su inversa, la **integral**, conforma la base del análisis matemático.",
              "short_description": "La **derivada** mide la **tasa de cambio instantánea** de una función. Describe a qué velocidad exacta está variando una magnitud en un momento o punto específico.\n$$f'(a) = \\lim_{h \\to 0} \\frac{f(a+h) - f(a)}{h}$$",
              "skills": [
                "LEXI",
                "CLSF",
                "GRAF",
                "ESTR"
              ]
            },
            {
              "key": "geometric_interpretation",
              "name": "Interpretación geométrica",
              "tooltip": "Geométricamente, la **derivada** de una función en un punto representa la **pendiente de la recta tangente** a la curva en ese mismo lugar.\n$$y = f'(a)(x - a) + f(a)$$\nEsta recta surge como el límite de las pendientes de las rectas **secantes**. Al acercar sus puntos de corte, la recta se junta con la dirección instantánea de la curva, convirtiéndose en la mejor aproximación lineal de la función en ese entorno.",
              "short_description": "Geométricamente, la **derivada** de una función en un punto representa la **pendiente de la recta tangente** a la curva en ese mismo lugar.\n$$y = f'(a)(x - a) + f(a)$$",
              "skills": [
                "LEXI",
                "GRAF",
                "ESTR",
                "RESL"
              ]
            },
            {
              "key": "differentiation_rules",
              "name": "Reglas",
              "tooltip": "Las **reglas de derivación** simplifican el cálculo de derivadas mediante fórmulas directas que combinan linealmente las derivadas de funciones elementales, incluyendo potencias, exponenciales, logaritmos y funciones trigonométricas.\n$$\\frac{d}{dx}[f(x) \\pm g(x)] = f'(x) \\pm g'(x)$$",
              "short_description": "Las **reglas de derivación** simplifican el cálculo de derivadas mediante fórmulas directas que combinan linealmente las derivadas de funciones elementales.\n$$\\frac{d}{dx}[f(x) \\pm g(x)] = f'(x) \\pm g'(x)$$",
              "skills": [
                "FORM",
                "ESTR",
                "RESL"
              ]
            },
            {
              "key": "product",
              "name": "Producto",
              "tooltip": "La **regla del producto** permite derivar funciones que resultan de multiplicar dos expresiones dependientes de la misma variable.\n$$(u \\cdot v)' = u'v + uv'$$\nSu uso es indispensable cuando interactúan factores que no pueden unificarse algebraicamente. La fórmula refleja que, cuando dos cantidades varían al mismo tiempo, el cambio total es la suma del crecimiento de una parte mientras la otra se mantiene constante, y viceversa.",
              "short_description": "La **regla del producto** permite derivar funciones que resultan de multiplicar dos expresiones dependientes de la misma variable.\n$$(u \\cdot v)' = u'v + uv'$$",
              "skills": [
                "ESTR",
                "RESL"
              ]
            },
            {
              "key": "quotient",
              "name": "Cociente",
              "tooltip": "La **regla del cociente** permite derivar funciones que resultan de dividir dos expresiones dependientes de la misma variable.\n$$\\left(\\frac{u}{v}\\right)' = \\frac{u'v - uv'}{v^2}$$\nEvita la reescritura previa de la expresión y es indispensable cuando el numerador y el denominador no admiten una simplificación algebraica directa.",
              "short_description": "La **regla del cociente** permite derivar funciones que resultan de dividir dos expresiones dependientes de la misma variable.\n$$\\left(\\frac{u}{v}\\right)' = \\frac{u'v - uv'}{v^2}$$",
              "skills": [
                "ESTR",
                "RESL"
              ]
            },
            {
              "key": "chain_rule",
              "name": "Cadena",
              "tooltip": "La **regla de la cadena** permite derivar funciones **compuestas**, es decir, aquellas en las que una función actúa sobre el resultado de otra.\n$$(g \\circ h)'(x) = g'(h(x)) \\cdot h'(x)$$\nSu aplicación consiste en derivar la función **exterior** evaluada en la **interior**, y multiplicarla luego por la derivada de esta última.",
              "short_description": "La **regla de la cadena** permite derivar funciones **compuestas**, es decir, aquellas en las que una función actúa sobre el resultado de otra.\n$$(g \\circ h)'(x) = g'(h(x)) \\cdot h'(x)$$",
              "skills": [
                "ESTR",
                "RESL"
              ]
            },
            {
              "key": "lhopital",
              "name": "L'Hôpital",
              "tooltip": "La **regla de L'Hôpital** resuelve límites **indeterminados** del tipo $\\tfrac{0}{0}$ o $\\tfrac{\\infty}{\\infty}$ derivando por separado el numerador y el denominador.\n$$\\lim_{x \\to a} \\frac{f(x)}{g(x)} = \\lim_{x \\to a} \\frac{f'(x)}{g'(x)}$$\nSe aplica reiteradamente mientras la indeterminación persista, aprovechando que las derivadas suelen tener un comportamiento más simple cerca del punto crítico.",
              "short_description": "La **regla de L'Hôpital** resuelve límites **indeterminados** del tipo $\\tfrac{0}{0}$ o $\\tfrac{\\infty}{\\infty}$ derivando por separado el numerador y el denominador.\n$$\\lim_{x \\to a} \\frac{f(x)}{g(x)} = \\lim_{x \\to a} \\frac{f'(x)}{g'(x)}$$",
              "skills": [
                "ESTR",
                "RESL"
              ]
            }
          ]
        }
      ]
    },
    {
      "key": "brown",
      "headline": "Integrales",
      "description": "Una **integral** acumula cambios infinitesimales y calcula el **área** neta encerrada bajo una curva sobre un intervalo.\n$$\\int_a^b f(x) \\, dx = F(b) - F(a)$$\nEs la operación inversa de la **derivada** según el **Teorema Fundamental del Cálculo**, y permite reconstruir una función a partir de su tasa de cambio, calcular áreas y sumar acumulaciones a lo largo de un intervalo.",
      "units": [
        {
          "key": "integrals",
          "name": "Integrales",
          "topics": [
            {
              "key": "definition",
              "name": "Definición",
              "tooltip": "La **integral indefinida** de una función es su **antiderivada**, es decir, otra función cuya derivada devuelve a la original.\n$$\\int f(x) \\, dx = F(x) + C$$\nLa **constante de integración** $C$ refleja que existe una familia infinita de antiderivadas, todas diferenciadas entre sí únicamente por un valor constante.",
              "short_description": "La **integral indefinida** de una función es su **antiderivada**, es decir, otra función cuya derivada devuelve a la original.\n$$\\int f(x) \\, dx = F(x) + C$$",
              "skills": [
                "LEXI",
                "ESTR",
                "RESL"
              ]
            },
            {
              "key": "reglas",
              "name": "Reglas",
              "tooltip": "Las **reglas de integración** simplifican el cálculo de integrales mediante fórmulas directas que combinan linealmente las antiderivadas de funciones elementales, incluyendo potencias, exponenciales, logaritmos y funciones trigonométricas.\n$$\\int [f(x) \\pm g(x)] \\, dx = \\int f(x) \\, dx \\pm \\int g(x) \\, dx$$",
              "short_description": "Las **reglas de integración** simplifican el cálculo de integrales mediante fórmulas directas que combinan linealmente las antiderivadas de funciones elementales.\n$$\\int [f(x) \\pm g(x)] \\, dx = \\int f(x) \\, dx \\pm \\int g(x) \\, dx$$",
              "skills": [
                "FORM",
                "ESTR",
                "RESL"
              ]
            },
            {
              "key": "substitution",
              "name": "Sustitución",
              "tooltip": "La **integración por sustitución** simplifica una integral introduciendo un **cambio de variable** que absorbe una parte compuesta de la expresión.\n$$\\int f(g(x)) \\cdot g'(x) \\, dx = \\int f(u) \\, du$$\nEs la contraparte integral de la **regla de la cadena** y resulta especialmente útil cuando la derivada de una función interior aparece como factor dentro del integrando.",
              "short_description": "La **integración por sustitución** simplifica una integral introduciendo un **cambio de variable** que absorbe una parte compuesta de la expresión.\n$$\\int f(g(x)) \\cdot g'(x) \\, dx = \\int f(u) \\, du$$",
              "skills": [
                "ESTR",
                "RESL"
              ]
            },
            {
              "key": "parts",
              "name": "Partes",
              "tooltip": "La **integración por partes** descompone una integral en dos términos apoyándose en la regla del producto para derivadas.\n$$\\int u \\, dv = u \\, v - \\int v \\, du$$\nSe elige la parte $u$ que se simplifica al derivarse y la parte $dv$ que resulta fácil de integrar, buscando así una integral remanente más simple que la original.",
              "short_description": "La **integración por partes** descompone una integral en dos términos apoyándose en la regla del producto para derivadas.\n$$\\int u \\, dv = u \\, v - \\int v \\, du$$",
              "skills": [
                "ESTR",
                "RESL"
              ]
            },
            {
              "key": "definite",
              "name": "Definidas",
              "tooltip": "La **integral definida** calcula el **área neta** encerrada entre una función y el eje horizontal sobre un intervalo determinado.\n$$\\int_a^b f(x) \\, dx = F(b) - F(a)$$\nSu evaluación se realiza mediante el **Teorema Fundamental del Cálculo**, que conecta la integración con la antiderivada de la función.",
              "short_description": "La **integral definida** calcula el **área neta** encerrada entre una función y el eje horizontal sobre un intervalo determinado.\n$$\\int_a^b f(x) \\, dx = F(b) - F(a)$$",
              "skills": [
                "GRAF",
                "RESL"
              ]
            }
          ]
        }
      ]
    }
  ]
}
