/**
 * Generates `src/lib/catalog/analisis.generated.ts` from the backend's
 * `content/analisis/catalog.json`.
 *
 * Wired into `predev` and `prebuild` so the generated module stays in sync
 * with the backend source of truth. Replace this whole script the day the
 * backend ships `GET /course/{id}/catalog`.
 *
 * Run manually: `bun run scripts/sync-catalog.ts`
 */

import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs"
import { dirname, resolve, join } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const CONTENT = resolve(here, "../../backend/content/analisis")
const SOURCE = join(CONTENT, "catalog.json")
const OUT = resolve(here, "../src/lib/catalog/analisis.generated.ts")

type RawTopic = {
  key: string
  name: string
  tooltip: string
  short_description?: string
  exercise_types?: string[]
}

type RawBelt = {
  key: string
  topics: RawTopic[]
}

type RawExerciseType = {
  id: string
  label: string
  description: string
}

type RawCatalog = { belts: RawBelt[]; exercise_types: RawExerciseType[] }

// Scan the new belt/unit/topic/SKILL.json structure to collect exercise_types
// per (belt, topic). Returns a map keyed by `${belt}/${topic}`.
function collectTopicExerciseTypes(): Map<string, Set<string>> {
  const out = new Map<string, Set<string>>()
  for (const beltEntry of readdirSync(CONTENT, { withFileTypes: true })) {
    if (!beltEntry.isDirectory()) continue
    const belt = beltEntry.name
    const beltPath = join(CONTENT, belt)
    for (const unitEntry of readdirSync(beltPath, { withFileTypes: true })) {
      if (!unitEntry.isDirectory()) continue
      const unitPath = join(beltPath, unitEntry.name)
      for (const topicEntry of readdirSync(unitPath, { withFileTypes: true })) {
        if (!topicEntry.isDirectory()) continue
        const topic = topicEntry.name
        const topicPath = join(unitPath, topic)
        const key = `${belt}/${topic}`
        for (const file of readdirSync(topicPath)) {
          if (!file.endsWith(".json")) continue
          const skill = file.slice(0, -5) // strip .json
          const set = out.get(key) ?? new Set<string>()
          set.add(skill)
          out.set(key, set)
        }
      }
    }
  }
  return out
}

function generate() {
  const raw: RawCatalog = JSON.parse(readFileSync(SOURCE, "utf8"))

  // Attach the unit set (exercise_types) to each topic, ordered by the catalog's
  // canonical exercise_types order so the dashboard grid renders consistently.
  const typeOrder = raw.exercise_types.map((t) => t.id)
  const byTopic = collectTopicExerciseTypes()
  for (const belt of raw.belts) {
    for (const topic of belt.topics) {
      const types = byTopic.get(`${belt.key}/${topic.key}`) ?? new Set<string>()
      topic.exercise_types = typeOrder.filter((id) => types.has(id))
    }
  }

  const beltKeys = raw.belts.map((b) => b.key)

  const header = `// AUTO-GENERATED by scripts/sync-catalog.ts.
// Source: backend/content/analisis/catalog.json
// Do not edit by hand; rerun \`bun run scripts/sync-catalog.ts\`.

`

  const types = `export type BeltKey = ${beltKeys.map((k) => JSON.stringify(k)).join(" | ")}

export interface Topic {
  key: string
  name: string
  tooltip: string
  short_description?: string
  exercise_types: string[]
}

export interface Belt {
  key: BeltKey
  topics: Topic[]
}

export interface ExerciseType {
  id: string
  label: string
  description: string
}

export interface Catalog {
  belts: Belt[]
  exercise_types: ExerciseType[]
}

`

  const data = `export const catalog: Catalog = ${JSON.stringify(raw, null, 2)}\n`

  mkdirSync(dirname(OUT), { recursive: true })
  writeFileSync(OUT, header + types + data)
  console.log(`✓ Wrote ${OUT} (${raw.belts.length} belts)`)
}

generate()
