/**
 * Generates `src/lib/emoji-tree.generated.ts` from the backend's
 * `content/emoji-tree.json` (árbol de desbloqueo de emojis por carrera).
 *
 * Wired into `sync:all` (predev/prebuild) so the generated module stays in sync
 * with the backend source of truth. Los umbrales de XP por profundidad viven en
 * el backend (emoji_tree.DEPTH_XP); acá se replican como dato derivado.
 *
 * Run manually: `bun run scripts/sync-emoji-tree.ts`
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import { dirname, resolve, join } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const SOURCE = resolve(here, "../../backend/content/emoji-tree.json")
const OUT = resolve(here, "../src/lib/emoji-tree.generated.ts")

// Debe coincidir con backend/emoji_tree.py DEPTH_XP.
const DEPTH_XP: Record<number, number> = { 1: 64, 2: 256, 3: 1024, 4: 4096, 5: 8192 }

function generate() {
  const raw = readFileSync(SOURCE, "utf8")
  const tree = JSON.parse(raw) as Record<string, unknown>
  const bucketKeys = Object.keys(tree)

  const header = `// AUTO-GENERATED by scripts/sync-emoji-tree.ts.
// Source: backend/content/emoji-tree.json
// Do not edit by hand; rerun \`bun run scripts/sync-emoji-tree.ts\`.

`

  const types = `export type EmojiBucket = ${bucketKeys.map((k) => JSON.stringify(k)).join(" | ")}

export interface EmojiNode {
  id: string
  emoji: string
  label: string
  unis?: string[]
  children?: EmojiNode[]
}

// Umbral de XP por profundidad del nodo (0 = raíz de bucket, gratis).
export const DEPTH_XP: Record<number, number> = ${JSON.stringify(DEPTH_XP)}

`

  const data = `export const EMOJI_TREE: Record<EmojiBucket, EmojiNode> = ${JSON.stringify(tree, null, 2)}\n`

  mkdirSync(dirname(OUT), { recursive: true })
  writeFileSync(OUT, header + types + data)
  console.log(`✓ Wrote ${OUT} (${bucketKeys.length} buckets)`)
}

generate()
