/**
 * Generates `src/lib/catalog/analisis.generated.ts` from the backend's
 * `content/analisis/course.json` (single source of course structure:
 * course → belt → units → topics → skills).
 *
 * Wired into `predev` and `prebuild` so the generated module stays in sync with
 * the backend source of truth. The same file is served at runtime by
 * `GET /course/{id}/structure`; this build step exists to keep `BeltKey` a
 * compile-time union.
 *
 * Run manually: `bun run scripts/sync-catalog.ts`
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import { dirname, resolve, join } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const CONTENT = resolve(here, "../../backend/content/analisis")
const SOURCE = join(CONTENT, "course.json")
const OUT = resolve(here, "../src/lib/catalog/analisis.generated.ts")

type RawTopic = {
  key: string
  name: string
  tooltip: string
  short_description?: string
  skills: string[]
}

type RawUnit = { key: string; name: string; topics: RawTopic[] }

type RawBelt = {
  key: string
  headline: string
  description: string
  units: RawUnit[]
}

type RawExerciseType = { id: string; label: string; description: string }

type RawCourse = {
  slug: string
  name: string
  description: string
  exercise_types: RawExerciseType[]
  belts: RawBelt[]
}

function generate() {
  const raw: RawCourse = JSON.parse(readFileSync(SOURCE, "utf8"))
  const beltKeys = raw.belts.map((b) => b.key)

  const header = `// AUTO-GENERATED by scripts/sync-catalog.ts.
// Source: backend/content/analisis/course.json
// Do not edit by hand; rerun \`bun run scripts/sync-catalog.ts\`.

`

  const types = `export type BeltKey = ${beltKeys.map((k) => JSON.stringify(k)).join(" | ")}

export interface Topic {
  key: string
  name: string
  tooltip: string
  short_description?: string
  skills: string[]
}

export interface Unit {
  key: string
  name: string
  topics: Topic[]
}

export interface Belt {
  key: BeltKey
  headline: string
  description: string
  units: Unit[]
}

export interface ExerciseType {
  id: string
  label: string
  description: string
}

export interface Catalog {
  slug: string
  name: string
  description: string
  belts: Belt[]
  exercise_types: ExerciseType[]
}

`

  const data = `export const catalog: Catalog = ${JSON.stringify(raw, null, 2)}\n`

  mkdirSync(dirname(OUT), { recursive: true })
  writeFileSync(OUT, header + types + data)
  const nUnits = raw.belts.reduce((n, b) => n + b.units.length, 0)
  console.log(`✓ Wrote ${OUT} (${raw.belts.length} belts, ${nUnits} units)`)
}

generate()
