/**
 * Generates `src/lib/catalog/analisis-1.generated.ts` from the backend's
 * `content/analisis-1/catalog.json`.
 *
 * Wired into `predev` and `prebuild` so the generated module stays in sync
 * with the backend source of truth. Replace this whole script the day the
 * backend ships `GET /course/{id}/catalog`.
 *
 * Run manually: `bun run scripts/sync-catalog.ts`
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const SOURCE = resolve(here, "../../backend/content/analisis-1/catalog.json")
const OUT = resolve(here, "../src/lib/catalog/analisis-1.generated.ts")

type RawTopic = {
  key: string
  skills: string[]
  tooltip: string
}

type RawBelt = {
  key: string
  stripe_thresholds: [number, number]
  promotion_threshold: number
  topics: RawTopic[]
}

type RawCatalog = { belts: RawBelt[] }

function generate() {
  const raw: RawCatalog = JSON.parse(readFileSync(SOURCE, "utf8"))

  const beltKeys = raw.belts.map((b) => b.key)

  const header = `// AUTO-GENERATED by scripts/sync-catalog.ts.
// Source: backend/content/analisis-1/catalog.json
// Do not edit by hand; rerun \`bun run scripts/sync-catalog.ts\`.

`

  const types = `export type BeltKey = ${beltKeys.map((k) => JSON.stringify(k)).join(" | ")}

export type Skill = string

export interface Topic {
  key: string
  skills: Skill[]
  tooltip: string
}

export interface Belt {
  key: BeltKey
  stripe_thresholds: [number, number]
  promotion_threshold: number
  topics: Topic[]
}

export interface Catalog {
  belts: Belt[]
}

`

  const data = `export const catalog: Catalog = ${JSON.stringify(raw, null, 2)}\n`

  mkdirSync(dirname(OUT), { recursive: true })
  writeFileSync(OUT, header + types + data)
  console.log(`✓ Wrote ${OUT} (${raw.belts.length} belts)`)
}

generate()
