"""Add exercises table

Revision ID: a1b2c3d4e5f6
Revises: 2688f2e54f81
Create Date: 2026-04-07 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '2688f2e54f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Mapping from old exercise bank skill keys to algorithm SkillCodes
_OLD_SKILL_TO_CODE = {
    "vocabulary": "LEXI",
    "visual_recognition": "CLSF",
    "parameter_identification": "FORM",
}


def upgrade() -> None:
    exercises_table = op.create_table(
        'exercises',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('course_id', sa.Integer(), nullable=False),
        sa.Column('belt', sa.String(20), nullable=False),
        sa.Column('topic', sa.String(50), nullable=False),
        sa.Column('skill', sa.String(10), nullable=False),
        sa.Column('subtype', sa.String(10), nullable=False),
        sa.Column('question', sa.Text(), nullable=False),
        sa.Column('option_a', sa.Text(), nullable=False),
        sa.Column('option_b', sa.Text(), nullable=False),
        sa.Column('option_c', sa.Text(), nullable=False),
        sa.Column('option_d', sa.Text(), nullable=False),
        sa.Column('correct_index', sa.Integer(), nullable=False),
        sa.Column('has_math', sa.Boolean(), nullable=True, server_default='0'),
        sa.Column('feedback_correct', sa.Text(), nullable=False),
        sa.Column('feedback_incorrect', sa.Text(), nullable=False),
        sa.Column('graph_fn', sa.String(500), nullable=True),
        sa.Column('graph_view', sa.String(100), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['course_id'], ['courses.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_exercises_lookup', 'exercises', ['course_id', 'belt', 'topic', 'skill'])
    op.create_index('ix_exercises_id', 'exercises', ['id'])

    # Datos de ejercicios eliminados de la migración.
    # El seed lo hace seed_content.py (corre en startup vía main.py).
    # Esto evita el ForeignKeyViolation cuando courses está vacío.
    _seed = [
        # ── LINEAR / LEXI ────────────────────────────────────────────────
        {
            "course_id": 1, "belt": "white", "topic": "linear", "skill": "LEXI",
            "subtype": "text",
            "question": "\\u00bfCu\\u00e1l de estas expresiones representa una funci\\u00f3n lineal?",
            "option_a": "$f(x) = 5x - 2$", "option_b": "$f(x) = x^2$",
            "option_c": "$f(x) = 3^x$", "option_d": "$f(x) = \\\\log(x)$",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! Una funci\\u00f3n lineal tiene la forma $f(x) = mx + b$, donde $m$ y $b$ son constantes.",
            "feedback_incorrect": "Una funci\\u00f3n lineal tiene la forma $f(x) = mx + b$. La opci\\u00f3n correcta es $f(x) = 5x - 2$.",
            "graph_fn": None, "graph_view": None,
        },
        {
            "course_id": 1, "belt": "white", "topic": "linear", "skill": "LEXI",
            "subtype": "graph",
            "question": "\\u00bfC\\u00f3mo se llama el punto donde la recta corta el eje Y?",
            "option_a": "Ordenada al origen", "option_b": "Pendiente",
            "option_c": "Ra\\u00edz", "option_d": "V\\u00e9rtice",
            "correct_index": 0, "has_math": False,
            "feedback_correct": "\\u00a1Correcto! El valor de $f(0)$ se llama ordenada al origen (o intercepto en Y).",
            "feedback_incorrect": "El punto donde la recta corta el eje Y se llama ordenada al origen ($f(0) = b$ en $f(x) = mx + b$).",
            "graph_fn": "3*x + 2", "graph_view": "[-4, 4, -8, 10]",
        },
        # ── LINEAR / CLSF ────────────────────────────────────────────────
        {
            "course_id": 1, "belt": "white", "topic": "linear", "skill": "CLSF",
            "subtype": "graph",
            "question": "\\u00bfA qu\\u00e9 familia de funciones pertenece esta gr\\u00e1fica?",
            "option_a": "Lineal", "option_b": "Cuadr\\u00e1tica",
            "option_c": "Exponencial", "option_d": "Logar\\u00edtmica",
            "correct_index": 0, "has_math": False,
            "feedback_correct": "\\u00a1Correcto! La gr\\u00e1fica es una l\\u00ednea recta: $f(x) = 2x - 5$, una funci\\u00f3n lineal.",
            "feedback_incorrect": "La gr\\u00e1fica es una l\\u00ednea recta ($f(x) = 2x - 5$), caracter\\u00edstica de una funci\\u00f3n lineal.",
            "graph_fn": "2*x - 5", "graph_view": "[-4, 6, -10, 10]",
        },
        {
            "course_id": 1, "belt": "white", "topic": "linear", "skill": "CLSF",
            "subtype": "text",
            "question": "\\u00bfA qu\\u00e9 familia de funciones pertenece $f(x) = 2x - 5$?",
            "option_a": "Lineal", "option_b": "Cuadr\\u00e1tica",
            "option_c": "Exponencial", "option_d": "Logar\\u00edtmica",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! $f(x) = 2x - 5$ tiene la forma $f(x) = mx + b$: es una funci\\u00f3n lineal.",
            "feedback_incorrect": "$f(x) = 2x - 5$ tiene la forma $f(x) = mx + b$, que define una funci\\u00f3n lineal.",
            "graph_fn": None, "graph_view": None,
        },
        # ── LINEAR / FORM ────────────────────────────────────────────────
        {
            "course_id": 1, "belt": "white", "topic": "linear", "skill": "FORM",
            "subtype": "text",
            "question": "En $f(x) = -3x + 8$, \\u00bfcu\\u00e1l es la ordenada al origen?",
            "option_a": "$8$", "option_b": "$-3$",
            "option_c": "$-3x$", "option_d": "$x$",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! En $f(x) = mx + b$, la ordenada al origen es $b = 8$.",
            "feedback_incorrect": "En $f(x) = mx + b$, $b$ es la ordenada al origen. Aqu\\u00ed $b = 8$.",
            "graph_fn": None, "graph_view": None,
        },
        {
            "course_id": 1, "belt": "white", "topic": "linear", "skill": "FORM",
            "subtype": "graph",
            "question": "\\u00bfCu\\u00e1l de estas expresiones corresponde a la recta del gr\\u00e1fico?",
            "option_a": "$y = 2x - 3$", "option_b": "$y = -2x + 3$",
            "option_c": "$y = 3x - 2$", "option_d": "$y = 2x + 3$",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! La recta tiene pendiente 2 e intercepto \\u22123: $y = 2x - 3$.",
            "feedback_incorrect": "La recta sube 2 unidades por cada unidad en x y corta el eje Y en \\u22123: $y = 2x - 3$.",
            "graph_fn": "2*x - 3", "graph_view": "[-3, 5, -8, 8]",
        },
        # ── QUADRATIC / LEXI ─────────────────────────────────────────────
        {
            "course_id": 1, "belt": "white", "topic": "quadratic", "skill": "LEXI",
            "subtype": "text",
            "question": "\\u00bfCu\\u00e1l de estas expresiones representa una funci\\u00f3n cuadr\\u00e1tica?",
            "option_a": "$f(x) = 2x^2 - x + 1$", "option_b": "$f(x) = 4x - 7$",
            "option_c": "$f(x) = 2^x$", "option_d": "$f(x) = \\\\sqrt{x}$",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! Una funci\\u00f3n cuadr\\u00e1tica tiene la forma $f(x) = ax^2 + bx + c$ con $a \\\\neq 0$.",
            "feedback_incorrect": "Una funci\\u00f3n cuadr\\u00e1tica incluye un t\\u00e9rmino de segundo grado ($x^2$). La correcta es $f(x) = 2x^2 - x + 1$.",
            "graph_fn": None, "graph_view": None,
        },
        {
            "course_id": 1, "belt": "white", "topic": "quadratic", "skill": "LEXI",
            "subtype": "graph",
            "question": "\\u00bfC\\u00f3mo se llama el punto m\\u00e1s bajo (o m\\u00e1s alto) de esta par\\u00e1bola?",
            "option_a": "V\\u00e9rtice", "option_b": "Ra\\u00edz",
            "option_c": "Ordenada al origen", "option_d": "As\\u00edntota",
            "correct_index": 0, "has_math": False,
            "feedback_correct": "\\u00a1Correcto! El punto extremo de una par\\u00e1bola se llama v\\u00e9rtice.",
            "feedback_incorrect": "El punto m\\u00e1s bajo (m\\u00ednimo) o m\\u00e1s alto (m\\u00e1ximo) de una par\\u00e1bola se llama v\\u00e9rtice.",
            "graph_fn": "x*x - 4*x + 3", "graph_view": "[-1, 5, -2, 8]",
        },
        # ── QUADRATIC / CLSF ─────────────────────────────────────────────
        {
            "course_id": 1, "belt": "white", "topic": "quadratic", "skill": "CLSF",
            "subtype": "graph",
            "question": "\\u00bfA qu\\u00e9 familia de funciones pertenece esta gr\\u00e1fica?",
            "option_a": "Cuadr\\u00e1tica", "option_b": "Lineal",
            "option_c": "Exponencial", "option_d": "Racional",
            "correct_index": 0, "has_math": False,
            "feedback_correct": "\\u00a1Correcto! La gr\\u00e1fica es una par\\u00e1bola: $f(x) = x^2 - 4x + 3$, una funci\\u00f3n cuadr\\u00e1tica.",
            "feedback_incorrect": "La gr\\u00e1fica es una par\\u00e1bola ($f(x) = x^2 - 4x + 3$), caracter\\u00edstica de una funci\\u00f3n cuadr\\u00e1tica.",
            "graph_fn": "x*x - 4*x + 3", "graph_view": "[-1, 5, -2, 8]",
        },
        {
            "course_id": 1, "belt": "white", "topic": "quadratic", "skill": "CLSF",
            "subtype": "text",
            "question": "\\u00bfA qu\\u00e9 familia de funciones pertenece $f(x) = x^2 - 4x + 3$?",
            "option_a": "Cuadr\\u00e1tica", "option_b": "Lineal",
            "option_c": "Exponencial", "option_d": "Racional",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! $f(x) = x^2 - 4x + 3$ tiene la forma $ax^2 + bx + c$: es una funci\\u00f3n cuadr\\u00e1tica.",
            "feedback_incorrect": "$f(x) = x^2 - 4x + 3$ tiene un t\\u00e9rmino $x^2$ como mayor potencia: es una funci\\u00f3n cuadr\\u00e1tica.",
            "graph_fn": None, "graph_view": None,
        },
        # ── QUADRATIC / FORM ─────────────────────────────────────────────
        {
            "course_id": 1, "belt": "white", "topic": "quadratic", "skill": "FORM",
            "subtype": "text",
            "question": "En $f(x) = 3x^2 - 6x + 2$, \\u00bfcu\\u00e1l es el coeficiente del t\\u00e9rmino cuadr\\u00e1tico?",
            "option_a": "$3$", "option_b": "$-6$",
            "option_c": "$2$", "option_d": "$-3$",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! En $f(x) = ax^2 + bx + c$, el coeficiente cuadr\\u00e1tico es $a = 3$.",
            "feedback_incorrect": "En $f(x) = ax^2 + bx + c$, $a$ es el coeficiente cuadr\\u00e1tico. Aqu\\u00ed $a = 3$.",
            "graph_fn": None, "graph_view": None,
        },
        {
            "course_id": 1, "belt": "white", "topic": "quadratic", "skill": "FORM",
            "subtype": "graph",
            "question": "\\u00bfCu\\u00e1l de estas expresiones corresponde a la par\\u00e1bola del gr\\u00e1fico?",
            "option_a": "$f(x) = (x-2)^2 - 1$", "option_b": "$f(x) = (x+2)^2 - 1$",
            "option_c": "$f(x) = -(x-2)^2 - 1$", "option_d": "$f(x) = (x-2)^2 + 1$",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! El v\\u00e9rtice est\\u00e1 en (2, \\u22121) y la par\\u00e1bola se abre hacia arriba: $f(x) = (x-2)^2 - 1$.",
            "feedback_incorrect": "La par\\u00e1bola tiene v\\u00e9rtice en (2, \\u22121) y se abre hacia arriba: $f(x) = (x-2)^2 - 1$.",
            "graph_fn": "pow(x-2, 2) - 1", "graph_view": "[-1, 5, -2, 8]",
        },
        # ── POLYNOMIAL / LEXI ────────────────────────────────────────────
        {
            "course_id": 1, "belt": "white", "topic": "polynomial", "skill": "LEXI",
            "subtype": "text",
            "question": "\\u00bfCu\\u00e1l de estas funciones es un polinomio de grado 3?",
            "option_a": "$f(x) = x^3 - 2x + 5$", "option_b": "$f(x) = x^2 + 1$",
            "option_c": "$f(x) = 4x - 1$", "option_d": "$f(x) = x^4$",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! Un polinomio de grado 3 tiene como t\\u00e9rmino de mayor grado $x^3$.",
            "feedback_incorrect": "Un polinomio de grado 3 tiene $x^3$ como potencia m\\u00e1xima. La correcta es $f(x) = x^3 - 2x + 5$.",
            "graph_fn": None, "graph_view": None,
        },
        {
            "course_id": 1, "belt": "white", "topic": "polynomial", "skill": "LEXI",
            "subtype": "graph",
            "question": "\\u00bfCu\\u00e1ntas ra\\u00edces reales puede tener como m\\u00e1ximo esta funci\\u00f3n polin\\u00f3mica?",
            "option_a": "3", "option_b": "2",
            "option_c": "1", "option_d": "Infinitas",
            "correct_index": 0, "has_math": False,
            "feedback_correct": "\\u00a1Correcto! Un polinomio de grado 3 puede tener hasta 3 ra\\u00edces reales.",
            "feedback_incorrect": "El n\\u00famero m\\u00e1ximo de ra\\u00edces reales de un polinomio es igual a su grado. Aqu\\u00ed el grado es 3.",
            "graph_fn": "pow(x, 3) - 3*x", "graph_view": "[-3, 3, -5, 5]",
        },
        # ── POLYNOMIAL / CLSF ────────────────────────────────────────────
        {
            "course_id": 1, "belt": "white", "topic": "polynomial", "skill": "CLSF",
            "subtype": "graph",
            "question": "\\u00bfA qu\\u00e9 familia de funciones pertenece esta gr\\u00e1fica?",
            "option_a": "Polin\\u00f3mica", "option_b": "Cuadr\\u00e1tica",
            "option_c": "Lineal", "option_d": "Exponencial",
            "correct_index": 0, "has_math": False,
            "feedback_correct": "\\u00a1Correcto! La curva es un polinomio de grado 3: $f(x) = x^3 - 2x^2 + x - 1$.",
            "feedback_incorrect": "La curva con dos cambios de direcci\\u00f3n es $f(x) = x^3 - 2x^2 + x - 1$, un polinomio de grado 3.",
            "graph_fn": "pow(x, 3) - 2*pow(x, 2) + x - 1", "graph_view": "[-2, 3, -5, 4]",
        },
        {
            "course_id": 1, "belt": "white", "topic": "polynomial", "skill": "CLSF",
            "subtype": "text",
            "question": "\\u00bfA qu\\u00e9 familia de funciones pertenece $f(x) = x^3 - 2x^2 + x - 1$?",
            "option_a": "Polin\\u00f3mica", "option_b": "Cuadr\\u00e1tica",
            "option_c": "Lineal", "option_d": "Exponencial",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! $f(x) = x^3 - 2x^2 + x - 1$ es un polinomio de grado 3.",
            "feedback_incorrect": "$f(x) = x^3 - 2x^2 + x - 1$ tiene $x^3$ como t\\u00e9rmino de mayor grado: es un polinomio de grado 3.",
            "graph_fn": None, "graph_view": None,
        },
        # ── POLYNOMIAL / FORM ────────────────────────────────────────────
        {
            "course_id": 1, "belt": "white", "topic": "polynomial", "skill": "FORM",
            "subtype": "text",
            "question": "\\u00bfCu\\u00e1l es el grado de $p(x) = 4x^5 - 3x^3 + x - 7$?",
            "option_a": "$5$", "option_b": "$3$",
            "option_c": "$1$", "option_d": "$4$",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! El grado es la potencia m\\u00e1s alta. En $4x^5 - 3x^3 + x - 7$, el grado es $5$.",
            "feedback_incorrect": "El grado es la potencia m\\u00e1s alta de $x$. En $4x^5 - 3x^3 + x - 7$, el grado es $5$.",
            "graph_fn": None, "graph_view": None,
        },
        {
            "course_id": 1, "belt": "white", "topic": "polynomial", "skill": "FORM",
            "subtype": "graph",
            "question": "\\u00bfCu\\u00e1l de estas expresiones corresponde a la curva del gr\\u00e1fico?",
            "option_a": "$f(x) = x^3 - 3x$", "option_b": "$f(x) = x^3 + 3x$",
            "option_c": "$f(x) = -x^3 + 3x$", "option_d": "$f(x) = x^2 - 3$",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! La curva tiene ra\\u00edces en $-\\\\sqrt{3}$, $0$ y $\\\\sqrt{3}$, consistente con $f(x) = x^3 - 3x$.",
            "feedback_incorrect": "La curva cruza el eje X en $-\\\\sqrt{3}$, $0$ y $\\\\sqrt{3}$ con pendiente positiva en el origen: $f(x) = x^3 - 3x$.",
            "graph_fn": "pow(x, 3) - 3*x", "graph_view": "[-3, 3, -5, 5]",
        },
        # ── EXPONENTIAL / LEXI ───────────────────────────────────────────
        {
            "course_id": 1, "belt": "white", "topic": "exponential", "skill": "LEXI",
            "subtype": "text",
            "question": "\\u00bfCu\\u00e1l de estas expresiones representa una funci\\u00f3n exponencial?",
            "option_a": "$f(x) = 5 \\\\cdot 2^x$", "option_b": "$f(x) = x^5$",
            "option_c": "$f(x) = 3x + 1$", "option_d": "$f(x) = \\\\ln(x)$",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! En una funci\\u00f3n exponencial, la variable $x$ aparece en el exponente: $f(x) = a \\\\cdot b^x$.",
            "feedback_incorrect": "En una funci\\u00f3n exponencial la variable est\\u00e1 en el exponente. La correcta es $f(x) = 5 \\\\cdot 2^x$.",
            "graph_fn": None, "graph_view": None,
        },
        {
            "course_id": 1, "belt": "white", "topic": "exponential", "skill": "LEXI",
            "subtype": "graph",
            "question": "\\u00bfC\\u00f3mo se llama la l\\u00ednea horizontal que esta curva se aproxima pero nunca alcanza?",
            "option_a": "As\\u00edntota horizontal", "option_b": "As\\u00edntota vertical",
            "option_c": "Eje de simetr\\u00eda", "option_d": "Tangente",
            "correct_index": 0, "has_math": False,
            "feedback_correct": "\\u00a1Correcto! Las funciones exponenciales tienen una as\\u00edntota horizontal ($y = 0$ en su forma b\\u00e1sica).",
            "feedback_incorrect": "La l\\u00ednea horizontal que una curva se aproxima infinitamente sin tocarla se llama as\\u00edntota horizontal.",
            "graph_fn": "pow(2, x)", "graph_view": "[-4, 4, -1, 10]",
        },
        # ── EXPONENTIAL / CLSF ───────────────────────────────────────────
        {
            "course_id": 1, "belt": "white", "topic": "exponential", "skill": "CLSF",
            "subtype": "graph",
            "question": "\\u00bfA qu\\u00e9 familia de funciones pertenece esta gr\\u00e1fica?",
            "option_a": "Exponencial", "option_b": "Polin\\u00f3mica",
            "option_c": "Logar\\u00edtmica", "option_d": "Lineal",
            "correct_index": 0, "has_math": False,
            "feedback_correct": "\\u00a1Correcto! La curva crece aceleradamente: $f(x) = 3 \\\\cdot 2^x$, una funci\\u00f3n exponencial.",
            "feedback_incorrect": "El crecimiento acelerado con as\\u00edntota en $y = 0$ es propio de una exponencial: $f(x) = 3 \\\\cdot 2^x$.",
            "graph_fn": "3 * pow(2, x)", "graph_view": "[-3, 3, -1, 12]",
        },
        {
            "course_id": 1, "belt": "white", "topic": "exponential", "skill": "CLSF",
            "subtype": "text",
            "question": "\\u00bfA qu\\u00e9 familia de funciones pertenece $f(x) = 3 \\\\cdot 2^x$?",
            "option_a": "Exponencial", "option_b": "Polin\\u00f3mica",
            "option_c": "Logar\\u00edtmica", "option_d": "Lineal",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! En $f(x) = 3 \\\\cdot 2^x$, la variable $x$ est\\u00e1 en el exponente: es una funci\\u00f3n exponencial.",
            "feedback_incorrect": "En $f(x) = 3 \\\\cdot 2^x$, la variable aparece en el exponente. Eso define una funci\\u00f3n exponencial.",
            "graph_fn": None, "graph_view": None,
        },
        # ── EXPONENTIAL / FORM ───────────────────────────────────────────
        {
            "course_id": 1, "belt": "white", "topic": "exponential", "skill": "FORM",
            "subtype": "text",
            "question": "En $f(x) = 3 \\\\cdot (0{,}5)^x$, \\u00bfcu\\u00e1l es la base de la exponencial?",
            "option_a": "$0{,}5$", "option_b": "$3$",
            "option_c": "$x$", "option_d": "$1{,}5$",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! En $f(x) = a \\\\cdot b^x$, la base es $b = 0{,}5$. Como $0 < b < 1$, la funci\\u00f3n es decreciente.",
            "feedback_incorrect": "En $f(x) = a \\\\cdot b^x$, $b$ es la base. Aqu\\u00ed $b = 0{,}5$.",
            "graph_fn": None, "graph_view": None,
        },
        {
            "course_id": 1, "belt": "white", "topic": "exponential", "skill": "FORM",
            "subtype": "graph",
            "question": "\\u00bfCu\\u00e1l de estas expresiones corresponde a la curva del gr\\u00e1fico?",
            "option_a": "$f(x) = (0{,}5)^x$", "option_b": "$f(x) = 2^x$",
            "option_c": "$f(x) = -2^x$", "option_d": "$f(x) = 2 \\\\cdot x$",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! La curva decrece hacia 0: base menor que 1, $f(x) = (0{,}5)^x$.",
            "feedback_incorrect": "La curva decrece (base $b < 1$) con as\\u00edntota en $y = 0$: corresponde a $f(x) = (0{,}5)^x$.",
            "graph_fn": "pow(0.5, x)", "graph_view": "[-3, 4, -0.5, 6]",
        },
        # ── LOGARITHMIC / LEXI ───────────────────────────────────────────
        {
            "course_id": 1, "belt": "white", "topic": "logarithmic", "skill": "LEXI",
            "subtype": "text",
            "question": "\\u00bfCu\\u00e1l de estas expresiones es una funci\\u00f3n logar\\u00edtmica?",
            "option_a": "$f(x) = \\\\log_2(x)$", "option_b": "$f(x) = 2^x$",
            "option_c": "$f(x) = x^2$", "option_d": "$f(x) = 1/x$",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! Una funci\\u00f3n logar\\u00edtmica tiene la forma $f(x) = \\\\log_a(x)$.",
            "feedback_incorrect": "Una funci\\u00f3n logar\\u00edtmica usa el logaritmo de la variable. La correcta es $f(x) = \\\\log_2(x)$.",
            "graph_fn": None, "graph_view": None,
        },
        {
            "course_id": 1, "belt": "white", "topic": "logarithmic", "skill": "LEXI",
            "subtype": "graph",
            "question": "\\u00bfC\\u00f3mo se llama la l\\u00ednea vertical que act\\u00faa como frontera para esta funci\\u00f3n?",
            "option_a": "As\\u00edntota vertical", "option_b": "As\\u00edntota horizontal",
            "option_c": "Eje de simetr\\u00eda", "option_d": "Tangente",
            "correct_index": 0, "has_math": False,
            "feedback_correct": "\\u00a1Correcto! Las funciones logar\\u00edtmicas tienen una as\\u00edntota vertical ($x = 0$ en su forma b\\u00e1sica).",
            "feedback_incorrect": "La l\\u00ednea vertical que la funci\\u00f3n no puede cruzar se llama as\\u00edntota vertical. Aqu\\u00ed est\\u00e1 en $x = 0$.",
            "graph_fn": "log2(x)", "graph_view": "[-0.5, 6, -4, 5]",
        },
        # ── LOGARITHMIC / CLSF ───────────────────────────────────────────
        {
            "course_id": 1, "belt": "white", "topic": "logarithmic", "skill": "CLSF",
            "subtype": "graph",
            "question": "\\u00bfA qu\\u00e9 familia de funciones pertenece esta gr\\u00e1fica?",
            "option_a": "Logar\\u00edtmica", "option_b": "Exponencial",
            "option_c": "Racional", "option_d": "Lineal",
            "correct_index": 0, "has_math": False,
            "feedback_correct": "\\u00a1Correcto! La curva crece lentamente para $x > 0$: $f(x) = \\\\log_2(x) + 1$, una funci\\u00f3n logar\\u00edtmica.",
            "feedback_incorrect": "La as\\u00edntota vertical en $x = 0$ y el crecimiento lento son propios de una logar\\u00edtmica: $f(x) = \\\\log_2(x) + 1$.",
            "graph_fn": "log2(x) + 1", "graph_view": "[-0.5, 6, -4, 5]",
        },
        {
            "course_id": 1, "belt": "white", "topic": "logarithmic", "skill": "CLSF",
            "subtype": "text",
            "question": "\\u00bfA qu\\u00e9 familia de funciones pertenece $f(x) = \\\\log_2(x) + 1$?",
            "option_a": "Logar\\u00edtmica", "option_b": "Exponencial",
            "option_c": "Racional", "option_d": "Lineal",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! $f(x) = \\\\log_2(x) + 1$ aplica un logaritmo a $x$: es una funci\\u00f3n logar\\u00edtmica.",
            "feedback_incorrect": "$f(x) = \\\\log_2(x) + 1$ usa el logaritmo de la variable: pertenece a la familia logar\\u00edtmica.",
            "graph_fn": None, "graph_view": None,
        },
        # ── LOGARITHMIC / FORM ───────────────────────────────────────────
        {
            "course_id": 1, "belt": "white", "topic": "logarithmic", "skill": "FORM",
            "subtype": "text",
            "question": "En $f(x) = \\\\log_5(x)$, \\u00bfcu\\u00e1l es la base del logaritmo?",
            "option_a": "$5$", "option_b": "$x$",
            "option_c": "$1$", "option_d": "$0$",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! En $\\\\log_5(x)$, el sub\\u00edndice $5$ es la base.",
            "feedback_incorrect": "En $\\\\log_a(x)$, $a$ es la base. En $\\\\log_5(x)$, la base es $5$.",
            "graph_fn": None, "graph_view": None,
        },
        {
            "course_id": 1, "belt": "white", "topic": "logarithmic", "skill": "FORM",
            "subtype": "graph",
            "question": "\\u00bfCu\\u00e1l de estas expresiones corresponde a la curva del gr\\u00e1fico?",
            "option_a": "$f(x) = \\\\log_2(x+1)$", "option_b": "$f(x) = \\\\log_2(x)$",
            "option_c": "$f(x) = \\\\log_2(x-1)$", "option_d": "$f(x) = -\\\\log_2(x+1)$",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! La curva pasa por (0, 0) y tiene as\\u00edntota en $x = -1$: $f(x) = \\\\log_2(x+1)$.",
            "feedback_incorrect": "La as\\u00edntota vertical en $x = -1$ y el cruce por el origen indican $f(x) = \\\\log_2(x+1)$.",
            "graph_fn": "log2(x + 1)", "graph_view": "[-1, 6, -3, 4]",
        },
        # ── TRIGONOMETRIC / LEXI ─────────────────────────────────────────
        {
            "course_id": 1, "belt": "white", "topic": "trigonometric", "skill": "LEXI",
            "subtype": "text",
            "question": "\\u00bfCu\\u00e1l de estas es una funci\\u00f3n trigonom\\u00e9trica?",
            "option_a": "$f(x) = \\\\operatorname{sen}(x)$", "option_b": "$f(x) = e^x$",
            "option_c": "$f(x) = x^3$", "option_d": "$f(x) = \\\\ln(x)$",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! El seno, coseno y tangente son las funciones trigonom\\u00e9tricas b\\u00e1sicas.",
            "feedback_incorrect": "Las funciones trigonom\\u00e9tricas son seno, coseno y tangente. La correcta es $f(x) = \\\\operatorname{sen}(x)$.",
            "graph_fn": None, "graph_view": None,
        },
        {
            "course_id": 1, "belt": "white", "topic": "trigonometric", "skill": "LEXI",
            "subtype": "graph",
            "question": "\\u00bfC\\u00f3mo se llama la distancia entre el valor m\\u00e1ximo de la curva y su eje de simetr\\u00eda horizontal?",
            "option_a": "Amplitud", "option_b": "Per\\u00edodo",
            "option_c": "Frecuencia", "option_d": "Fase",
            "correct_index": 0, "has_math": False,
            "feedback_correct": "\\u00a1Correcto! La amplitud es la distancia del m\\u00e1ximo (o m\\u00ednimo) al eje central. Aqu\\u00ed vale 2.",
            "feedback_incorrect": "Esa distancia se llama amplitud. En $f(x) = 2 \\\\cdot \\\\operatorname{sen}(x)$, la amplitud es 2.",
            "graph_fn": "2 * sin(x)", "graph_view": "[-7, 7, -3, 3]",
        },
        # ── TRIGONOMETRIC / CLSF ─────────────────────────────────────────
        {
            "course_id": 1, "belt": "white", "topic": "trigonometric", "skill": "CLSF",
            "subtype": "graph",
            "question": "\\u00bfA qu\\u00e9 familia de funciones pertenece esta gr\\u00e1fica?",
            "option_a": "Trigonom\\u00e9trica", "option_b": "Exponencial",
            "option_c": "Polin\\u00f3mica", "option_d": "Racional",
            "correct_index": 0, "has_math": False,
            "feedback_correct": "\\u00a1Correcto! La oscilaci\\u00f3n peri\\u00f3dica corresponde a $f(x) = 2 \\\\cdot \\\\operatorname{sen}(x)$, una funci\\u00f3n trigonom\\u00e9trica.",
            "feedback_incorrect": "La forma de onda peri\\u00f3dica entre \\u22122 y 2 es propia de una trigonom\\u00e9trica: $f(x) = 2 \\\\cdot \\\\operatorname{sen}(x)$.",
            "graph_fn": "2 * sin(x)", "graph_view": "[-7, 7, -3, 3]",
        },
        {
            "course_id": 1, "belt": "white", "topic": "trigonometric", "skill": "CLSF",
            "subtype": "text",
            "question": "\\u00bfA qu\\u00e9 familia de funciones pertenece $f(x) = 2\\\\operatorname{sen}(x)$?",
            "option_a": "Trigonom\\u00e9trica", "option_b": "Exponencial",
            "option_c": "Polin\\u00f3mica", "option_d": "Racional",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! $f(x) = 2\\\\operatorname{sen}(x)$ usa la funci\\u00f3n seno: es trigonom\\u00e9trica.",
            "feedback_incorrect": "La funci\\u00f3n seno pertenece a la familia trigonom\\u00e9trica. $f(x) = 2\\\\operatorname{sen}(x)$ es trigonom\\u00e9trica.",
            "graph_fn": None, "graph_view": None,
        },
        # ── TRIGONOMETRIC / FORM ─────────────────────────────────────────
        {
            "course_id": 1, "belt": "white", "topic": "trigonometric", "skill": "FORM",
            "subtype": "text",
            "question": "En $f(x) = 3\\\\operatorname{sen}(2x + \\\\pi/4)$, \\u00bfcu\\u00e1l es la amplitud?",
            "option_a": "$3$", "option_b": "$2$",
            "option_c": "$\\\\pi/4$", "option_d": "$1$",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! En $A \\\\cdot \\\\operatorname{sen}(Bx + C)$, la amplitud es $A = 3$.",
            "feedback_incorrect": "En $A \\\\cdot \\\\operatorname{sen}(Bx + C)$, $A$ es la amplitud. Aqu\\u00ed $A = 3$.",
            "graph_fn": None, "graph_view": None,
        },
        {
            "course_id": 1, "belt": "white", "topic": "trigonometric", "skill": "FORM",
            "subtype": "graph",
            "question": "\\u00bfCu\\u00e1l de estas expresiones corresponde a la curva del gr\\u00e1fico?",
            "option_a": "$f(x) = \\\\cos(x)$", "option_b": "$f(x) = \\\\operatorname{sen}(x)$",
            "option_c": "$f(x) = 2\\\\cos(x)$", "option_d": "$f(x) = \\\\cos(2x)$",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! La curva parte de su m\\u00e1ximo en $x = 0$ con amplitud 1: $f(x) = \\\\cos(x)$.",
            "feedback_incorrect": "La curva comienza en su valor m\\u00e1ximo (1) cuando $x = 0$: eso es $f(x) = \\\\cos(x)$, no el seno.",
            "graph_fn": "cos(x)", "graph_view": "[-7, 7, -3, 3]",
        },
        # ── RATIONAL / LEXI ──────────────────────────────────────────────
        {
            "course_id": 1, "belt": "white", "topic": "rational", "skill": "LEXI",
            "subtype": "text",
            "question": "\\u00bfCu\\u00e1l de estas es una funci\\u00f3n racional?",
            "option_a": "$f(x) = \\\\dfrac{x+1}{x-2}$", "option_b": "$f(x) = x^2 - 1$",
            "option_c": "$f(x) = 3^x$", "option_d": "$f(x) = \\\\sqrt{x}$",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! Una funci\\u00f3n racional es el cociente de dos polinomios.",
            "feedback_incorrect": "Una funci\\u00f3n racional es un cociente de polinomios. La correcta es $f(x) = \\\\dfrac{x+1}{x-2}$.",
            "graph_fn": None, "graph_view": None,
        },
        {
            "course_id": 1, "belt": "white", "topic": "rational", "skill": "LEXI",
            "subtype": "graph",
            "question": "\\u00bfC\\u00f3mo se llaman las l\\u00edneas que esta curva se aproxima pero nunca llega a tocar?",
            "option_a": "As\\u00edntotas", "option_b": "Tangentes",
            "option_c": "Ejes de simetr\\u00eda", "option_d": "Rectas directrices",
            "correct_index": 0, "has_math": False,
            "feedback_correct": "\\u00a1Correcto! Las l\\u00edneas que una curva se acerca indefinidamente sin tocar se llaman as\\u00edntotas.",
            "feedback_incorrect": "Esas l\\u00edneas se llaman as\\u00edntotas. Esta funci\\u00f3n racional tiene una vertical ($x = 2$) y una horizontal ($y = 1$).",
            "graph_fn": "(x + 1) / (x - 2)", "graph_view": "[-5, 7, -8, 8]",
        },
        # ── RATIONAL / CLSF ──────────────────────────────────────────────
        {
            "course_id": 1, "belt": "white", "topic": "rational", "skill": "CLSF",
            "subtype": "graph",
            "question": "\\u00bfA qu\\u00e9 familia de funciones pertenece esta gr\\u00e1fica?",
            "option_a": "Racional", "option_b": "Polin\\u00f3mica",
            "option_c": "Lineal", "option_d": "Logar\\u00edtmica",
            "correct_index": 0, "has_math": False,
            "feedback_correct": "\\u00a1Correcto! Las dos ramas con as\\u00edntotas corresponden a $f(x) = \\\\dfrac{x+1}{x-2}$, una funci\\u00f3n racional.",
            "feedback_incorrect": "Las as\\u00edntotas vertical y horizontal con dos ramas separadas son propias de una racional: $f(x) = \\\\dfrac{x+1}{x-2}$.",
            "graph_fn": "(x + 1) / (x - 2)", "graph_view": "[-5, 7, -8, 8]",
        },
        {
            "course_id": 1, "belt": "white", "topic": "rational", "skill": "CLSF",
            "subtype": "text",
            "question": "\\u00bfA qu\\u00e9 familia de funciones pertenece $f(x) = \\\\dfrac{x+1}{x-2}$?",
            "option_a": "Racional", "option_b": "Polin\\u00f3mica",
            "option_c": "Lineal", "option_d": "Logar\\u00edtmica",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! $\\\\dfrac{x+1}{x-2}$ es el cociente de dos polinomios: es una funci\\u00f3n racional.",
            "feedback_incorrect": "$f(x) = \\\\dfrac{x+1}{x-2}$ es un cociente de polinomios: pertenece a la familia racional.",
            "graph_fn": None, "graph_view": None,
        },
        # ── RATIONAL / FORM ──────────────────────────────────────────────
        {
            "course_id": 1, "belt": "white", "topic": "rational", "skill": "FORM",
            "subtype": "text",
            "question": "\\u00bfPara qu\\u00e9 valor de $x$ no est\\u00e1 definida $f(x) = \\\\dfrac{2x + 3}{x - 5}$?",
            "option_a": "$x = 5$", "option_b": "$x = 3$",
            "option_c": "$x = -3$", "option_d": "$x = 2$",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! La funci\\u00f3n no est\\u00e1 definida cuando el denominador se anula: $x - 5 = 0 \\\\Rightarrow x = 5$.",
            "feedback_incorrect": "La funci\\u00f3n no est\\u00e1 definida donde el denominador es cero: $x - 5 = 0 \\\\Rightarrow x = 5$.",
            "graph_fn": None, "graph_view": None,
        },
        {
            "course_id": 1, "belt": "white", "topic": "rational", "skill": "FORM",
            "subtype": "graph",
            "question": "\\u00bfCu\\u00e1l de estas expresiones corresponde a la curva del gr\\u00e1fico?",
            "option_a": "$f(x) = \\\\dfrac{1}{x-1}$", "option_b": "$f(x) = \\\\dfrac{1}{x+1}$",
            "option_c": "$f(x) = \\\\dfrac{x}{x-1}$", "option_d": "$f(x) = \\\\dfrac{1}{x^2-1}$",
            "correct_index": 0, "has_math": True,
            "feedback_correct": "\\u00a1Correcto! La as\\u00edntota vertical en $x = 1$ y la horizontal en $y = 0$ corresponden a $f(x) = \\\\dfrac{1}{x-1}$.",
            "feedback_incorrect": "La as\\u00edntota vertical est\\u00e1 en $x = 1$ (denominador = 0) y la horizontal en $y = 0$: $f(x) = \\\\dfrac{1}{x-1}$.",
            "graph_fn": "1 / (x - 1)", "graph_view": "[-4, 6, -6, 6]",
        },
    ]

    # op.bulk_insert(exercises_table, _seed)  # datos manejados por seed_content.py


def downgrade() -> None:
    op.drop_index('idx_exercises_lookup', table_name='exercises')
    op.drop_index('ix_exercises_id', table_name='exercises')
    op.drop_table('exercises')
